### ISSUE TITLE
Application to contrib team

### ISSUE THREAD

**Issue by miromichalicka** [backdrop-ops/contrib#10]
Hi, 

I have ported pathauto module. Find it here https://github.com/miromichalicka/backdrop_pathauto. It might require minor changes to work fine with contrib token, since it was developed with previous version.

**Comment by docwilmot** [comment]
Hi there @miromichalicka, and welcome. It might help to see the comment at https://github.com/backdrop-ops/contrib/issues/9#issuecomment-70367118.

It doesnt look like you quite converted the module yet though: you havent kept the commit history from the Drupal version, and  still uses variables, and doesnt have an upgrade path. 
Drupal modules may still work if you change the .info file, but thats just because Backdrop still recognizes Drupal functions (drupal_) through the compatibility layer. But both this layer and variables will have to go away eventually, so you will need to fully convert to the Backdrop way.

Hope you understand.

**Comment by miromichalicka** [comment]
Hi @docwilmot, 
I do not understand what does 'upgrade path' mean. I will work on the other things and then I will ping you to review it again.

**Comment by docwilmot** [comment]
> I do not understand what 'upgrade path' means

We think people with Drupal websites will want to switch to Backdrop instead of upgrading to D8. When they do, your module will need to be able to upgrade their existing data, especially converting variables to config. Theres some information here https://api.backdropcms.org/node/28621.

**Comment by quicksketch** [comment]
Hi @miromichalicka! Thanks for your work porting Pathauto! I agree with @docwilmot's recommendations, for a module like Pathauto with a long history, it'd be ideal to include the full project history by doing a Git checkout from drupal.org, then renaming the current branch to 1.x-1.x and pushing that up to Github.

An upgrade path is also important, but it looks like right now Pathauto is still using variable_get() and variable_set() instead of config_get() and config_set(), so there probably isn't much of an upgrade needed yet. We should convert that to config ASAP, so that you can benefit from Backdrop's main advantage over D7.

**Comment by quicksketch** [comment]
It looks like we ended up with another port getting into the repository at the same time. Dang, I hate wasted work. @miromichalicka, could you help by filing pull requests against PathAuto to help get it up to snuff? The current port has a number of bugs: https://github.com/backdrop-contrib/pathauto/issues

If you can help get that project up to speed, e.g. updating the README.md and fixing some of the issues through pull requests, that would probably work in lieu of porting a new module. Then we could add you (if you're interested) to the list of maintainers for the project.

**Comment by klonos** [comment]
@miromichalicka are you still interested in becoming a contrib member? Any other project you might have worked on by now?

**Comment by klonos** [comment]
Pathauto is now in Backdrop core 😄. See:

https://github.com/backdrop/backdrop-issues/issues/87
https://github.com/backdrop/backdrop/releases/tag/1.1.0
