### ISSUE TITLE
Port of Feed Import

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#104]
I have done initial work on a port of Feed Import as a means of importing existing data files into Backdrop, as mentioned by @klonos in https://github.com/backdrop-ops/contrib/issues/103

My port repository is initially at https://github.com/Graham-72/feed_import prior to testing.

**Comment by docwilmot** [comment]
Somebody somewhere thought that feeds import was too complicated. Haven't tried it myself but if it is more complex and less featured, it may be wiser to port Feeds instead. Have you guys actually compared the two?

**Comment by docwilmot** [comment]
Checked. Feeds+++. Feeds Import is quite a bit confusing and Feeds has more support. Missing Feeds features can be found in submodules.

**Comment by Graham-72** [comment]
@docwilmot  There is a lot more code in Feeds than in Feeds Import and therefore my impression was it would probably take a lot longer to port. But at the end of the day it probably depends on which will prove to be most usable. I will let you know how my attempt to import a CSV file goes.

**Comment by docwilmot** [comment]
Seems nearly half of the file count in Feeds is test files, which is a good thing. And it's a bit more modular. The Feeds Import module file is huge.

**Comment by Graham-72** [comment]
Thanks @docwilmot . It looks as though it will be well worth looking to port Feeds when time permits.

**Comment by docwilmot** [comment]
I gave Feeds port a try last night; got it to stop giving Ctools errors by brute force so far and its importing nodes from an RSS link. 

But just thought, why arent we porting ctools instead? Was there a specific reason?

**Comment by Graham-72** [comment]
@docwilmot well done and a good question. Hasn't some of it been included already?

I have a pressing need to import a CSV file into a Backdrop site. Please may I try your repo?

**Comment by docwilmot** [comment]
Go for it sir. https://github.com/docwilmot/feeds. Its a bit of a hack right now, so expect issues.

We have a few parts of ctools in core, and I made a standalone module out of the form wizard ctools code, but there are a lot of other bits in CTools; plugins seem to be the main thing most modules use. We can keep trying to work around CTools, or just port the rest of it and get it over with.

**Comment by Graham-72** [comment]
@docwilmot I had a try with your repo of feeds but immediately hit problems beyond my understanding!

So I have had another look at feed_import, with considerable success. I have been able to use it in Backdrop to upload a test CSV file successfuly, so I have moved my repo into backdrop-contrib - https://github.com/backdrop-contrib/feed_import

It seems my earlier problems were due to my failure to understand how to use the module. Now that I have had some success, though only with a CSV file, I would like to provide an elementary guide explaining how to get started. But where would I publish this in Backdrop? Perhaps as an issue on the repository - at least as a starting point?

**Comment by docwilmot** [comment]
Sorry, I hadnt looked at the CSV importer at all, just the node importer, thats likely the issue. I'll probably want to get it fully ported eventually, but Im not sure about the convert-vs-port-ctools decision. Maybe I should consult with @quicksketch on this. Should we port CTools? At least the bits that are not in core, which still seem considerable? Is there any technical reason why not?

**Comment by docwilmot** [comment]
> But where would I publish this in Backdrop?

The orginal idea is that we could use the GitHub wiki that's available for each project repository. I don't think anyone has actually done this yet, you'd be the pioneer. I think thats much better than overloading the READMEs like some of our project currently do.
https://github.com/backdrop-contrib/feed_import/wiki

**Comment by Graham-72** [comment]
>>The orginal idea was that we should use the GitHub wiki that's available for each project repository.

Thanks for the suggestion. I have made a simple start at https://github.com/backdrop-contrib/feed_import/wiki and over the next few days I will try adding more detail including screenshots of the admin pages.

**Comment by quicksketch** [comment]
> Should we port CTools? At least the bits that are not in core, which still seem considerable? Is there any technical reason why not?

So the primary parts of CTools that is not in core are "CTools plugins". The reason we did not include these in core is that they would have been a replacement for all *_info() hooks. And rather than having 2 ways of doing the same thing, we decided to stick with _info() hooks instead of converting them all to plugins. As we only moved a few things from CTools (e.g. Views "wizards" and the handlers from Panels and Page manager), it was much easier and more consistent with core to switch these to info hooks.

So in general, if you're porting a module that used CTools plugins, it's preferable to convert it to using info hooks instead.

Take for example our conversion of Views wizards into Backdrop. In Drupal 7, the existence of a wizard class was done via a file placed in a special directory (views_wizard). Here are the plugins for node and user:

https://api.drupal.org/api/views/plugins!views_wizard!node.inc/7
https://api.drupal.org/api/views/plugins!views_wizard!users.inc/7

In Backdrop we instead made a hook, `hook_views_ui_wizards()` and included the same information that had been in the plugin in it. See [`views_ui_views_ui_wizards()`](https://api.backdropcms.org/api/backdrop/core!modules!views_ui!views_ui.module/function/views_ui_views_ui_wizards/1).

Then when actually getting a list of wizards, both Backdrop and Drupal 7 have the same parent function `views_ui_get_wizards()`. The only difference is how we build the list:

[Backdrop views_ui_get_wizards()](https://api.backdropcms.org/api/backdrop/core!modules!views_ui!views_ui.module/function/views_ui_get_wizards/1)
```
  $wizard_plugins = module_invoke_all('views_ui_wizards');
```

[Drupal 7 views_ui_get_wizards()](https://api.drupal.org/api/views/views_ui.module/function/views_ui_get_wizards/7)
```php
  ctools_include('plugins');
  $wizard_plugins = ctools_get_plugins('views_ui', 'views_wizard');
```

So, in general you can avoid using a plugin by doing the following:
- Move any `$plugin = array()` definitions from CTools plugin files into a new *_info() hook of you making.
- Find the place where previously your module called `ctools_get_plugins()` and change it instead to be `module_invoke_all('your_new_info')`.
- If necessary, include a `'file'` value in the info hook to point at the plugin file. Then module_load_include() this file before calling its functions. In the case of Views wizards, that wasn't necessary because they are all classes and use the autoloader to load themselves.

**Comment by Graham-72** [comment]
I am making some progress with the port of Feed Import and have moved the repository to https://github.com/backdrop-contrib/feed_import

I have successfully imported a medium sized CSV file (90+ files, 35+ columns) and this raised various issues to do with understanding how to configure the module's admin settings. Also, the CSV import seems very sensitive to field content, much more so than, for example, importing a CSV file into a MySQL datatable with phpMyAdmin.

**Comment by jenlampton** [comment]
Closing this issue because https://github.com/backdrop-contrib/feed_import exists now.  Please continue all conversation about feed_import module in the feed_import issue queue.
