### ISSUE TITLE
Application Request

### ISSUE THREAD

**Issue by matthewdorman** [backdrop-ops/contrib#107]
Hi,

I'd like to joing the contributor group. I have a module that I've done an initial port from D7/8 to Backdrop, here's the Backdrop branch: https://github.com/ndevrinc/wpmenu/tree/1.x-1.x

Yes, it's the WordPress menu. :) I'll of course make any additional changes based on the requirements, I'm looking to maintain this module for D7, D8 and Backdrop as long as I can so I'm hoping to find some good write ups on others doing the same.

Thanks!
Matt

**Comment by quicksketch** [comment]
Nice, welcome @matthewdorman!

This looks great and we always love to have new contributors.
All projects must meet a few minimum requirements:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

So if you could A) add a LICENSE.txt file (you don't have to do that on Drupal.org, but it's recommended in our repositories) and B) Build out the README.md a little more. Because we don't have strict access control on GitHub, we maintain the "official" list of maintainers in the README.md file. You can use the example for reference.

----

Other than that, this looks good and it'll be nice to have it in Backdrop. The port is probably working as-is, but if you're interested in making it work without the Drupal-compatibility mode turned on, I'd recommend doing a find/replace for all function calls containing "drupal" and replace them with "backdrop".

**Comment by matthewdorman** [comment]
Thanks Nate,

I think I'm good to go, well as far as requirements go at least. Thanks for the reminder about the compatibility mode settings, made the changes and turned that off.

https://github.com/ndevrinc/wpmenu/tree/1.x-1.x

-Matt

**Comment by quicksketch** [comment]
Awesome! Looks great. Thanks @matthewdorman! I've sent an invite for the group through GitHub. Welcome to the Backdrop community. It'll be a pleasure working with you. :smile:

You can transfer the project to the Backdrop contrib group as described in http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2

When you're ready to make an official release, follow these steps:

- Make sure you have a `type = module` line in your .info file.
- Tag the module with the version (e.g. `1.x-1.0.0`) and push to GitHub. 
- Create a release on GitHub for that tag.
- The entire Backdrop contrib group is synced with backdropcms.org. So if everything went well, your module will show up under http://backdropcms.org/modules. If something went wrong, you'll get a PACKAGING_ERRORS.txt file attached to your release on GitHub, explaining what the problem is.

Thanks again!
