### ISSUE TITLE
bootstrap backport

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-ops/contrib#109]
Hi Guys.

First release(backport) of bootstrap 3.3.5 for backdrop.

Thanks.

**Comment by quicksketch** [comment]
Woot! Thanks Gor! Where is it? If you're not in the contrib group already, we can get you access. First we have to do the basic README, LICENSE, etc. check per the README at https://github.com/backdrop-ops/contrib. Could you push it to you individual account for review?

**Comment by Gormartsen** [comment]
Hi,
Hm, I forgot to post link. https://github.com/itpatrol/bootstrap
I am not contrib group. I would appreciate access to contrib group.

**Comment by Gormartsen** [comment]
I am working on demo site. 
I will update readme, when it's done.

**Comment by quicksketch** [comment]
Great! Here's our checklist for new projects:

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

---

The README you've got is pretty close, but we need a list of maintainers (see the example linked above). It looks like this doesn't maintain the history from D7. You may need to recreate your repository by doing a fresh checkout from Drupal.org, then copying your new version over the top. Commit the changes then push up to GitHub.

**Comment by Gormartsen** [comment]
Ok, I will.
But looks like, there is almost none original code left.
I really cut it down and completely rewrite for backdrop features.

**Comment by Gormartsen** [comment]
@quicksketch I updated README and Did my best to get GIT history from drupal 7 by your article.
Please review.

**Comment by Gormartsen** [comment]
Added demo http://bootstrap.backdrop.expert

**Comment by quicksketch** [comment]
Thanks @Gormartsen! Looking much better. Good enough for initial moving into the Contrib repository.

A few things I found that could be improved:

- There are still lot of `drupal_*` functions, like drupal_get_title() and drupal_get_path(). If you just do a simple find/replace for drupal_ with backdrop_ you can clean a lot of those up. Although the compatibility mode is enabled by default in settings.php, it'd be great to get this "native" so it didn't depend on any of the old Drupal-namespaced functions.
- The first paragraph of your README.md will be used as the summary in the themes listing at https://backdropcms.org/themes, so it would be great to use a more verbose description than "ported from Drupal Bootstrap theme 7.x-3.0", as that will otherwise be the summary.

But it's a great start! I'll send you an invite to the contrib group and you can transfer the project. Please make an official release as soon as you feel it's ready for public use. Thanks!

**Comment by quicksketch** [comment]
Invite has been sent, let me know if you have any trouble. Thanks!

**Comment by Gormartsen** [comment]
@quicksketch Tnx. I've got invite.
I was waiting to have a talk with @markcarver.

Looks like they are going to add backdrop support to original code.
I will rename my project to do not miss lead people.

It is going to be separated from original bootstrap drupal project

**Comment by Gormartsen** [comment]
@quicksketch Ok, I renamed theme and posted to backdrop-contrib
https://github.com/backdrop-contrib/bootstrap_lite
