### ISSUE TITLE
Request : Node Detail View module port

### ISSUE THREAD

**Issue by gauravjeet** [backdrop-ops/contrib#114]
Hi there, I have a D7 module called Node Detail View that I am very much interested to port to Backdrop CMS. I think this could be a good UI for admins/content producer who manage this CMS. I've just started to port my module.
Would love to port my other modules as well later.

Module link - https://www.drupal.org/project/node_detail_view
My Github - https://github.com/gauravjeet/
Module Backdrop branch - https://github.com/gauravjeet/node_detail_view/tree/backdrop

Let me know if there is anything I missed out.

**Comment by klonos** [comment]
Hey there @gauravjeet and thank you for starting to port your modules to Backdrop. In case you were not following the development of Backdrop since early on, I would like to point to you that most admin page listings have either already been converted to views (once we got Views is in Backdrop core) or are in the process of being converted to views. You can see the progress of this task here: https://github.com/backdrop/backdrop-issues/issues/151

The content listing page itself (```/admin/content/node```) is already a view (https://github.com/backdrop/backdrop-issues/issues/150) and I was wondering if there might be a way to achieve what Node Detail View does with only what is already available in Backdrop core. In other words perhaps by editing the default "*Admin Content*" view or simply by providing another view. One of the main reasons why we initially decided to convert listings to views was to empower people to be able to change the admin UI to present things the way they see fit for them ...without using other contrib modules if possible.

**Comment by gauravjeet** [comment]
Hi @klonos, thanks for the reply. Yes, Views is in Backdrop core now and I have started looking for a workaround to edit the `admin/content` page. One solution can be to use `hook_views_pre_render()`, even though this hook is too late in the process, the module only gives an option to change the layout of this page to show a new section on the page that renders and shows the node (hope you must have seen a demo on a D7 test site), or another solution could be to create another View altogether and replace the default `admin/content/node` View.

**Comment by klonos** [comment]
Instead of overriding the default view, perhaps you could try creating your custom view as a separate display of the default view. (in a separate URL, say ```/admin/content/node/details```) and then use the "Menu" setting to have that render as a tab:

![backdrop-ops-contrib-issue114-view_display_as_tab-step1](https://cloud.githubusercontent.com/assets/2423362/10696721/3e351c9c-79f5-11e5-87e2-db4641c79718.png)
![backdrop-ops-contrib-issue114-view_display_as_tab-step2](https://cloud.githubusercontent.com/assets/2423362/10696723/3e595fc6-79f5-11e5-8651-c79296bcc569.png)
![backdrop-ops-contrib-issue114-view_display_as_tab-step3](https://cloud.githubusercontent.com/assets/2423362/10696724/3e69a1a6-79f5-11e5-8bf1-86ef95c56faa.png)
![backdrop-ops-contrib-issue114-view_display_as_tab-step4](https://cloud.githubusercontent.com/assets/2423362/10696725/3e8e0bfe-79f5-11e5-882c-3525d57cbc1b.png)
![backdrop-ops-contrib-issue114-view_display_as_tab-step5](https://cloud.githubusercontent.com/assets/2423362/10696727/3ed9ae60-79f5-11e5-934e-cb8920479f99.png)
![backdrop-ops-contrib-issue114-view_display_as_tab-step6](https://cloud.githubusercontent.com/assets/2423362/10696726/3ea03c66-79f5-11e5-909b-ae4dc52abeaf.png)
![backdrop-ops-contrib-issue114-view_display_as_tab-step7](https://cloud.githubusercontent.com/assets/2423362/10696728/3ee92494-79f5-11e5-97b7-9db8402aa009.png)

**Comment by klonos** [comment]
...don't you just :heart: Views? ...in core baby!!

![yeah-baby-yeah](https://cloud.githubusercontent.com/assets/2423362/10696811/cbc9e628-79f5-11e5-8afe-65cd79f38ea3.jpg)

**Comment by gauravjeet** [comment]
AWESOME man :))
that's the way to do it.. thnks

**Comment by klonos** [comment]
Hello @gauravjeet 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
