### ISSUE TITLE
Contrib

### ISSUE THREAD

**Issue by dyrer** [backdrop-ops/contrib#122]
Hello, 
I would like to contribute to backdrop cms
Thanks in advance

**Comment by quicksketch** [comment]
Hi @dyrer, Welcome!

We would love to have your help working on Backdrop. :smile:

To contribute a module, we ask that you put the module you've ported or written up in your personal GitHub account so that we can review it. It should be fully ported to Backdrop without using the Drupal compatibility mode setting in settings.php.

We require that at minimum, the following steps have been done:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Once the module has been reviewed, we can add you to the Backdrop Contrib group, and you can then transfer the module into http://github.com/backdrop-contrib. Please let me know if you have any questions.

**Comment by docwilmot** [comment]
Now that we're accepting logins on BackdropCMS.org can we automate this now? A form with all of this?

**Comment by dyrer** [comment]
I tried that, to create a new account and get message "You are not authorized to access this page."

**Comment by docwilmot** [comment]
Sorry, @dyrer, my comment was for @quicksketch, not you. I thought I saw on Twitter that you could create an account now, maybe I was wrong.

**Comment by dyrer** [comment]
I saw that too @docwilmot

**Comment by quicksketch** [comment]
> I tried that, to create a new account and get message "You are not authorized to access this page."

Huh! Not relevant to our current task but this gives you a 403? https://backdropcms.org/user/register

If it's giving us problems, let's make an issue over in http://github.com/backdrop-ops/backdropcms.org/issues.

> Now that we're accepting logins on BackdropCMS.org can we automate this now? A form with all of this?

Maybe? We can talk about it in an issue. :smile:

**Comment by docwilmot** [comment]
> Maybe? We can talk about it in an issue. :smile:

Done

**Comment by klonos** [comment]
@dyrer καλώς ήλθες πατρίδα!

**Comment by jenlampton** [comment]
> καλώς ήλθες πατρίδα!

@klonos :+1: 

> I would like to contribute to backdrop cms

 Hi @dyrer, Welcome!

If you do not have a module (or theme, or layout) that you have created or ported and is ready to be contributed, you are also welcome to co-maintain a module or theme along side the current maintainer. I myself have my name on too many projects at the moment, and would love some assistance :) Do you have a favorite module, theme, or layout you would feel comfortable maintaining?

If so, we can help you through that process too. 

If not, then you are welcome to contribute to backdrop by helping us with core - we could always use more help [in the issue queue](https://github.com/backdrop/backdrop-issues/issues).  Unfortunately, PHPStorm licenses aren't available for core developers, only for contrib at this time.

**Comment by jenlampton** [comment]
Since the maintainer request was also done in https://github.com/backdrop-ops/contrib/issues/176, I'm going to close this issue to clean up the queue.
