### ISSUE TITLE
Submitting Location module port

### ISSUE THREAD

**Issue by earthday47** [backdrop-ops/contrib#129]
Hello! I'm a long time Drupaller and a maintainer of a few modules on d.o.

I would like to submit my port of Location (https://www.drupal.org/project/location) module. The code is hosted here:

https://github.com/earthday47/backdrop-location

I have only ported the functionality for core `location` and `location_node` submodule. There are several other modules and `gmap` integration that I would like to finish up in the future.

Steps I have taken for this project:
 1. update .info file
 2. update all instances of `variable_get()` and `variable_set()` to use config.
 3. Rename some variables to get rid of `location_` prefix.
 4. Add default config json.
 5. replace system_settings_form().
 6. Add LICENSE.txt
 7. Add README.md

I hope everything is order. Really looking forward to growing Backdrop's contrib!!!!

-Wes

**Comment by jenlampton** [comment]
Hello @earthday47 and welcome to the backdrop contrib group!  This port is looking fantastic so far, great start :)

I would like to ask you to change the name of the project from `backdrop-lcoation` to just `location`, so that when it moves into the `backdrop-contrib` group you'll get the namespace.  

Otherwise, carry on, and feel free to ask us if you have any questions. This is likely going to be one of the tougher ports since it has a few ctools plugins that will need to be converted as well.

**Comment by earthday47** [comment]
Hi @jenlampton sounds good.

This is actually an application to become a contributor ;) should I make another issue?

**Comment by quicksketch** [comment]
Hi @earthday47! I'm excited to see these contributions as well! The ports are looking really good!

I found a couple items of feedback just browsing over the code:

- Add `type = module` to the .info files. This isn't required for Backdrop to find them, but it is required for the packager to make official releases.
- A couple of lingering calls to Drupal functions, such as `drupal_get_path()`, should be switched to `backdrop_*` so that the module can run with compatibility mode turned off in settings.php.
- `variable_get('site_default_country', 'us')` can be switched to `config_get('system.date', 'default_country')`

But, the main items are all there!

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

So if you would just accept the following agreement for the record, then I'll send you an invite and you can transfer the projects and get them listed on backdropcms.org (which we would *love*)!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by earthday47** [comment]
Awesome, thanks @quicksketch , those will be my next to-do items.

I accept the Backdrop Contributed Project Agreement.

Looking forward to the future ;)
-Wes

**Comment by quicksketch** [comment]
Invite sent! You're a member of the "Authors" group. Be sure that you grant this group permission when transferring repositories, as it's possible to lock yourself out of the transferred project (which is totally silly). Let me know if you have any questions!

Welcome again!! :smile:
