### ISSUE TITLE
AES module porting

### ISSUE THREAD

**Issue by ShurikBarkov** [backdrop-ops/contrib#13]
Hello, 

During Drupal Global Sprint Weekend (https://www.drupal.org/node/2406601) we have ported Drupal 7.x module AES to Backdrop.

https://github.com/ShurikBarkov/aes-backdrop

If you interested, transfer it to Backdrop Contributed Project Group and leave users listed bellow as contributors.

https://github.com/ShurikBarkov
https://github.com/dpovshed

Thank you.

**Comment by quicksketch** [comment]
Hi @ShurikBarkov! Thanks for doing this port! How exciting. We'd love to include the module in the contrib repository for Backdrop. We need to do a little cleanup to put it in though:

- Because we do not (yet) have a packaging script on Github, we need to add the LICENSE.txt file to the repository.
- For consistency, it'd be great if you could update the README.md to follow the general pattern provided in https://github.com/backdrop-ops/contrib/tree/master/examples
- And it would be ideal to maintain the entire history of the AES module. To do this, do a Git checkout of the 7.x-1.x branch, rename it to 1.x-1.x (For Backdrop 1.x) and then copy/commit your port over the top of it.

**Comment by quicksketch** [comment]
Hi @ShurikBarkov, if you're still interested in transferring this project to the contrib group, we need those few items I mentioned in the last comment. Since we haven't heard anything in a few weeks, I'm going to close this issue. Please reopen it if you're still interested in transferring the project. Thanks!

**Comment by ShurikBarkov** [comment]
Hi, @quicksketch, I'll do this in the near future.
Please reopen the issue.
Thanks.

**Comment by ShurikBarkov** [comment]
Dear @quicksketch, all of your requirements were applied.
 
https://github.com/ShurikBarkov/aes-backdrop

Please check. 
Now is your turn!

**Comment by quicksketch** [comment]
It looks great @ShurikBarkov! Thanks for making these changes! You could probably delete the `README.txt` file, since it's replaced by the `README.md`. All requirements are met now (README, LICENSE, project history). The GitHub invite should be on its way. You should be able to transfer the project into the Contirb group now. Thanks!
