### ISSUE TITLE
Porting Content Theme module

### ISSUE THREAD

**Issue by rstamm** [backdrop-ops/contrib#131]
You can find it here:
https://github.com/rstamm/backdrop-content_theme

d.o. project page:
https://www.drupal.org/project/content_theme

**Comment by quicksketch** [comment]
Awesome @rstamm! Welcome! We'll handle your application over in the other issue you made at https://github.com/backdrop-ops/contrib/issues/130.

In that other issue I noted that you might want to use configuration files for storing your theme configuration. In this module, I think you're doing the right thing using the database, because it contains node IDs. Overall, looks like a neat module and I'm really excited to have your modules ported to Backdrop!

**Comment by quicksketch** [comment]
We've approved your application over in https://github.com/backdrop-ops/contrib/issues/130. Please let me know if you have any questions!
