### ISSUE TITLE
Join group

### ISSUE THREAD

**Issue by pifbits** [backdrop-ops/contrib#153]
I will do my best to help convert what I can. D8 is too time-consuming for me. Thx

**Comment by klonos** [comment]
Hi there @pifbits! In order to be able to port modules and post them to the contrib group, you'll need to submit an initial module for review. You can do that by cloning the Drupal repository of the module you intent to port into your own GitHub profile. Then you make the necessary changes and once ready, you can post a comment here to request a review. What we are ask as the minimum is this:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Let us know if we can help in any way.

**Comment by klonos** [comment]
Hello @pifbits 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
