### ISSUE TITLE
Start porting i18n

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#155]
Noticed a distinct need for language related help, so this is a start on i18n. It will not work as is, haven't tested, so don't use in production. It's here so hopefully we can collaborate and fix it. 

So far only work done is to get it installing without error and to get the settings page for the main module and i18n strings working. Have not touched any of the other submodules at all.

Please if you try this, list whats broken in detail, on the module's issue queue.

**Comment by quicksketch** [comment]
Thanks @docwilmot! That's not a small undertaking!

Here's the module link for reference: https://github.com/backdrop-contrib/i18n

**Comment by docwilmot** [comment]
I agree its a bit of work @quicksketch and even more so that I dont even know how to use it, so I have no idea what to check to see if its working. :smile: 

We just need some of our foreign language users/devs to test and report.

**Comment by gifad** [comment]
> foreign language users/devs

AFAIK, i18n is not at all about _foreign_ language, where Backdrop is fine (with help of localize.drupal.org).
It's about multiple languages, whether they are _foreign_ or not, in a single web site…

**Comment by docwilmot** [comment]
You are correct of course. I imagined that non English speaking users may more likely have used this and know how it works, but that's probably not necessarily so.

**Comment by gifad** [comment]
Yes you're right; I was just reacting to the word _foreign_, which for too many people means _"on the other (i.e. bad) side of the wall".
Thank's for giving your time to help break this wall…

**Comment by klonos** [comment]
Yeah, I kinda had the same reaction as @gifad when I saw "foreign", but I know native English speakers use it in order to refer to non-English languages. They mean well though. Especially in open-source software. ...AND especially people like @docwilmot :wink: 

Just as a reference, in Greek, even in official documents like CVs we use the phrase "ξένες γλώσσες" which literally translates to "foreign languages" instead of using for example "other languages spoken". It doesn't mean that it is used in any discriminating way though.

BTW, anyone watched [My Big Fat Greek Wedding](http://www.imdb.com/title/tt0259446/) might remember the dad say "I can't believe my daughter is getting married to a *kseno*" ...which means "foreigner" or "stranger" in Greek.

**Comment by klonos** [comment]
...in the entire movie, Gas is behaving if not in a cutely racist way, then perhaps in a "strongly ethnically-favoring" one, but I love [his speech at the end](https://www.youtube.com/watch?v=epu_zBlX4tA&feature=youtu.be&t=641).

**Comment by mikemccaffrey** [comment]
Well, since core is written in English, maybe we should refer to alternate
systems of communication as Contributed Languages...  ;-)

**Comment by klonos** [comment]
Sounds reasonable to me since these are most likely going to be .po files that will live in contrib (or served directly from a localization server).

**Comment by klonos** [comment]
> alternate systems of communication

:smile:

**Comment by klonos** [comment]
..."additional languages" might be a good way to refer to them officially in documentation. They do are not shipped with core, but they can be *added*, so *additional*.

**Comment by gifad** [comment]
This time, I'll be serious : is there a milestone for a localize.backdrop.org ?

**Comment by klonos** [comment]
@gifad That's a question to be asked in https://github.com/backdrop-ops/backdropcms.org/issues but I agree that this should be on the official roadmap (even if we need to postpone it because of no time/energy/resources).

**Comment by herbdool** [comment]
Great start @docwilmot. I had given a go at this on my own account but stopped when I didn't really need ASAP. I18n taxonomy was difficult and particularly hard will be the submodules that heavily rely on Variable.

I've used it on sites for English/French (quite common in Canada) plus for a law firm site in four languages. It's a byzantine set of modules

**Comment by docwilmot** [comment]
Great to hear @herbdool. You think you could PR your progress to this repo? And/or please feel free to consider yourself a maintainer of this.

And what exactly is the i18n_variable submodule supposed to do anyway? Didnt pay much attention to it.

**Comment by herbdool** [comment]
I think it would take a bit of work to do a PR since I started porting it separately. I'd need to fork the version on backdrop-contrib and then copy/paste changes, then do a PR from that. I'll hopefully be able to help with that in the upcoming months.

There's a few places where Variable pokes up its head and not just in i18n_variable. It allows for a more complex saving of variables, particularly for different languages. It would be nice to avoid also porting Variable but it's heavily integrated into some of the submodules.

**Comment by indigoxela** [comment]
Just found this issue here - which IMO can get closed: https://backdropcms.org/project/i18n

**Comment by olafgrabienski** [comment]
Added the "Port complete" label.
