### ISSUE TITLE
becoming group member and porting modules

### ISSUE THREAD

**Issue by asherry** [backdrop-ops/contrib#156]
Hello, I got a request to port one of the modules I maintain on d.o to backdrop and I'd like to support that myself. I think I have to apply to join first correct?
It will be the d3 module, and I'm a maintainer and co-maintainer of a few other projects that I can port when the time comes as well.

**Comment by klonos** [comment]
Hello @asherry and welcome to Backdrop!

I believe that the process is to first get the code to a GitHub repo retaining the commit history from d.org. Then you can post a link of the repo here so we can review it, the basic requirements we ask are as follows:

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
...let us know when it is ready for the initial review.

**Comment by quicksketch** [comment]
Welcome @asherry! We would *love* to see the D3 module available for Backdrop! I saw you present on it at Stanford Camp last year and it looks fantastic!

We do a consistency review (following the checklist @klonos posted), but I promise it's a simple process. We need things like the README.md file to be updated because it gets used as the project page on backdropcms.org (e.g. https://backdropcms.org/project/honeypot). As the author of the module, maintaining the Git history is optional if you have been the only committer, but it's best to keep the history from D7 just for reference.

**Comment by klonos** [comment]
Hello @asherry 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
