### ISSUE TITLE
Permission to start porting some (very basic) modules.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#157]
I think I'm going to give a go at learning a bit more about git and GitHub and a bit more about php and modules. So, the plan is to start "playing around" with a few "small" contrib modules. *But* given the fact that a) I have very limited time and b) I am a total noob at this, is it ok to start "experimenting" with actual modules and porting them from d.org? I'm asking because I do not expect to be either prompt or good at this. What I'm trying to say is that I will be a horrible maintainer. Nevertheless, I am willing to try and improve.

So, can I?

**Comment by klonos** [comment]
I plan to start with https://www.drupal.org/project/fixteaserlinks in order to help @bd0bd with https://github.com/backdrop/backdrop-issues/issues/1787

**Comment by gifad** [comment]
:+1: :+1: This will be an excellent showcase about locating backdrop vs D7 vs D8
From a linguistic point of view, it will show how backdrop uses D7 words to express D8 concepts…

[Note] you should fix the "Backdrop" link in your D.o message “start porting this module to _Backdrop_ …“

**Comment by docwilmot** [comment]
There's no rule against porting anything as far as I recall.  So no need to ask permission.

**Comment by klonos** [comment]
> [Note] you should fix the "Backdrop" link in your D.o message “start porting this module to Backdrop …“

Done. Thanx :wink: 

> There's no rule against porting anything as far as I recall. So no need to ask permission.

I am a non-coder contributor. I was given certain permissions on the contrib repository with the intention to be for example triaging issues in the queue (being able to edit issue summaries even if the issues are not created by me, being able to close issues or edit labels etc.) I was never officially asked nor have I officially accepted the [Backdrop Contributed Project Group Application](https://github.com/backdrop-ops/contrib/blob/master/README.md).

Although these permissions also granted me commit access, it was agreed that should I ever decide I want to contribute actual code, I will have to go through the process that others undergo. Hence this issue here. Hence waiting to be asked if I agree and then accept :wink:

**Comment by klonos** [comment]
...in the mean time (while waiting to be asked if I agree to the terms of the Agreement), I have cloned the project from d.org to my personal GitHub account in https://github.com/klonos/fixteaserlinks and here are a few questions:

1. I want to update the README.md and also add a LICENSE.txt, but I'm scared that if I do so, I will accidentally "push" or "commit" (sorry I am not familiar with the terminology) something back to the d.org project and upset the maintainer. So, the question is: if I change something in my repo (or the one in contrib once I transfer it), do these changes get propagated back to d.org?

2. The cloning transferred both the 7.x as well as the 8.x branches from d.org. Is it safe to delete the 8.x branch on my repo, or will it also delete the branch form d.org?

3. After removing the 8.x branch, do I rename the 7.x or start a new 1.x for Backdrop?

That's it ...for now.

**Comment by gifad** [comment]
@klonos : the process is perfectly described here : [How to Maintain Contrib Modules for Drupal and Backdrop at the Same Time - Part 2](https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
That's the guide I followed.

**Comment by docwilmot** [comment]
@klonos I personally use [GitHub for Windows](https://desktop.github.com/) and Notepad++ but you can get an IDE (we get free PHPStorm licences).

The following is probably terribly uncool, since I've had to learn all this stuff recently from myriad Googlings. But these are the thoughts that come to mind.

You'll need to clone the project to your local machine. I tend to clone all of them to the `/modules` folder of an actual local install of Backdrop, so I can immediately enable and install. (The active local install is itself a clone of the Backdrop project).

Then figure out how to use the command line tool; once youve figured it, you can delete the Drupal remote (usually `git remote rm origin`). But in either case, unless you have commit access to Drupal, I dont believe your changes will be pushed to the original project repo on Drupal.

Particularly get used to creating new branches whenever you want to add new changes. If you dont like what youve done, you go back to the original master branch. Delete the 'mistake' branch, or just ignore it. If you like what youve done, you can merge in that branch. So feel free to delete all the unneeded Drupal branches too. I usually make a new 1.x branch from the 7.x branch then I delete the 7.x. Or leave them all there and ignore them and just do all your work in the 1.x and branches created off 1.x.

Only when youve created a branch that you like you can push it up to your online GitHub repo and PR to the Backdrop contrib.

Theres of course a lot more to it than this, but this is where you'd want to start. 

Anyone else have any other thoughts?

**Comment by klonos** [comment]
Thanx @docwilmot! Lots of things to grok, but as you say a good start.

Seems a really good practice to have the local dev of Backdrop actually be a clone of the project and the modules one works on cloned inside the `/modules` dir of the local Backdrop clone. Excellent thinking :+1: I will surely try that.

**Comment by klonos** [comment]
...seems to me though that I shouldn't be using that local clone for core PRs as those would include the contrib modules from the `/modules` dir. Should use a separate clone for that.

**Comment by docwilmot** [comment]
>...seems to me though that I shouldn't be using that local clone for core PRs, as those would include the contrib modules from the /modules dir

There is (or you can copy there) a `.gitignore` file in the root of the Backdrop repo; you put `/module` in there and core PRs will ignore it. Same for themes, layouts etc.

**Comment by klonos** [comment]
I had GitHub Desktop installed already! :smile: Never actually used it though. ...version 2.13.2.4 ...updating now.

**Comment by klonos** [comment]
> There is (or you can copy there) a `.gitignore` file in the root of the Backdrop repo; you put `/module` in there and core PRs will ignore it. Same for themes, layouts etc.

**Comment by gifad** [comment]
@klonos : for this particular module, don't throw the drupal 8 branch too early : it will be a great help for porting — not on the "how to do" side, but on "what to do" — and you will learn what is CMI :scream:

**Comment by klonos** [comment]
[Permission granted](https://www.drupal.org/node/2699655#comment-11036329) by the current module maintainer, so good to go!

**Comment by klonos** [comment]
I have created a new 1.x branch from the 7.x-1.x and made it the default one:

![github-klonos-fixteaserlinks-created_1 x_branch_and_locked_7 x_and_8 x](https://cloud.githubusercontent.com/assets/2423362/14269904/654fd976-fb2c-11e5-851a-18ff967e4afa.png)

...also "locked" the 7.x and 8.x branches from changes. Hope I've done the right thing.

**Comment by klonos** [comment]
...[added the default LICENSE.txt](https://github.com/klonos/fixteaserlinks/blob/1.x/LICENSE.txt)

**Comment by klonos** [comment]
...will take some time to edit the README.md. Will update here once done.

**Comment by quicksketch** [comment]
Doing great @klonos! I usually delete the 7.x-1.x and 8.x-1.x branches. You won't need them any more. So to delete them you need to actually remove them from being "protected" then use:

```
git branch -D 7.x-1.x
git push origin :7.x-1.x
```

I have no idea why someone thought a colon should mean "delete the remote branch", but there you go.

You should also rename the `1.x` branch to `1.x-1.x`. Although we don't strictly enforce it at this time, it means "Backdrop 1.x compatible --- The 1.x version of this module". Because in the future you could have version number for the module that differs from the version of Backdrop it is compatible with e.g. `1.x-2.x` or `2.x-1.x`. It's a bit of a weird convention, but we inherited it from Drupal.

**Comment by klonos** [comment]
OK, after a looong time I'm getting back to this (I will at the same time try to port https://www.drupal.org/project/rename_admin_paths), but I am going to need some mentoring...

I removed the 7.x and 8.x branches, renamed the 1.x to 1.x-1.x and edited the README.md, so from the checklist standpoint I think I'm OK. So, ...

I hereby agree to the terms listed in https://github.com/backdrop-ops/contrib/blob/master/README.md and officially request permission to the contrib group as a coder/contributor (I already have non-coder permission) so I can transfer my project repo(s) under contrib.

**Comment by klonos** [comment]
@quicksketch, @jenlampton, can have your official consent please?

**Comment by docwilmot** [comment]
Might help to push what you have so far to your personal GitHub repo. That's also required for new applications, to be fair.

**Comment by klonos** [comment]
...still polishing a few things. Need to get some rest. Will do that ASAP.

**Comment by klonos** [comment]
@docwilmot are you going to have some time for mentoring? I have a few questions, but not right now. It's gonna be a bit of a pain due to timezone difference. I understand.

**Comment by klonos** [comment]
...couldn't get any sleep, so I pushed what I have so far. Basically, just CMI conversion done and removed `hook_help`. Should be good for initial review.

**Comment by jenlampton** [comment]
@klonos yes of course you have permission to port modules!!! :)  I've done a cursory code review and so far your port of fixteaserlinks looks great!  I have two suggestions you can take or leave as you please:

* since we are porting from variables to config (with an update hook) now is a good time to change the names of the variables from `fixteaserlinks_comment` to `comment` and from `fixteaserlinks_readmore` to `readmore`.  The module-name prefix was necessary in D7 because all the variables were stored in the same db. In Backdrop it's not necessary, and is a super-minor DX improvement (simply because there's less typing).

* I'd also recommend adding a settings page for this module. The target audience for backdrop is going to be more likely to want a UI for these settings than the Drupal audience. (I'd be more than willing to provide a PR for this change once the module is in the contrib space if you are willing to test it and review my PR!)

edit: I just read the README.md and see plans for this are in the works! good job :)

**Comment by klonos** [comment]
Thanx @jenlampton 👍 ...I transferred the repo to backdrop-contrib and will make a release soon.

> ...I'd also recommend adding a settings page for this module. ...edit: I just read the README.md and see plans for a UI are in the works!

...way ahead of you mate 😉 ...it's just that my php-fu is a joke and it'll take me some time.

I saw that the configuration in the Drupal version was only done via drush and realized that a) drush doesn't still work 100% for Backdrop (although I'm seeing some serious activity by the amazing @Gormartsen in gitter) and b) even if drush did work for us, having a module only be configurable via drush (the dev, geeky way) is simply against our philosophy. So, putting sensible defaults is a good thing, but we should allow users to easily change them *via the UI*.

About the update hook, there's a couple of questions I have:

- the 1000 update, I get it ...it is needed for the D7 to Backdrop migration in order to convert the variables to config and once that's done, delete the variables from the db. Right?
- the 7000 update, ...hmm, not sure. The module did not have any 7xxx updates in D7, but from our dev docs I could not understand clearly if it is needed or not. ??

...didn't know about the prefixes in the variables, but it makes perfect sense the way you explain it. Done! 😉

**Comment by jenlampton** [comment]
> the 1000 update, I get it ...it is needed for the D7 to Backdrop migration in order to convert the variables to config and once that's done, delete the variables from the db. Right?

You got it! 

> the 7000 last_removed update, ...hmm, not sure. The module did not have any 7xxx updates in D7, but from our dev docs I could not understand clearly if it is needed or not. ??

If the module didn't have any updates in 7.x then that is not neecessary.  I don't know if it's still recommended or not (@quicksketch?)
If the module did have updates in 7.x, that number would have told Backdrop "When upgrading from D7 to BD, run all D7 updates UP TO THIS NUMBER before switching to the 1000+n updates." It's so we get the order of updates correct since 1000 is less than 7000. :)

**Comment by klonos** [comment]
Thank you for taking the time to reply @jenlampton 

I've filed a separate issue for the 7000 update, so lets close this application issue 😉

**Comment by klonos** [comment]
Thanx everybody for the advice, reviewing and pointers.
