### ISSUE TITLE
First contrib module (port of StickyNav)

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/contrib#165]
https://github.com/CEDC/stickynav

**Comment by klonos** [comment]
Hello there @laryn and welcome to the Backdrop CMS contrib queue. Thank you for porting the module over. Here's a checklist of the minimum requirements for a project to be accepted:

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

...I see that your repo meets all the above criteria with the exception of the README that needs a bit of work. Before we are good to go, you need to make sure that it includes license and maintainer information (you can use the example file in the link above as reference). It's basically just the "License" section that you need to add at the bottom of the file + make sure that current maintainers and credits are clear in separate sections. Also would be nice if the references to people were actual links that people can click and follow instead of just mentioning Drupal/GitHub handles.

**Comment by klonos** [comment]
...please let me know once you have updated the README so I can proceed with officially adding you to the group.

**Comment by laryn** [comment]
@klonos Okay, I revised the README.

**Comment by klonos** [comment]
Perfect! ...all boxes checked, so last thing is to have you officially agree to the following terms:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

**Comment by laryn** [comment]
Agreed! (Although I confess surprise that the system requires opening up push permissions on all contrib projects).

**Comment by klonos** [comment]
@laryn welcome to the the Backdrop Contrib Group! ...invite is on the way.

You can now transfer your repo to the backdrop-contrib (instructions [here](https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2)). That way, new releases will be shown on the official backdropcms.org website and the Project Installer as well as available updates.

The issue with the "shared" access is known and by-design the way the repository was initially set up. We are working on it: #150

**Comment by quicksketch** [comment]
Welcome @laryn! We're excited to have you in the Backdrop community! :smile:

Thanks @klonos for reviewing and giving access. :+1:

**Comment by klonos** [comment]
@quicksketch anything that I can do to buy you more time 😉 Thank you for starting Backdrop!

@laryn unless you have any access issues or any questions, feel free to close this issue. See you in the queues.

**Comment by laryn** [comment]
Thank you @klonos and @quicksketch !
Love the philosophy of supporting lower budget nonprofits as that is what I do, so am very interested in seeing where Backdrop goes.
