### ISSUE TITLE
Contribution Policies and Procedures need some care

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-ops/contrib#169]
Moved from on https://github.com/backdrop-ops/backdropcms.org/issues/277

Original post: @kkomelin

Hi there, 

I'd like to ask if you have any procedure for accepting PRs for contrib projects. I mean some reasonable "time to process". I'd like to know how much time the maintainers need to consider my simple PR backdrop-contrib/socialfield#14 
If you do not have any formal rules regarding that, maybe it is time to create them.

P.S. You may port hundreds of projects relatively quickly but their support is much more expensive process.

Thanks.

---

PR from @jenlampton to restore original intent https://github.com/backdrop-ops/contrib/pull/187

**Comment by Gormartsen** [comment]
This topic mean to be discussed and some solution is required to be found from my point of view.

Some contrib supervisor group or  maybe even completely different approach to contribution compare to Drupal policy.

There is my Issue with PR that is sitting for 1 month as well:
https://github.com/backdrop-contrib/radix_layouts/issues/9

I did a quick PR search in contrib projects and found another one-month-old PR:
https://github.com/backdrop-contrib/filefield_sources/pull/5

**Comment by Gormartsen** [comment]
Useful link from @serundeputy 
https://github.com/backdrop-ops/contrib/blob/master/README.md

>  If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by Gormartsen** [comment]
Maybe we need to make public visible "Backdrop Contrib administrator" and some issue queue to handle this type of requests?

**Comment by Gormartsen** [comment]
this one is related to topic as well:

>#Abandoned Projects

>You may apply to adopt an abandoned project. The procedure is as follows:

>If you haven't already, please join the Backdrop Contrib group by submitting an application (see above).

> File an issue with the current project requesting to help maintain the project.

> If written permission is granted by a current maintainer, create a PR that adds your name to the README.md file in the list of maintainers.
If a current maintainer does not respond within 2 weeks create an issue in this repository to take over the project. Please include a link to the issue you filed with the abandoned project.
After confirming the project has been abandoned, a Backdrop Contrib administrator will add your name to the list of maintainers in that project's README.md file.

> You may now maintain the project directly as though given permission by the project maintainers, and likewise now grant permission to others to maintain the project.

**Comment by Gormartsen** [comment]
+ extra idea. We can track open issues and PR to contrib and if there is no answer to issue or PR for 2 weeks, open issue to "Backdrop Contrib group issue queue"

**Comment by serundeputy** [comment]
seems right to me @gormartsen ; i think @klonos is the admin of contrib

**Comment by klonos** [comment]
I would not call myself admin of contrib ...I'm more like a general-purpose, jack-of-all-trades janitor 😄 . At least I hope I'm not alone in this. We have an issue open for forming a team of "Contrib Curators": https://github.com/backdrop-ops/backdropcms.org/issues/233 ...applications welcome.

It is true that we have very few hands on deck, but I feel that we are all doing our best and contributing *a lot* of time. It will never be possible to keep on top of everything. Open source is best-effort after all.

Another thing that we need to keep in mind is that we need to be careful not to be stepping on anybody's toes. I have previously asked how people generally feel about the idea of having some people (the Contrib Curators, including myself) be allowed to merge minor changes like typos etc, but was told that the issue queue and PRs is the right way to go. Then, all I can do is wait for the project maintainer to find the time to do the review.

**Comment by serundeputy** [comment]
I believe it is all spelled out here quite clearly: https://github.com/backdrop-ops/contrib/blob/master/README.md

~Geoff

**Comment by klonos** [comment]
Yep, the 2 weeks deadline for response by the project maintainer that's mentioned in the "Abandoned projects" section seems relatively reasonable, but you see it is a bit harsh to deem a project abandoned when the maintainer simply has no time. Also there are some people that although they want to make a random, one-time contribution, they might not be ready to commit full-time and take over the project maintenance.

**Comment by jenlampton** [comment]
I have mixed feelings about this. There's a big difference between an abandoned project and one with some patches in the queue. I don't think there should be any expectation about how long a maintainer has to do someone else's work for them. Maintainers do a lot of great work for people already, for free, and their time needs to be respected.

There's no reason people can't run patched versions of modules for their own personal use, I've got patched versions of Drupal modules (and core!) where my patches have sat, neglected, in the queue for YEARS. It's never been an issue.

From the perspective of a busy maintainer, it is a LOT easier to let all the issues pile up, and then run through them all at once, then make a new release. If there aren't very many issues - it could be a very long time between releases, and that's actually a good thing. Less busy work for the people who need to update those modules - especially if the module is stable.

**Comment by serundeputy** [comment]
Maybe we should change the window in https://github.com/backdrop-ops/contrib/blob/master/README.md from 2 weeks to N-weeks?

Maybe 6 weeks?  Clarify that we just need a response like: 

  * Yes, I will try to replicate that problem, but it will be a few weeks as I'm on a deadline.
  * I need more info I can not replicate this problem can you provide the steps you took to arrive at this issue?

And not necessarily a merge or immediate solt'n, but a response with some expectations, showing path forward and plan.

I definitely at times feel the pinch of `busy maintainer` and I don't want to lose people/devs.

**Comment by jenlampton** [comment]
@serundeputy your recommended responses don't make any sense for abandoned projects. What N-weeks are you talking about?

I still think we should avoid adding any time commitment for maintainers into this agreement, I think it's fine as-is.

**Comment by serundeputy** [comment]
it already has a time requirement: https://github.com/backdrop-ops/contrib/blob/master/README.md

>If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

maybe we should take it out.

**Comment by jenlampton** [comment]
Ah! I see the problem. The issue that needs to be responded to in 2 weeks or less is not a general issue like "I want a new feature" but the "is this project abandoned?" issue. Maybe we should reword to make that more clear.  The reason for the time-limit on that kind of issue is so that the project can be handed over to a different maintainer when necessary.

**Comment by jenlampton** [comment]
I don't remember the original intent anymore. Let's ask @quicksketch, I think he wrote the original readme.

**Comment by kkomelin** [comment]
@jenlampton 
> I don't think there should be any expectation about how long a maintainer has to do someone else's work for them. 

Then there should not be any expectation about how much time an issue/PR author needs to answer questions of the maintainer. Every man for himself. 

> a maintainer has to do someone else's work for them

Don't you think that the work of maintainer is to maintain her project and not just port from Drupal? If you're not sure that you have time to maintain it, just don't port it.
"You become responsible, forever, for what you have tamed." - Antoine de Saint-Exupéry

**Comment by jenlampton** [comment]
> Then there should not be any expectation about how much time an issue/PR author needs to answer questions of the maintainer. Every man for himself.

I have no problem with that either.

> Don't you think that the work of maintainer is to maintain her project

No, I don't. The work of a maintainer could be to build rockets, teach schoolchildren, or like some of us, build websites for other people. Being a maintainer means that these people are also volunteering to manage that project over time.

> If you're not sure that you have time to maintain it, just don't port it.

Seriously?  I need these ports for the work I do on a daily basis, and so do lots of other people. I'm going to do the work I need to do for a client, and then give it away for free, also. Sharing and working together is how open source works.

**Comment by kkomelin** [comment]
@jenlampton Then the word "maintainer" is not suitable in this context.

**Comment by jenlampton** [comment]
Okay, then what should we call someone who's committed to manage contrib projects over time?

**Comment by kkomelin** [comment]
The context was:
> Don't you think that the work of a maintainer is to maintain her project and not just port from Drupal? 

I wish I used "responsibility" instead of "work". The responsibility doesn't always imply direct material compensation for the work.

Anyway, If a person port a project from one system to another and create a new project on Github, she can be considered as maintainer by default but if the issues of the project are not answered for months I can hardly call the person maintainer because in fact she doesn't maintain.

**Comment by jenlampton** [comment]
I see where you are coming from, but the problem with applying dry logic is that lacks compassion. We are a community of hard-working, generous people (for the most part) and you need to understand that just because someone is not answering questions as fast as you like, doesn't mean that they never will, or that they don't care about the project, or that it isn't being maintained. 

Yes, it can be frustrating to manage contrib projects that are patched, but there are [plenty of good solutions](http://www.jenlampton.com/blog/sustainable-development-workflow-patching) out there. It's just another part of Open Source software development.

> I wish I used "responsibility" instead of "work".

I would say the only "responsibility" of maintainers is to keep people safe. That means `You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary` (quoted from the readme). All the other things we ask of maintainers is just that - a request.

**Comment by kkomelin** [comment]
@jenlampton 
I have maintained OS projects for years. I know how hard it could be. That's why I though twice and tried to answer the following questions before creating one more project: Would I cope with all the requests? would I have time and will to answer sometimes obvious, sometimes incorrect questions? etc. That helped me to keep the number of projects I maintained reasonable and I did maintain them in a timely manner.

> I would say the only "responsibility" of maintainers is to keep people safe. That means You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary (quoted from the readme). All the other things we ask of maintainers is just that - a request.

Your quote is about Backdrop Security Team but I believe there could be other people also porting and maintaining Backdrop extensions, so if you don't build proper contribution and maintainership policies and recommendations, you will soon have 20K abandoned extensions as some other well-known projects have. People should feel responsibility for what they opensource, form my subjective opinion. 

To sum up, I might be totally wrong here and I might misunderstand opensource completely but I like to think this way and I believe users of projects which I created valued it. Anyway, it's good to know Backdrop Core Team point of view even if it's different.

**Comment by Gormartsen** [comment]
Hi @jenlampton 

I completely on the same page with you about compassion and friendly environment for contrib developers.

I don't want to add any kind of extra stress to it.

At the same time, I have nice example when extra action from "the admin group" would be nice to have:

https://github.com/backdrop-contrib/radix_layouts/pull/10

This kinda PR I would name "typo, style fixes".

As a contrib developer, I would appreciate if somebody from  "the admin group"  would accept similar PR to my projects as well, while I am away for personal reasons.

PS: Russian people sometimes harsh, but mostly honest. :)

**Comment by kkomelin** [comment]
@Gormartsen 
> I completely on the same page with you about compassion
Don't forget that your users also need compassion and understanding. If I didn't maintain a number of projects, didn't see user frustration when their questions were not answered for months and didn't see them gone, I would not probably raise the topic.

> PS: Russian people sometimes harsh, but mostly honest. :)
Yes, @jenlampton, sorry if I was too direct in expressing my personal opinion.

**Comment by klonos** [comment]
Being one such person that simply does not have time in their lives, I'd say that I am in favor of not setting specific time thresholds/deadlines that project porters/maintainers should adhere to. The difference with projects on GitHub vs projects on D.org is that backdrop/contrib authors have commit access to ALL projects. So, *theoretically*, we can take advantage of this fact (I see it as a feature in the context of this issue here) and get some people together to form a team of contrib committers (respective to the team of core committers). These people could have a unanimous approval to accept and merge PRs that have been RTBC'ed and where they deem that the changes made are either too trivial to require the project maintainer's attention/action (typo fixes for example) or are simply not API-breaking and/or are not changing the project greatly in ways that would confuse users/developers. If we had that as part of the Contrib Author Agreement, then all project maintainers would know what they are getting into and it will not be a surprised if they saw some (minor) commits made to their project. We can have a list of the Contrib Committers available and I offer to be one (but only for minor corrective commits like typo fixes),

**Comment by jenlampton** [comment]
>  People should feel responsible for what they opensource, from my subjective opinion.

I do feel responsible for what I opensource @kkomelin. But as I mentioned above, I feel my only "responsibility" is to keep people safe. Answering questions and reviewing feature requests is not my "responsibility" - those are things I do because I'm asked, and because I like to do them. I do them when I have time, and when I don't, I ask for help. (All my modules state they are seeking additional maintainers).

> if you don't build proper contribution and maintainership policies and recommendations, you will soon have 20K abandoned extensions as some other well-known projects have.  

Yes, and that's why we have a process for dealing with abandoned projects stated clearly in the REAME. And why we are working on this issue - so that we can set the right expectations from the onset. We have a lot of experience with open source, too. 

I'm usually trying to do what's best for the community. Right now, I believe it's best for the community for me to be working on ports of modules like metatag and xmlsitemap, and not reviewing your feature request to add rel="nofollow" links to socialfield. That does not mean the socialfield module is abandoned. 

It may, in fact, make me a bad maintainer to act in the best interest of the community like this, but I'm okay with that. I also hear that you don't contribute as much as you could, because you think it's more important to respond to people in a timely manner, and I think that difference of opinion is okay. There are lots of different people in open source communities and I believe everyone should be welcome to manage their own projects as they wish. I think it's important that these freedoms remain, and our standard policies shouldn't exclude anyone from participating.

> backdrop/contrib authors have commit access to ALL projects

I don't think this is technically the case anymore @klonos, though it was when we started the contrib-group, and remains true for some people today. I do like this idea though, we could set up some sort of a bug-squad of people empowered to handle small but crucial changes, who understand what lines are not to be crossed. 👍

**Comment by docwilmot** [comment]
Three reasons when combined make me feel we should have a time limit policy:

One is that some of our projects may have been ported by persons (like myself) who aren't exactly experts at this, plus very few people are available to test/try/suggest, and so we are more likely to have issues.

Second is that our "customers" have limited options, so if a project doesn't work, unlike Drupal, Wordpress, they cant just try another.

Third is that Backdrop is in the early stages and requires "customer satisfaction" to encourage uptake of the project.

So we require a method of ensuring that simple fixes which may render the only option unusable can be relatively rapidly applied. Having a simple fix waiting in a queue indefinitely is more likely to be harmful to Backdrop than elsewhere. 

But the good things with being small, is that we may not be as hierarchical as the other projects. I would suggest a policy that if one of us notes that a "simple fix" has waited N weeks (I say 4-6) that we declare it "blocked" or "delayed" or "sad" or "lonely" or whatever the heck you wish to call it if "abandoned" doesnt fit, and allow somebody to merge it to fix the problem so that Backdrop CMS isn't harmed and people can move on with using it.

We are not Drupal. We have to think differently and make the decisions that are best for the project.

**Comment by klonos** [comment]
> We are not Drupal. We have to think differently and make the decisions that are best for the project.

👍

**Comment by kkomelin** [comment]
Hi @jenlampton,

> and not reviewing your feature request to add rel="nofollow" links to socialfield

I talked in general and did not refer to anybody in particular, so please don't take it personally.

> We have a lot of experience with open source, too.

I have no doubts about that.

> I also hear that you don't contribute as much as you could, because you think it's more important to respond to people in a timely manner,

You may contribute with code, by answering users' requests, organizing conferences and writing promo articles. Whatever you do in favor of a project is contribution. So, I do contribute to opensource projects but I'm trying to avoid opensourcing code which I don't have time to maintain. I wouldn't like to judge whose approach is better I just thought my suggestion can improve something (see the issue description).

In conclusion, Jen, thank you for answering my comments. Please don't take them too personally. If I used "she" I didn't mean you in particular, it was just a standard polite way of referring to an undefined person.

**Comment by jenlampton** [comment]
I think having a bug-squad would solve all the problems you mention @docwilmot.

> Second is that our "customers" have limited options, so if a project doesn't work, unlike Drupal, Wordpress, they cant just try another.

Discouraging new contributors (and discouraging current contributors from working on more projects) is only going to make this problem worse, not better. I fear that's what a time-limit would do, making unrealistic expectations of contributors time.

Can we start with a bug-squad and see how that goes for a while?

**Comment by kkomelin** [comment]
@docwilmot
> We are not Drupal. We have to think differently and make the decisions that are best for the project.

I like that. Maybe that's why I asked my initial question (in the issue description) on Gitter.

**Comment by docwilmot** [comment]
> I fear that's what a time-limit would do, making unrealistic expectations of contributors time

Its all in the wording though. Lets not call it a "time limit", lets not call it "abandoned", lets not make it sound punitive, lets just agree that if you're busy and there's a simple fix waiting, we will remind you kindly and if you are still preoccupied we will help you out by committing it for you and keeping you informed.

> Can we start with a bug-squad and see how that goes for a while

I think we'd all be happier with that, really. Are you going to draft that as a policy?

**Comment by Gormartsen** [comment]
> @jenlampton : Can we start with a bug-squad and see how that goes for a while?

I love it!

**Comment by jenlampton** [comment]
> Its all in the wording though. Lets not call it a "time limit", lets not call it "abandoned", lets not make it sound punitive, lets just agree that if you're busy and there's a simple fix waiting, we will remind you kindly and if you are still preoccupied we will help you out by committing it for you and keeping you informed.

But, that's what the bug squad would do...

**Comment by klonos** [comment]
> If I used "she" I didn't mean you in particular, it was just a standard polite way of referring to an undefined person.

The proper way to be "undefined" is to use "they" and "them", even when referring to a single person. For example, instead of this:

"When the user clicks on xyz, he/she gets taken to the admin UI"

...it is grammatically correct to say:

"When the user clicks on xyz, **they** get taken to the admin UI"

**Comment by kkomelin** [comment]
Thanks @klonos for correcting me. I will fix my comments accordingly.

**Comment by docwilmot** [comment]
> But, that's what the bug squad would do, no? I was thinking the bug-squad remove the need for any kind of time-limit.

I think you'd need to define the scope of operations for the bug squad; I'm not quite sure what it would entail. 

But if the bug squad had authority to merge bug fixes and I just pushed my shiny new module I wouldnt want the squad swooping in and merging 'fixes' while I'm still working things out on my local. Gimme a few days maybe? That kind of time limit.

**Comment by Gormartsen** [comment]
I think that bug-squad is applicable if maintainer is out of reach.

I mean that issue and/or pr has no answer , no comments or any kind activity happen on repo.
Then bug-squash can act.

I believe any bug-squash member should post comment first:

Maintainer, how is it going? Is it ok for you if we merge this on your behalf?


And if there is no answer N days, then act.

Regards,
Gor Martsen
@gormartsen

**Comment by Gormartsen** [comment]
So basically all big-squash action start with respect to maintainer.
Next priority after that is security and stability of project.

Features request is not a part of bug-squash team.

**Comment by klonos** [comment]
>I believe any bug-squash member should post comment first: Maintainer, how is it going? Is it ok for you if we merge this on your behalf?

> Features request is not a part of bug-squash team.

My thoughts exactly.

**Comment by jenlampton** [comment]
How about something like this? https://github.com/backdrop-ops/contrib/pull/184/files

**Comment by docwilmot** [comment]
We should add a note about the Bug squad process as well, like a member of the squad will ping you in the issue queue at least once to advise you that the merge will be done within the next x days.

**Comment by jenlampton** [comment]
I'm a little bit worried about defining too precisely what the process will be until we've actually tried the process :) How about we just start with "they are empowered to do things" and once they figure out what they are doing, we can write it down?

**Comment by jenlampton** [comment]
I've created another issue so we don't forget after this issue is closed (and if we decide to add it now we can close that issue now too). It's important to be as clear and upfront as possible, but I think adding too many specifics without trying them out first might hinder us. We're already adding the whole bug-squad bit without an existing bug-squad.

**Comment by Gormartsen** [comment]
I can do pr review from security perspective if necessary.

**Comment by jenlampton** [comment]
> I can do pr review from security perspective if necessary.

That would be great!  We should get you added to the official security team :)

**Comment by quicksketch** [comment]
Sorry I haven't been able to weigh in here yet. Could we start with just fixing the abandoned projects clarification as posted in the PR at #184, and save the bug squad concept and details for the new issue @jenlampton created at #185?

**Comment by jenlampton** [comment]
Here's a pull request that restores the language for the Abandoned project to what I thought the original intent was:
```
If your project becomes abandoned and you do not respond to an issue to grant
a new maintainer within 2 weeks, your project may be modified by a Backdrop
Contrib Administrator without your explicit consent, to add a new maintainer.
```

**Comment by klonos** [comment]
Looks good. Two nits/questions:

1. "If your project becomes abandoned...": Do we define what makes a project abandoned?
2. "...your project may be modified by a Backdrop Contrib Administrator without your explicit consent, to add a new maintainer.": English is not my main language, but I've never seen this before. I'd expect this instead: "...your project may be modified by a Backdrop Contrib Administrator to add a new maintainer, without your explicit consent." Are both grammatically correct?

**Comment by jenlampton** [comment]
> Are both grammatically correct?

There are two clauses:`'without your explicit consent` and `to add a new maintainer` I don't think the order is important. Whatever you guys prefer is fine with me :)

**Comment by quicksketch** [comment]
Thanks everyone. I've merged https://github.com/backdrop-ops/contrib/pull/187 that simply clarifies this one sentence. Please feel free to make further grammatical fixes as PRs if we come up with better language. Let's continue the bug-squad concept issue over in #185.
