### ISSUE TITLE
Requesting access to contrib

### ISSUE THREAD

**Issue by les-lim** [backdrop-ops/contrib#196]
Hello! I'm Les Lim (https://www.drupal.org/u/les-lim), and I'm the creator of Object Log module (https://www.drupal.org/project/object_log) and a co-maintainer for Mailsystem module (https://www.drupal.org/project/mailsystem) in Drupal 7. I have a working port of Object Log ready to go for Backdrop, and I'd like access to backdrop-ops/contrib to create a project for it there.  

I'm also interesting in porting the 7.x-3.x branch of Mailsystem to Backdrop - there's an existing port for the 7.x-2.x branch, but the 2.x branch is a fragile version that works by creating a generated PHP file in the public files directory.

**Comment by serundeputy** [comment]
Hi @les-lim that sounds great!

Here is the new project check list: https://github.com/backdrop-ops/contrib/blob/master/README.md

To get you started.  I think @klonos will probably be in touch with you shortly to help you dot the I's and cross the T's.

It will be great to have you aboard along with these wonderful modules!
~Geoff

**Comment by klonos** [comment]
Hello @les-lim and welcome to the Backdrop contrib queue. Sorry for the late reply.

Mail System seems to have already been ported to Backdrop (from the 7.x-2.x branch as you said). The usual process of porting a module includes letting the original module maintainers know of our intention by filing an issue in the d.org issue queue, but this time this was not done for some reason. Anyways, out of courtesy  we always offer the original authors co-maintainership at any point in the future should they change their mind (even if they had originally said that they are not interested in a Backdrop port). I am sure that @Graham-72 and @biolithic will be glad to get any help they can, especially from one of the original authors.

To the point... the usual process of granting somebody access to the contrib repo involves them creating a GitHub repo with the ported module code and doing a review of that. Since Mail System is already ported, we cannot start with that, so how about you create a repo with the port of one of the other modules you (co)maintain such as Object Log? Once you have done so, please post a link to it and we'll do the review (which usually takes a day or two). After you have been granted access to the Backdrop contrib repo, you will be able to transfer your module(s) and they will be made available on backdropcms.org and in the Project Browser. You will also be able to become co-maintainer of the Backdrop port of Mail System and create a new branch for the 3.x version. Does that sound like a plan?

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
Hello @les-lim 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
