### ISSUE TITLE
Alternate hreflang form D7 to Backdrop

### ISSUE THREAD

**Issue by fazni** [backdrop-ops/contrib#201]
Search engines use `<link rel="alternate" hreflang="x" />` tags to serve the correct language or regional URL in search results.

More info about hreflang can be found at the article [Use hreflang for language and regional URLs](https://support.google.com/webmasters/answer/189077).

**Comment by klonos** [comment]
Hello @fazni. Is this a request for someone to do the porting or are you in the process of doing it yourself?

**Comment by fazni** [comment]
Hi @klonos I did locally but I would like to publish it on the backdrop-contrib repository

**Comment by klonos** [comment]
I certainly can @fazni. Before granting you access to the contrib repo, there are certain requirements that need to be met for any new application and there are certain things that need to be done:

1. Open an issue in the backdrop/contrib issue queue letting everybody know that you have started working on the port. This is done in order to avoid duplication of efforts. You have already done this by opening this issue here, so 👍 
1. The maintainers of the original project need to be notified of the intention to do the port and asked if they intent to do that themselves. They should also be offered to join as co-maintainers in the future should they change their mind. You can do this by opening an issue in the d.org queue. Once the issue in d.org has been opened, please update the issue here with a link to it. There are [some example issues that have been previously opened](https://www.drupal.org/project/issues/search?issue_tags_op=%3D&issue_tags=Backdrop%2C+backdrop-port%2C+Backdrop+compatibility) for other projects that you can use as a reference.

While waiting for a reply from the original module maintainers, you can start working on the port. Here's the checklist of things that we ask from new ports:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Once you have done these and are ready for an initial review, let us know by updating this issue here. Let me know if you need help with anything else in the meantime.

**Comment by fazni** [comment]
Thank you for your answer @klonos , yes I spoke with maintainer  I think it agrees., link issue https://www.drupal.org/node/2853541. 
I added the requirements, what is the next step ?

**Comment by klonos** [comment]
For the record, @fazni's initial port is at https://github.com/fazni/hreflang

@fazni the original module maintainers have been notified, you have added the LICENSE.txt file, and the Git history from d.org seems to be there. The only minor thing is to rename the README.txt to README.md and ideally convert it to markdown format.

**Comment by fazni** [comment]
@klonos, it's OK I'm ready for the next step https://github.com/fazni/hreflang ;)

**Comment by klonos** [comment]
@fazni looking good, just minor details:

- The "ALTERNATE HREFLANG" section is repeated twice in the README. Accidental copy/(double-)paste?
- In the same section there is this text at the last paragraph:
  >To file a bug report, feature request or support request for this module, please visit the module project page: https://www.drupal.org/project/hreflang

  Can you please change that link to https://github.com/backdrop-contrib/hreflang/issues or remove the entire paragraph (since you have a separate, dedicated "Issues" section with the correct URL)?
- The "Current Maintainers" section still lists the d.org original maintainer. You should change that to yourself.

Once these points have been addressed, and to avoid wasting time, can I please have you agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to an issue to grant
   a new maintainer within 2 weeks, your project may be modified by a Backdrop
   Contrib Administrator to add a new maintainer, without your explicit consent.

**Comment by fazni** [comment]
@klonos, I read the agreement, it is noted  ;)  for information I deleted section **for additional documentation** because I have a basic documentation in top Readme.md :+1:

**Comment by fazni** [comment]
Hi @klonos, I'm still waiting for your answer ;) or if someone else can help me to push the module https://github.com/fazni/hreflang you tag it here

**Comment by jenlampton** [comment]
Hi @fazni and welcome to Backdrop! For clarification, do you agree to the Backdrop Contributed Project Agreement?  We'll need a simple yes or no.  Once we can confirm that you have agreed, you will be granted access to push the module into the contrib group.

**Comment by klonos** [comment]
Hi @fazni, sorry for the delay. Before you are granted access to backdrop-contrib, can you please explicitly state that you accept the terms of the Backdrop Contributed Project Agreement above?

**Comment by klonos** [comment]
...what @jenlampton said 😄 ...had the tab open and did not refresh.

**Comment by fazni** [comment]
**I do accept the backdrop contrib project agreement.**

**Comment by klonos** [comment]
Thanx @fazni ...invite is underway 👍 

> You've invited fazni to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Officially welcome to the Backdrop Contrib Group 😄 ...feel free to move your repo to backdrop-contrib and tag a release once you are ready 😉

**Comment by fazni** [comment]
It's OK I accepted the invitation it's great Thank you  @klonos  :).
I have another question ;), but it is embarrassing;). `I'm afraid of doing stupid things ;)`
In fact I do not usually use github, how can I do?
I do the import through the interface  https://github.com/new/import ?
Thank you

**Comment by fazni** [comment]
@klonos,
tag a release https://github.com/backdrop-contrib/hreflang/releases

**Comment by klonos** [comment]
Hello @fazni and once again sorry for the late response. No need to stress or feel embarrassed.

In order to move your port repository to backdrop-contrib, from the GitHub web UI:

- navigate to your repository settings: https://github.com/fazni/hreflang/settings
- scroll down to the "Danger Zone" section.
- click the "Transfer" button in the "Transfer ownership" subsection.

...in the pop-up that appears:

- enter your repository name (`hreflang`) in the first field.
- enter `backdrop-contrib` in the second field.
- hit the "I understand, transfer this repository" button.

**Comment by klonos** [comment]
...let me know if that worked OK for you 😉

**Comment by fazni** [comment]
Hi @klonos, Yes everything is OK ;)  https://backdropcms.org/project/hreflang Thank you.

**Comment by klonos** [comment]
Perfect! 👍 ...glad to have you onboard @fazni
