### ISSUE TITLE
Add YesCT

### ISSUE THREAD

**Issue by YesCT** [backdrop-ops/contrib#202]
Looking at https://api.backdropcms.org/contrib-application-process

I agree to the Backdrop Contributed Project Agreement

**Comment by serundeputy** [comment]
https://github.com/YesCT/audiofield

**Comment by klonos** [comment]
> I agree to the Backdrop Contributed Project Agreement

Hold your horse there @YesCT 😄 😛 ...

For the record, here's what we require from new project ports in order to grant the porter(s) access to move them to backdrop-contrib:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

You've already [notified the original module maintainers](https://www.drupal.org/node/2854212) and ticked off 2 of the 3 items in the list. The only minor thing remaining is to rename the README.txt to README.md and ideally re-format it to markdown. you need to also mention and link the licence to it and add your name as the maintainer of the Backdrop port, leaving in place the name(s) of the Drupal module maintainers as credit.

That's it! Let me know once you're ready 😉

**Comment by klonos** [comment]
...did I mention how exciting it is to be seeing familiar names from d.org show up here 🎉  👏

**Comment by YesCT** [comment]
:) Yep working on the readme.md now. Checking back on this to see if I could move parts to the wiki as I trim down the readme.txt for that.

**Comment by klonos** [comment]
README has been renamed and modified per suggestions 👍  Now, @YesCT you have already pre-agreed to the following. FTR and for posterity, I am appending it here:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to an issue to grant
   a new maintainer within 2 weeks, your project may be modified by a Backdrop
   Contrib Administrator to add a new maintainer, without your explicit consent.

**Comment by klonos** [comment]
...invite for joining the backdrop-contrib group underway. Let me know if everything is OK 😉 

>You've invited Cathy Theys to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by klonos** [comment]
...once you have accepted the invite, you can transfer your repo to backdrop-contrib and tag a release so the module shows up in https://backdropcms.org/modules and in the Project Installer in the admin UI of the Backdrop CMS.

**Comment by YesCT** [comment]
Great! Trying to do that now.

**Comment by klonos** [comment]
Tis done 👍 😄
