### ISSUE TITLE
E-commerce solution

### ISSUE THREAD

**Issue by ivanklut** [backdrop-ops/contrib#215]
Hello!

Itinity - is ecommerce CMS based on Drupal 7. We are looking for an opportuniny to integrate our solution into Backdrop. Our goal is to deliver our work to the broad community and develop better experience for users.

How many users could be intesting in Backdrop ecommerce solution based on Itinity?

Currently Itinity is capable with Drupal 7, should we adjust it to Backdrop CMS?

How many ecommerce projects could be created on Backdrop in 2017?

Do you have a people who could take part in code remastering?

The demo video is on the link below https://youtu.be/LSaGIowjX-o

Github code https://github.com/Itinityorg

**Comment by klonos** [comment]
Thank you for contacting us and for filing this issue here @ivanklut. I also see that you've created a demo video and placed all code that you have available on a GitHub repo 👍 

There have been some mentions lately about various ecommerce solutions on our Gitter channel. I'll shout a link to this issue here and have these people chime in.

This is exciting!

**Comment by stpaultim** [comment]
I'm going to close this issue. I recommend this forum discussion for anyone interested in this topic.
https://forum.backdropcms.org/forum/e-commerce-solutions-backdropcms
