### ISSUE TITLE
Porting Amount module

### ISSUE THREAD

**Issue by geru** [backdrop-ops/contrib#217]
I am porting the Amount module to Backdrop. [Link to issue](https://www.drupal.org/node/2874301).
Consider this issue my application to join the Backdrop Contrib group.

**Comment by klonos** [comment]
Hey @geru you might be interested in https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time 😉 

Welcome to the Backdrop contrib issue queues!

I have taken a quick look at the module description in d.org and although I understand the use of it, it would be useful if there was a list of reasons and/or use cases of why one would want to use that over say currency for example.

I have also given it a spin on simplytest.me and was wondering why in the field settings form, the multi-select for allowed unit types and the drop-down for the default value have these "cryptic" labels instead of "pretty", human-readable ones:

![image](https://cloud.githubusercontent.com/assets/2423362/25579158/985ab2e4-2eb8-11e7-99d6-5ae0d5f8afeb.png)

**Comment by geru** [comment]
Thank you for the message @klonos

I assume someone would have to add me to the group in order to add this
repository to backdrop-contrib, yes?

The purpose of the module is documented in the README file. Key elements
are: large range, high precision, computer-native format (no BCMATH
needed), and, importantly, it can be used with Mysql embedded semaphore
system to do fast, non-colliding updates.

   - One has to wonder why Drupal ships with a number module with three
   different number types, and then someone still found the need to make the
   Currency, Price, Fraction, and now Amount fields, and more... This one
   module eliminates the need for Integer, Decimal, Float, Fraction, Currency,
   and Price fields which all save data in dissimilar ways and all require
   extra intervention just to be able to manipulate mere numbers.
   - As for the cryptic codes, they are no different than the cryptic codes
   saved in the Currency module, only they go beyond currency to support
   arbitrary unit types such as quantities, temperature, pressure, length,
   etc. If you want pretty words, it is easy enough to make a taxonomy to map
   the codes to pretty words, but issue 2662 would need to be incorporated
   into Backdrop for that to work, or issue 1621356 on Drupal.org, and then,
   of course the taxonomy-pretty-word-mapping-module would need to be written.

Thanks for adding the link to @DavidRothstein article on dual Backdrop /
Drupal maintenance. The third one pushes my abilities with git, but I'll
try to have it figured out before I push to Backdrop, so I can maintain
both versions easily.

I look forward to getting this module uploaded into the Backdrop contrib
list if I get added to the contrib group.

**Comment by klonos** [comment]
>I assume someone would have to add me to the group in order to add this repository to backdrop-contrib, yes?

Correct. And I am one of the people that can help with that 😄. More on that in my next comment though.

>The purpose of the module is documented in the README file. Key elements are: large range, high precision, computer-native format (no BCMATH needed), and, importantly, it can be used with Mysql embedded semaphore system to do fast, non-colliding updates.

Yep, that info unfortunately does not make sense to the average Joe/Joette. Perhaps there can be a lame-term explanation or a use case example. Still a useful module for those that understand what it does.

**Comment by klonos** [comment]
In order for a project to be added to Backdrop contrib, we ask these requirements to be met:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

I assume that https://github.com/geru/amount is the repository that will be holding the code. Right? Since you are the original author/maintainer of the respective d.org project, there is no need to ask permission or notify anyone else that you are porting the module to Backdrop 👍 ...git history seems to be maintained from d.org 👍, so what's left is the addition of the LICENSE.txt file and either to rename the README.txt to .md or create a new README.md for backdrop. Once these two tasks have been done, let me know and we'll take it from there. Let me know if you need any help or further clarification 😄

**Comment by klonos** [comment]
Hello @geru 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
