### ISSUE TITLE
contrib developers group

### ISSUE THREAD

**Issue by chrisherberte** [backdrop-ops/contrib#22]
Hi. Theme https://github.com/chrisherberte/backdrop-theme-aeon5 has been ported and tested. You can see it here http://backdrop.dev.xweb.com.au/
Original and project here https://www.drupal.org/project/aeon5.

**Comment by chrisherberte** [comment]
Sorry, renamed GH repo https://github.com/chrisherberte/aeon5

**Comment by quicksketch** [comment]
Hi @chrisherberte! Excellent! Our requirements generally require:

- LICENSE.txt
- README.md (with list of maintainers)
- Maintain the history from Drupal 7.

However, since you are the original author from Drupal 7, I'll leave it to you if you would like to keep the Git history from Drupal 7. Normally what I do is do a Git checkout from the D7 branch, rename it to `1.x-1.x`, then push that to Github. Then copy your port over the top and commit that.

Anyway, that's not needed in this case, but we do need you to agree to the contrib agreement. So if you would confirm, we'll send you an invite to the group. :)

---


Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the Backdrop project
  1. A list of the past maintainers for the Backdrop or Drupal project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by chrisherberte** [comment]
Thanks Nate. Yes I agree to the above Backdrop Contributed Project Author Agreement.
Cheers, Chris.

**Comment by quicksketch** [comment]
Great! Invite sent. We're so excited to have your help!
