### ISSUE TITLE
New module request: Control the animation of .gif images

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#223]
We very often use animated .gifs to showcase Backdrop new features in various release blog posts and documentation on b.org. The good thing with animated gifs is that they are smaller in size than videos. The bad thing is that some people find them annoying/distracting. There is no d.org contrib module available for this purpose, but there are a few js libraries out there that add play/pause functionality to animated gifs:

https://github.com/krasimir/gifffer
https://github.com/ctrl-freaks/freezeframe.js
http://rubentd.com/gifplayer

We could really use a contrib module that adds this functionality. A very minimal, first version can just be adding one of these libraries so that *all* gifs acquire play/pause controls. Further iterations of the module can make this be an option when uploading .gif files in image fields and in CKeditor.

**Comment by BWPanda** [comment]
In my opinion, the only one worth looking at using is freezeframe.js, as the other two require additional HTML markup. freezeframe.js seems to allow regular, simple markup and does its magic with that.

I'm looking at using this on a site so may be able to do this soon.

**Comment by BWPanda** [comment]
Here you go: https://github.com/backdrop-contrib/freezeframe

Seems to be working well for me, though I do want to add an overlay button, like this: https://github.com/ctrl-freaks/freezeframe.js/issues/27
Might try and work on something custom for the Backdrop module until that PR is committed to the freezeframe.js script.

**Comment by docwilmot** [comment]
@BWPanda the notation for which images to animate (`img[src$=".gif"]`) is a bit advanced (I dont know what it means TBH). So suggestion: 
- add a "Animate all gifs" checkbox on the settings page, which hides the textarea with states
- if the above is unchecked, then in the textarea allow simple class or id selectors, like `.my-class` or `#my-id`

Also, have you had any thoughts on how users get new classes on images? Would be nice if this module allowed users to add classes right into the image dialog, but I noted in https://github.com/backdrop/backdrop-issues/issues/1580#issuecomment-329004345 that it isn't obvious how to do so with the current API. Still waiting a response from @quicksketch but maybe you can figure it.

> I do want to add an overlay button

You could use the `gifplayer` library instead; its got all the features of Freezeframe it seems, including the overlay. Another issue with Frezeframe I just noted as well is that it doesnt work with transparent gifs. It adds an overlay over inactive gifs, with an opacity of 1, but chrome at least ignores that overlay opacity, so you end up seeing a static frame of the gif with the playing gif in the background. Gifplayer uses `display:none` instead of opacity, which works.

![recording](https://user-images.githubusercontent.com/1042283/31328947-8cbf1f70-accf-11e7-8ec4-1c92d1ded718.gif)

**Comment by BWPanda** [comment]
> ... add a "Animate all gifs" checkbox ...
Good idea, will do.

> ... have you had any thoughts on how users get new classes on images?
No, but I think that's out-of-scope for this module. That should either be a separate contrib module, or else added to core.

> You could use the gifplayer library instead...
I purposefully chose Freezeframe over Gifffer and GifPlayer as those other two require additional HTML markup to work (e.g. "Specify a ‘data-src’ attribute..." (from https://github.com/rubentd/gifplayer#gifplayer)). Freezeframe isn't perfect, but I'll see what I can do regarding the transparent issue...

**Comment by BWPanda** [comment]
@docwilmot I've just made two commits that address the 'All' checkbox request and the transparent GIF issue. They are, respectively:

https://github.com/backdrop-contrib/freezeframe/commit/e2f5fafa191eed09d2337c6ef0a26a77a897585f
https://github.com/backdrop-contrib/freezeframe/commit/a2c7f14feb915c6d11b939b39ddb27236fda9c4d

**Comment by BWPanda** [comment]
I've also made the pointer display as a cursor when hovering over GIFs (so you know to click on them (couldn't work out how to do the overlay thing after all)), and made GIFs responsive by default.

**Comment by docwilmot** [comment]
Tested and much better! Still few small issues:
- I get this JS error on every page load: `✨ freezeframe.js ✨ : no images found for selector img[src$=".gif"], img[src$=".GIF"]`
- When the GIF plays for the set duration, it fades out rather than just stopping. Not a big deal, but I didnt expect it and so it stood out to me.
- With the new 'all' checkbox, you shouldnt need the default text in the textarea. (Its a bit scary).

**Comment by BWPanda** [comment]
> I get this JS error on every page load...

I'll look into that.

> When the GIF plays for the set duration, it fades out rather than just stopping.

I believe that's part of the fix for the transparent GIF issue. See here: https://github.com/ctrl-freaks/freezeframe.js/pull/26

> ...you shouldnt need the default text in the textarea.

You may need to uninstall and re-install the module to see that I've removed that with the new 'All' checkbox. Probably that default was still saved in your active config directory from before the update where this was removed.

**Comment by BWPanda** [comment]
I just pushed a commit that fixes the JS error. Please test: https://github.com/backdrop-contrib/freezeframe/commit/567f41499348e4dd8ce64c16dd6f6052c57cc0c7

**Comment by docwilmot** [comment]
great, that fixes it.
could something like this work for an overlay?:
```
(function($) {

Backdrop.behaviors.freezeframe = {
  attach: function(context, settings) {

    var gifs = $(settings.freezeframe.gifs);
    if (gifs.length) {
      gifs.freezeframe({
        'animation_play_duration': Number(settings.freezeframe.duration),
        'non_touch_device_trigger_event': settings.freezeframe.trigger
      });
    }
    $(".ff-container").prepend("<div class='overlay'><img src='/core/misc/arrow-asc.png'></div>").each(function() {
      $(this).hover(function() {  \\ need to modify based on  settings.freezeframe.trigger
        $(this).children(".overlay").toggle();
      });
    });
  }
};

})(jQuery);
```
```
.ff-container .overlay {
  position:absolute;
  height:100px;
  width:100px;
  top:0;
  left:0;
  z-index:999;
}
```

**Comment by BWPanda** [comment]
Yes! Awesome, thanks!

Here's an initial commit inspired by your code: https://github.com/backdrop-contrib/freezeframe/commit/2f2105d311e41a3d5b06479c1b4c745c8eec745a
I had to change it around a bit to try and get it working when you start the animation (hiding the overlay) and then click the GIF again to stop the animation (showing the overlay again). Also to show the overlay after the duration of the animation.

It all works nicely (from what I can see), except that on a mobile/touch screen it doesn't work properly... Help appreciated! :wink: 

Once that's sorted, I can theme the overlay better (and maybe add an option to use your own image in the settings).

**Comment by BWPanda** [comment]
@klonos I think we can close this issue now in favour of using FreezeFrame's issue queue? https://github.com/backdrop-contrib/freezeframe/issues

**Comment by serundeputy** [comment]
closing.
