### ISSUE TITLE
Requesting maintainership for smsframework module

### ISSUE THREAD

**Issue by almaudoh** [backdrop-ops/contrib#228]
Hi, [SMS Framework](https://github.com/backdrop-contrib/smsframework) has already been ported over to Backdrop (thanks to all those who contributed). I'm the maintainer on d.o (https://www.drupal.org/u/almaudoh) and would like to update the current branch to include the latest bug fixes. I would also help to maintain the module (looks like some work still left in the 1.x-1.0.0 branch too)

**Comment by klonos** [comment]
Hello @almaudoh and welcome to the Backdrop contrib issue queue! I will help you with your request, but please bare with me as we usually have either newcomers applying to become the maintainers of a newly-ported module or people that are already approved members of the Backdrop contrib group applying for co-maintainership. You my friend, I'm afraid do not fit in any of these categories 😄 ...and we do not have a procedure in place for that.

You see, the usual process is that when a person applies to become a contrib maintainer, we have them go through a process of linking to a GitHub repo of a project that they have either created from scratch or have ported from d.org. We then need go through the following checklist:

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

So, the easiest way to set you up would be if you actually ported another project 😄 

Now, once approved, as a Backdrop contrib member, you can then transfer any ported projects from your own repos to the backdrop/contrib repo, or you can ask other maintainers to join them in maintaining their projects (or projects they have ported).

We also have a process where we ask the original project maintainers for approval before porting, and as part of this request we also offer the option of co-interrelationship as a courtesy.

So, in order to be eligible for co-maintainership, you first need to be a member of backdrop/contrib (which you are not at the moment), but on the other hand you are the original project maintainer [which we have already offered to accept as a co-maintainer](https://www.drupal.org/node/2534768). Hmm.

Please do not be put off by this as this is not your fault in any way. It's just that it seems that e do not have the right processes in place for cases such as this.

cc'ing @jenlampton for advice on how to move this forward, and @docwilmot which is the porter and current maintainer of the SMS Framework for Backdrop.

**Comment by docwilmot** [comment]
I think @almaudoh is already a seasoned developer, and we should not be too bureaucratic. Send him the email with the box to check saying he agrees with the rules and let him get on with it.

**Comment by klonos** [comment]
@docwilmot I agree!! ...but I am a member of the PMC and I have to abide by some rules. Here's what I think would be best in this situation...

1. I'll have @almaudoh agree to the Contributed Project Agreement so not to waste time on that.
2. I will wait on an official go-ahead from at least another 2 PMC members (looking at you @serundeputy and @jenlampton 😄)
3. I'll then send the invite.

**Comment by klonos** [comment]
@almaudoh can you please agree to the following?:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib)
(Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2
   `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later. See the
   [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed
   explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
    1. A description of the project
    1. Basic documentation
    1. License information for the project (GPL v2)
    1. License information for any additional assets (SIL OFL fonts, CC-SA images,
       etc)
    1. A list of the current maintainers for the Backdrop project
    1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

      You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)
      to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to an issue to grant
   a new maintainer within 2 weeks, your project may be modified by a Backdrop
   Contrib Administrator to add a new maintainer, without your explicit consent.

Additional notes for non-coders
-------------------------------

1. If an applicant is not (yet) a coder but would still like access to the
   contrib group (for example, for updating documentation or managing issue
   queues) the applicant must get at least one recommendation from another
   person who already has commit access to the contrib group.

1. Any non-coder applicant still agrees to the same contributed project author
   agreement as coders (above).

1. Any non-coder applicant needs to additionally promise that should they ever
   wish to author new code in the Backdrop contrib group, they will also undergo
   the same code spot-check process a new contributor needs to undergo at the
   time they add the code.

**Comment by klonos** [comment]
...number 4 on the list of things to do: work with @jenlampton and the rest of the PMC to put a process in place for when original (d.org) maintainers of a project request to join 😄

**Comment by serundeputy** [comment]
> I will wait on an official go-ahead from at least another 2 PMC members (looking at you @serundeputy and @jenlampton 😄). That way, I'll have at least 50% PMC approval.

I'm not on PMC, but for what it is worth I approve.

**Comment by jenlampton** [comment]
I think we should follow the same guidelines as `Additional notes for non-coders` and require two existing contributors vouch for the person applying. I'm happy to be the second person in this case and gladly welcome @almaudoh to the team :)

I also think we should update that part of the maintainer applications so it applies not only to non-coders, but for applications without code.

**Comment by almaudoh** [comment]
Hey, thanks everyone. I just want to contribute code where I can. Didn't expect my request to trigger a new process to be put in place.

> @almaudoh can you please agree to the following?:

How do I do that? Didn't see any buttons or checkboxes. Can I just say "Yes I agree"? Well, yes I agree.

**Comment by serundeputy** [comment]
@almaudoh yes just state here in this issue as a comment that you agree.  That will be the official record.

**Comment by klonos** [comment]
Invite underway @almaudoh:

>You've invited almaudoh to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome to the Backdrop community and the Backdrop Contrib group! Please let us know if there's anything else you need help with.

**Comment by almaudoh** [comment]
Thanks for the invite @klonos, I've just joined. I'll make a PR immediately for the updates on the smsframework issue queue.

**Comment by klonos** [comment]
No worries @almaudoh. Glad to have helped and thrilled to have you on board!

Seems that everything actionable has been actioned here, so I'm closing this ticked.
