### ISSUE TITLE
Port of Twilio module; request to join the Backdrop contrib group

### ISSUE THREAD

**Issue by mclinn** [backdrop-ops/contrib#232]
I would like to join the Backdrop contrib group here on Github.  I have ported the Drupal 7 version of the twilio module: 

https://github.com/mclinn/twilio/tree/1.11_local

I posted a "backdrop-port" issue on drupal.org on 8/9/17:

https://www.drupal.org/node/2901091

No reply yet.  As I had already begun the work, I decided to go ahead with the port rather than wait -- I am ok with the gamble that the original author might want to do this himself. It sounds like he is involved with a port to Drupal 8 so may not be interested / available anyway. I think Backdrop is fantastic so I enjoyed the port as a way to begin to get familiar with Backdrop.

The Drupal version includes a second module, twilio_twiml, to make use of "twiml," the "Twilio Markup Language."  I have not included this in the Backdrop port.  I have found very little information about using this module; some of the little bit I've found implies that the PHP filter is required to make it work. I don't know if this is true but since the primary module works fine without this I decided to leave it for a possible later project.

I realize that the SMS Framework module, already ported, works well with Twilio and has some additional functionality. This module might be a good fit for someone already familiar with Twilio who just wanted to stick with that platform. The Rules integration seems to work well also.  

One neat "use case" could be sending a text to put your site into or out of maintenance mode. It looks like a simple addition to rules could make this work. I will test this out when I get a chance, maybe add the rules hook in an update later on.

Anyway please let me know how this looks and what else I need to do. Thanks!  

And thanks to all who created Backdrop, what a lifesaver.  I am a textbook example of the kind of person who simply would not have been able to move to Drupal 8 for a variety of reasons. Backdrop has saved the day!

**Comment by jenlampton** [comment]
Hello @mclinn and Welcome to Backdrop!  Thank you for porting the Twilio module :)

I think your decision to omit the `twilio_twiml` submodule is fine, but I would recommend creating an issue for it in your queue (once you have one) stating that you have done so, and for the same reasons you mention here. That way if anyone else was using that submodule on Drupal 7 and moves their site to Backdrop, they will find their answer in the queue (which is the most likely place for them to check).

Even though there may already be a similar module in contrib for backdrop, there is always value in providing the same modules that existed for Drupal 7, as that will help people who are already using those modules make the move to Backdrop. In the future if one is determined the "winner" we can write an upgrade path from the other. But both may end up being great tools, perhaps for different use-cases.

I did a quick review of your port and everything looks great!  Nice job on the conversion to CMI :)

I found only thing to note: in Backdrop we are trying to move away from using the Libraries module. Instead, we put external libraries directly into the Backdrop module. This is for several reasons:

1) we can - this is GitHub and we are not faced with the same restrictions as on drupal.org
2) [DX] developers don't need to download the library separately, and worry about which version actually works with the module (or worry about installing the libraries module!)
3) [UX] should the module or library be updated separately, everything won't suddenly explode

As long as the licensing on the Twilio library is GPL-compatible, I'd recommend bundling directory into a `/libraries/` directory in the module itself. (If not, please disregard!)

@klonos will be along shortly with your maintainer application details :)

**Comment by mclinn** [comment]
Hi @jenlampton and thanks!

I appreciate the comments, looking forward to being involved here.  

I will definitely create an issue about the twilio_twiml submodule when the time comes.

I didn't realize it was possible to include a library within the module, but I'm glad to hear it. I appreciate how Backdrop really makes things as smooth as possible, especially for those new to the whole thing... and the "go somewhere else to get this library file, etc. etc." deal is a fine example of NON-smooth.

I don't know if the license in this case qualifies or not, will post the file here.  It's an "MIT License" but I have no idea what that means.  Regardless, I like the idea of including libraries when possible. Is there an article somewhere about the best way to do this?  I assume this means I can remove the dependency to the libraries module as well where the license qualifies?  I'll make the changes in the twilio module if it turns out this license is GPL-compatible.

I am already crazy about the configuration management system!  I work a lot with virtualbox and have several pcs involved, so I'm constantly moving things around.  Updating a new install is so much easier this way.

The attached file is for Twilio library v. 4.11.
[twilio_LICENSE.txt](https://github.com/backdrop-ops/contrib/files/1236416/twilio_LICENSE.txt)

**Comment by mclinn** [comment]
OK, I was curious... switched off libraries module and dependency, just added require() to call the library's initial file after removing the call to libraries_load() -- seems to work fine.  Is there a more elegant way to do this?  I do like the idea of just including the library code when possible, didn't realize that was a requirement of drupal.org.  I won't implement this here unless I can determine the twilio library is GPL-compatible.

**Comment by jenlampton** [comment]
Yes, MIT is a GPL compatible license. :)

**Comment by mclinn** [comment]
OK, I will "bundle" the library as you suggest and remove the dependency, change installation steps etc.  I like it better already!

**Comment by jenlampton** [comment]
To answer your previous question:

> Is there a more elegant way to do this?

There is. Instead of defining `hook_libraries_info()` which registers your external library with the Libraries API (the contrib module) you could define [`hook_library_info()`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_library_info/1) which would register your external library with Backdrop core. Once you did that, you could use [`backdrop_get_library()`](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_add_library/1) instead of `include()` to add it in wherever it's needed. 

This makes the most sense when your library includes multiple files, but it's a "best practice" to do it anyway because another contrib project wants to support / depend on Twilio, that developer could simply add the Twilio library using `backdrop_get_library()` without needing to know what's inside (or where it's located).

**Comment by mclinn** [comment]
I can see where that could be useful, sure.  I have got twilio just about ready using your original suggestion, however -- I've just added a libraries/ subdirectory and a require_once in the module file.  It's working fine, once I clean it up I can push the revision for review.

Is this ok?  I can use the hook_library_info() in an update later on.  This looks a bit tricky to implement... although I did ask about something "more elegant."  A fine case of "beware of what you wish for"!

**Comment by jenlampton** [comment]
> Is this ok?

Yes of course! It was "ok" before I said anything at all :) Since @klonos is probably busy atm, I'll go ahead and do this part...

In order for a project to be added to Backdrop contrib, we ask these requirements to be met:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

all boxes ticked 👍 
... before granting you access to the backdrop-contrib group, can I please have you agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to an issue to grant
   a new maintainer within 2 weeks, your project may be modified by a Backdrop
   Contrib Administrator to add a new maintainer, without your explicit consent.

**Comment by mclinn** [comment]
Thanks @jenlampton!

Yes, I agree to the above.

I appreciate any and all recommendations.  I've been pretty much a "loner" for much of my tech career so I welcome the opportunity to learn better ways to do things, in addition to learning established procedures etc. within the community. 

I think what you and Nate and others have created with Backdrop is fabulous on many different levels, and I am really looking forward to being part of it.

I am just about ready to push the latest version of the twilio code.  I'm also just getting familiar with git so I will probably have some questions about that, specific procedures etc. once I start interacting with the backdrop repository.  For now I will post link to my repo as I did before, probably a new branch.

**Comment by jenlampton** [comment]
> I think what you and Nate and others have created with Backdrop is fabulous on many different levels, and I am really looking forward to being part of it.

Thank you, from all of us! We're really looking forward to having you be a part of it, too :)

> I'm also just getting familiar with git so I will probably have some questions about that, specific procedures etc. once I start interacting with the backdrop repository. 

Feel free to ask in this issue, in [this queue](https://github.com/backdrop-ops/contrib/issues) or in our [Gitter chat channel](https://gitter.im/backdrop/backdrop-issues) if you need real-time support.

> For now I will post link to my repo as I did before, probably a new branch.

No need to post a link :) However, it would be good to use a branch named `1.x-1.x` when you are ready to issue releases. I notice that branch looks like it's currently still the Drupal version of the module.

> Yes, I agree to the above.

Very well, Invite underway @mclinn!

> You've invited mclinn to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome to the Backdrop community and the Backdrop Contrib group! Please let us know if there's anything else you need help with.

**Comment by mclinn** [comment]
Invitation accepted!  

And I do have questions.  For one, is it better to start a new issue than post into a closed one as I'm doing here?  

The other question is procedural I guess: I've got twilio.module for backdrop ready, and I've managed to get the branch name to 1.x-1.x as you suggest, still on my repo at github.   (had to rename the old repo; this one just has the one branch.)

https://github.com/mclinn/twilio

I saw an article somewhere about the procedure to bring a project into the backdrop-contrib repo but I can't find it now.  And I'm not sure of the protocol anyway -- do you (or someone) need to review the module again before I make an official release and / or import into backdrop-contrib?   Not 100% sure about that either but I am pretty sure that happens after I get the module into backdrop-contrib.

I think I need to use tags as well... I'm catching on to git but plenty more to learn.

As you can see I've got some fuzziness about this new universe I've entered!  I know it will clear up soon enough but as of now I'm not quite sure how to proceed.  Any direction will be appreciated.  Thanks!

**Comment by jenlampton** [comment]
>  For one, is it better to start a new issue than post into a closed one as I'm doing here?

This is fine, as someone is listening ;)

> I saw an article somewhere about the procedure to bring a project into the backdrop-contrib repo but I can't find it now.

I can't find it either, but the repository "owner" us under the settings cog at the top right of a repo:
<img width="1418" alt="screen shot 2017-08-22 at 2 02 30 pm" src="https://user-images.githubusercontent.com/397895/29587372-a0e0bc8c-8742-11e7-9480-baa9990184c1.png">

In there there's a "Transfer ownership" setting down at the bottom, in the DANGER ZONE.
<img width="792" alt="screen shot 2017-08-22 at 2 03 44 pm" src="https://user-images.githubusercontent.com/397895/29587426-cde46fee-8742-11e7-9ad5-d70c864317e2.png">

Enter the organization name `backdrop-contrib` to transfer the repo to the congrib group :)

> do you (or someone) need to review the module again before I make an official release and / or import into backdrop-contrib?

Nope. Once you're in we trust you to make your own decisions about when your project is ready for a release. Of course, if you want reviews or feedback, you are always welcome to ask :)

> I think I need to use tags as well... 

Yes, when you are ready for a release, you'll need to "Tag" that release. Since the Drupal version of Twilio you ported was `7.x-1.11` I'd recommend tagging your first release `1.x-1.11.0` or if you are not ready for prime time yet, `1.x-1.11.0-alpha` or `1.x-1.11.0-beta`.

Here in backdrop land the last `.0` is for bug fixes, so you can release any number of `1.x-1.11.1` or `1.x-1.11.2` to fix little things that come up, so the `-alpha` or `-beta` is not so necessary. (I don't use them)

**Comment by mclinn** [comment]
That all makes sense, thank you. I will go over my port one more time before I put it out there for the world.  Might be a day or two but I'll get it out there.  I will probably show up in one of the other venues, chat etc. with questions as I figure stuff out here.

I've already got some ideas for upgrades... I can see how this stuff could consume 110% of one's time.  

Thanks for coaching me along in my first steps as a backdrop contributor!  I've been meaning to get involved in this kind of thing for quite some time now but never quite got around to it.  When I found backdrop I realized I had to make the jump.  You're doing something super here and I'm looking forward to adding whatever I can to help.
