### ISSUE TITLE
Request admin access to Featherlight module

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#234]
I just transferred ownership of my newly-created Featherlight module to backdrop-contrib: https://github.com/backdrop-contrib/featherlight

However I seem to have lost the ability to administer it... I need to access the Settings for that repository to change the default branch from 'master' to '1.x-1.x', but there's no Settings option in Github on that page for me.

I've previously written and transferred the Simplify module, and I have access to that: https://github.com/backdrop-contrib/simplify Not sure what I did wrong this time...

**Comment by BWPanda** [comment]
While you're at it, can someone point me to the instructions on how to change the branch from master to 1.x-1.x? I was able to create a new branch on my server, but it doesn't seem to have been pushed to Github...

**Comment by jenlampton** [comment]
I've restored your admin access.  You are not the first one who has fallen into that trap..  We should document better so that doesn't happen to the next person as well.

The default branch is under "Settings".
<img width="1026" alt="screen shot 2017-09-07 at 7 58 14 pm" src="https://user-images.githubusercontent.com/397895/30194258-ed6ac0cc-9406-11e7-818d-bc53bf19c4e3.png">

**Comment by BWPanda** [comment]
@jenlampton Thanks so much!
