### ISSUE TITLE
Port of Geolocation field

### ISSUE THREAD

**Issue by opi** [backdrop-ops/contrib#238]
Drupal module: https://www.drupal.org/project/geolocation

Drupal issue: https://www.drupal.org/node/2914022

Work in progress: https://github.com/opi/geolocation

**Comment by opi** [comment]
> Some people also post an issue into the backdrop-ops/contrib queue, mentioning that a specific module is about to be ported, and linking to the Drupal issue. This post can also serve as an application to join the Backdrop Contrib group.

( from https://api.backdropcms.org/converting-modules-from-drupal )

So please consider this as an application to join the Backdrop Contrib group <3

**Comment by jenlampton** [comment]
Since I think @klonos is pretty busy these days, I'd like to take over and get you into the contrib group :) 

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

We'll also need an official agreement to abide by the terms here in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md

@opi If you can give that a read, and state for the record here in this issue thread if you agree or disagree (of course agreeing is required for admittance to contrib group) :)

thanks,
Jen

**Comment by jenlampton** [comment]
👍 Fantastic, thank you :) I have sent you an invitation to join the contrib group. Once you have it, you should be able to transfer any projects you would like into the group.  

You might try to add yourself as a contributor (with admin rights) before you transfer, so that you can retain admin access after the transfer. If that doesn't work, please let us know and we can fix the access for you after any repository has been transferred.

**Comment by opi** [comment]
Done https://github.com/backdrop-contrib/geolocation

**Comment by klonos** [comment]
Yeah, I am too scared to eve look at the list of unread Github notifications :( ...sorry for not being around much lately guys.
