### ISSUE TITLE
 Requesting access to contrib (and port of filefield_paths module)

### ISSUE THREAD

**Issue by kleomash** [backdrop-ops/contrib#246]
Hello! 
 I've started port my sites from drupal to backdropcms. For now I found and fixed one bug in entityrefernce project ported to backdropcms.

I'd like access to backdrop-ops/contrib to join to the team sicnse I plan fully move from drupal to backdrop and interesting to port modules I need.

**Comment by jenlampton** [comment]
Hello @kleomash and welcome to Backdrop! 
We'd love to have you be a part of the contrib group :)

If you have ported a module, theme, or layout (or started to) we would like to see your work on that project before we admit you as a maintainer for contrib. You can post a link here to your personal GitHub repo for a quick review.

If you have not started to port modules, themes, or layouts yet, or have no code ready to show us, we will still grant you access to the contrib repo if two existing maintainers can vouch for you, either based on your work with Drupal or Backdrop. (The list of existing maintainers is here: https://github.com/orgs/backdrop-contrib/people feel free to browse for your friends or colleagues)

**Comment by kleomash** [comment]
Hello @jenlampton!

Just now I've ported filefield_paths module. It seems working, but not fully tested yet. For now I'm starting using it at my new site building on backdrop.

You can check my work at https://github.com/kleomash/filefield_paths

**Comment by jenlampton** [comment]
Great!  Thanks for sharing :)

New project checklist
---------------------

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [ ] Official agreement to abide by the terms in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md

For your maintainer application:

* It looks like you'll still need to add a LICENSE.txt file into the repo - this is a step that the drupal.org packaging script handled for us, but we do manually here for Backdrop projects.
* It would be great if in the readme you could separate the `History and Maintainers` section into two, one for Maintainers (listing yourself as the Backdrop maintainer) and one for Credits (listing Deciphered as the Drupal maintainer), as in our example readme (linked above). 
* We'll also need a section added to the README about license information, also as in our example readme (linked above). 
* We'll also need an official `Yes, I agree` statement from you, agreeing to abide by the terms in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md


General notes on your port. (...and these notes are intended to be helpful -- they are in no way a requirement for becoming a member of contrib!)

* in your module's `.info` file you'll need to add the line `type = module` in order for the Backdrop packaging script to work correctly. 
* The `pathauto` and `token` modules don't exist for Backdrop, those features have been merged directly into core, so those lines can be removed from the .info file - they do not need to be ported or adapted at all, they are a given :)
* It looks like you haven't ported the tests yet, let me know if you need help with those. It's a pretty simple find/replace action, but it's helpful to know exactly what to find & replace! :)
* In `filefield_paths_config_info()` the group is defined as `File (field) paths` but it doesn't look like this module provides a whole set of configurations (like image styles) that need to be grouped together. In this case, I'd recommend changing the group to simply `Configuration` so that this module's settings will be grouped with every other module that provides a single config file.
* The hook `filefield_paths_form_alter()` is going to execute for all forms on a backdrop site. If this can't be restricteed by form_id or base_form, is there some testing we can do at the very top, so we can return if the code within isn't necessary on a particular form?  This should result in a performance gain.
* The external link to Redirect module (https://drupal.org/project/redirect) can be removed, since that is part of core in Backdrop.
* the functions `drupal_get_form()`, `drupal_basename()`, `drupal_static()`, `drupal_encode_path()`, `drupal_substr()` and `drupal_strlen()` can be replaced with `backdrop_get_form()`, `backdrop_basename()`, `backdrop_static()`, `backdrop_encode_path()`, `backdrop_substr()` and `backdrop_strlen()`.
* It might be a good idea to remove `filefield_paths.variable.inc` since there likely won't be a variable module for Backdrop, since we don't use variables anymore. If we do get a copy of that module it's likely to work differently and these implementations may not "just work". The same might be said for `modules/features.inc`.
* It might also be worth renaming the `modules` directory to something like `includes` since a directory named "modules" usually includes sub-modules. I'm not sure about this one...  it might be better to keep it the same so D7 patches apply cleanly ;)
* Nice job with the update hook, and the use of `hook_update_last_removed()` 👍

**Comment by kleomash** [comment]
Hi, @jenlampton !

I've checked and fixed your notes except of next:

1. Tests is not ported for now. I need help what to find and replace.
2. I did not fix configuration name as I want to specify if group should be `Configuration` or `configuration`?
3. I did not fix hoot flefield_path_form_alter(). I agree we should add checking if we need form alter at top, but for now do now know how. This is my first experience in Drupal/Backdrop coding. So I'll add issue for the future.

I decided to rename modules directory to includes.  Last commit for original project was about two years ago, so I think it will not be a lot of patches in the future.

Where I should say 'Yes, I agree' to statement? Is it enough here? If enough then I'm saying: "Yes, I agree'.

**Comment by jenlampton** [comment]
Thanks @kleomash!  Yes, it's enough to say `Yes, I agree` right here, so thank you, and also thank you for addressing all those other issues as well.  Our checklist is looking great!

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [x] Official agreement to abide by the terms in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md

Im going to send you an invite to the contrib group right now! Once you have joined you should be able to transfer the filefield_paths repo into the group using [these instructions](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) 

Any issues you'd like to address from above can be added into the issue queue - and I'd be happy to help with instructions for the tests.

Welcome to contrib! :)

**Comment by kleomash** [comment]
Hi, @jenlampton!

I think it is good idea to port tests for the module. You said that you could get info what I need to do to port them. After that I could make release of the module.

Thank you in advance.

**Comment by klonos** [comment]
This port is complete. Any issues should be reported in https://github.com/backdrop-contrib/filefield_paths/issues
