### ISSUE TITLE
System_settings_form conversion question

### ISSUE THREAD

**Issue by quackers8me** [backdrop-ops/contrib#26]
I've run into a problem in converting from this drupal function and am hoping for some insight. I've seen examples of saving individual form_state values with config->set, but what about the following code?

```php
$form += backup_migrate_nodesquirrel_info_form();
$form += backup_migrate_nodesquirrel_status_form($key, $destination, $status);
$form += backup_migrate_nodesquirrel_credentials_settings_form($key, $status);
$form += backup_migrate_nodesquirrel_schedule_settings_form($destination, $status);
return system_settings_form($form);
```

**Comment by quicksketch** [comment]
That's interesting, I wonder why the functions are split up like that. Does the module call those forms in other locations besides the settings form?

I'd probably convert this form as any other, and add in:

```php
$form['actions']['#type'] = 'actions';
$form['actions]['submit'] = array(
  '#type' => 'submit',
  '#submit' => t('Save configuration'),
);
return $form;
```

And then write the submit handler to save the individual values into config one at a time, just like any other form. If it turns out that these save in multiple locations, you might make 4 different functions for saving to match the 4 different functions for creating the form, but I doubt that will be the case.
