### ISSUE TITLE
Application to join Backdrop contrib community

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#289]
Hi, I'm Tim Erickson or stpaultim. I'd be interetest in joining the Backdrop contrib community. My company, Triplo, recently started using the Views Bootstrap module and have submitted a couple of pull requests. However, the module appears to be unmaintained at this time. We would be interested in volunteering to work on this module (and/or other contrib projects). 

I agree to the Backdrop Contributed Project Agreement.

Here is a link to my Drupal.org profile
https://www.drupal.org/u/stpaultim

**Comment by klonos** [comment]
Our [Backdrop Contributed Project Group Application](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-group-application) states the following:

>- If you are not submitting code for review at the time of application (for the purposes of managing issues) you must have at least one recommendation from a person who is already a member of the Backdrop contrib group.

I would gladly vouch for @stpaultim, but for the sake of transparency, and since I will be the person reviewing and approving the application, I would prefer to have someone else also give a thumbs up (preferably not affiliated with Triplo please).

**Comment by oadaeh** [comment]
I'll vouch for Tim.
Unfortunately, I don't know David, so I cannot vouch for him.

**Comment by alexfinnarn** [comment]
Same as #290, maybe it would be good to amend the process to also include reviewing PRs to existing projects instead of only new Backdrop modules? By the current logic, if someone unknown to the contrib group wants to join Backdrop, they have to port a module that the community might not need in order to work on an existing, potentially abandoned project that might be used by many Backdrop sites.

**Comment by klonos** [comment]
@stpaultim invite underway:

> You've invited Tim Erickson to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Officially welcome to the club 😉 🎉
