### ISSUE TITLE
How will we track which contrib is module vs theme vs layout?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#29]
Related https://github.com/backdrop/backdrop-issues/issues/625
The list is growing rapidly; [@oadaeh is threatening](https://github.com/backdrop-ops/contrib/issues/2#issuecomment-70833032) to port 12 modules from his favorites soon. Just curious how will we track these, and how will users search.

**Comment by oadaeh** [comment]
I thought of another one this morning (MIME Mail, which depends on Mail System), that i might add to the list. :)

**Comment by quicksketch** [comment]
@oadaeh++

Too many projects is a wonderful problem to have.

I'm not sure we'll be able to make the backdrop-contrib list sustainable for any period of time. It's already pretty unwieldly with only 20 modules in there. The fact that they're ordered by the last time they were worked on (rather than something logical like their name), makes browsing modules difficult.

I think our best bet is to work on porting backdropcms.org to Backdrop, then working on the contrib listing there. We have an issue for that at https://github.com/backdrop-ops/backdropcms.org/issues/8.
