### ISSUE TITLE
Page background module

### ISSUE THREAD

**Issue by degami** [backdrop-ops/contrib#31]
Here is a port of my "Page background" module to backdrop.

here's the repo: https://github.com/degami/backdrop_page_background

"A simple way to associate an image or a slideshow to a path.

You can upload an image and set it to be shown as background image for the
specified path.
More images on the same path will become a slideshow
(if jquery.cycle is installed) .
You can also associate images to "default" , so if the path you're visiting has
no images directly attached one random image (or a slideshow) from the "default"
is shown.
Backgrounds can also be exposed as a block."

**Comment by quicksketch** [comment]
Hi @degami! Thanks for porting your module to Backdrop!

We like to check a few basic things before moving modules into the Backdrop Contrib group. Could you address the following?

- [ ] Update the REAME.md to include a list of maintainers, and license information. You can copy [this example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md).
- [ ] Include a LICENSE.txt file indicating it is GPL v2. You can use [this copy](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt).

We also prefer that you keep the entire project history from Drupal 7, by doing a Git checkout of the 7.x-1.x branch from drupal.org, renaming it to 1.x-1.x, then copying your port over the top, but it looks like in this case your project has a sad story getting stuck in the review process. :frowning: Since this is essentially the initial public version of this module, no history is needed and it's up to you if you want to keep the previous history or not.

Long-term, it'd also be great to move away from `variable_get()` calls to leverage the configuration management system in Backdrop, but that conversion can come at any time and will probably happen naturally as you maintain the module. You can read more about converting a module to Backdrop at https://api.backdropcms.org/node/28621 (still a work in progress).

**Comment by degami** [comment]
Hi @quicksketch, 
thanks for your reply. Will add the missing files asap. I didn't changed yet the variable_get/set yet as i just need to understand the differences in the approach... Will do it asap

**Comment by degami** [comment]
Sorry for my english, btw

**Comment by quicksketch** [comment]
No problem @degami! We're excited to have your help. :smile:

Just let me know when the LICENSE.txt and README.md have been added/updated.

**Comment by degami** [comment]
Hi @quicksketch . Files added! No drupal -history , as it was not intresting

**Comment by quicksketch** [comment]
Excellent! I've sent an invite your way.

One more thing, in the README.md, please change "BackDrop" to "Backdrop". Thanks!

**Comment by quicksketch** [comment]
Oh dang, I forgot to have you confirm the agreement. Would you agree to the following for the record?

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must agree to license your contributions as GPLv2 or later.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.  The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explaination.    

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later. 

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc) 
  1. A list of the current maintainers for the Backdrop project
  1. A list of the past maintainers for the Backdrop or Drupal project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by degami** [comment]
Hi @quicksketch ,
fixed the typo in README.md. 
Of course I do agree with the Backdrop Contributed Project Author Agreement

Thanks

**Comment by quicksketch** [comment]
Excellent. Thanks @degami!
