### ISSUE TITLE
Port Request: Views Photo Grid

### ISSUE THREAD

**Issue by korontari** [backdrop-ops/contrib#310]
There are very few modules that allow to create nice responsive galleries (I know only Masonry view at the moment). This module provides a very nice grid arrangement and is responsive and mobile friendly.

https://www.drupal.org/project/views_photo_grid

 #Port Request

**Comment by docwilmot** [comment]
it's helpful to run the d7 code through Coder Upgrade module, then create a repository on GitHub.

**Comment by korontari** [comment]
I am sorry I am not a programmer, just a Backdrop user.  I don't understand what you mean here. :)

**Comment by jenlampton** [comment]
@docwilmot 	This might be something that is worthy of a blog post on backdropcms.org: a brief tutorial on running modules through coder upgrade, for the non-programmers among us!  I'll mention this at the meeting today and see if anyone wants to take this on.

**Comment by docwilmot** [comment]
Good point. Also include how to upload to a repository.

**Comment by Graham-72** [comment]
@korontari first you need to create a repository in your personal github account and upload all the module files to there. Give the repository a title and then, under settings, transfer ownership to backdrop-contrib, assuming you have the right permissions to do this. I look forward to seeing your port of this module.

Before you transfer ownership, you can invite others to look at your repository, which will be public.

**Comment by korontari** [comment]
@Graham-72 Thank you very much for your interest and advice! I have made a [repository ](https://github.com/korontari/Views-Photo-Grid) with the code that I ran through Coder Upgrade module. Could you have a look at it and tell if I can transfer ownership to backdrop-contrib?

**Comment by Graham-72** [comment]
@korontari I will be glad to take a look at your repository during this week.

**Comment by Graham-72** [comment]
@korontari I see that the Coder Upgrade module did not convert your javascript file by changing Drupal to Backdrop, but there is just today a new release of Coder Upgrade that will do this. It may be easiest to delete the repository you have just created and start again because of the following consideration.

I suggest you look at https://github.com/backdrop-ops/contrib because there it explains what you will have to do before you can become a member of the contrib group which you will need to do.

You will see there that one of the requirements is to preserve the history of the D7 module, and this                                                                         is best done by starting from a copy of the D7 code repository and then committing changes to that. I am sorry but I misled you be saying you could just upload your code to a github repository.

To create your own copy of the D7 repository you can, if you are able to use git, follow the procedure described in https://api.backdropcms.org/converting-modules-from-drupal

Or you can use https://github.com/new/import 'Import your project to GitHub' in your browser, and give it the D7 code repository address which in this case is https://git.drupal.org/project/views_photo_grid.git.  This will import all the branches of the project and you delete all except the one you are porting, and then from it create a new branch 1.x-1.x for Backdrop. This will be the one to convert using Coder Upgrade.

Once you think your repository is correct you can apply to be a member of the Contrib group and then, once approved, you will be able to transfer it to backdrop-contrib.

**Comment by korontari** [comment]
@Graham-72 Thank you for the in-depth instructions! I have followed the second way and imported D7 code from the link you provided, removed extra branches and created the one for Backdrop which I then updated with code from Coder Upgrade. Could you check it and tell if everything is correct, please?

**Comment by korontari** [comment]
Here is the link to the repository: https://github.com/korontari/views_photo_grid

**Comment by Graham-72** [comment]
@korontari I have had an initial look but I am wondering whether your repository has the code produced by Coder Upgrade? Just looking at views_photo_grid.info suggests something is wrong. Please can you check.

**Comment by korontari** [comment]
@Graham-72 Sorry, something went wrong. Could you check [the repository](https://github.com/korontari/views_photo_grid) again, please?

**Comment by Graham-72** [comment]
@korontari I have now had a look at your repository. One thing you will need to do is create a README.md file. Have a look at what other modules have in one of these. Also, your repository will need a short description - there is a field for this in GitHub.
I have installed your module in a test site and found one problem that I don't know how to fix. In the file `views/views_photo_grid_plugin_style.inc` there is line 60
 `if (!is_numeric($this->view->vid)) {`
and `vid`does not exist in Backdrop, and I don't know what replaces it. 
Perhaps the quickest way to get an answer is to ask on the chat channel `https://gitter.im/backdrop/backdrop-issues`

**Comment by jenlampton** [comment]
There's a vocabulary name now instead, just like in D7.

**Comment by Graham-72** [comment]
@jenlampton thanks but unfortunately I know almost nothing about the inner workings of D7, particularly Views, so not familiar with the term 'vocabulary name'. Is that simply the name given to the view? If so, I'm wondering why the code in question is testing that it is not numeric?

Anyway, I have modified the code so that it tests the value of view['name'] and the module now seems to work without producing an error report. So maybe @korontari should compose a README.md, make this fix, then apply to join backdrop-contrib?

It looks like a useful module.

**Comment by jenlampton** [comment]
> not familiar with the term 'vocabulary name'.

It's the name given to a Taxonomy Vocabulary. Early in Drupal 7 each had a unique auto-increment number, or `vid`. At the end of Drupal 7 they switched them over to using machine names instead. Backdrop kept the machine names, but dropped the `vid`.

> I'm wondering why the code in question is testing that it is not numeric?

This is a good point - machine names are usually not numeric anymore, so this check is likely preventing the following code from running entirely. That makes me think it may not be needed for the views you are testing, but perhaps when it is there may be an issue? 

> So maybe @korontari should compose a README.md, make this fix, then apply to join backdrop-contrib?

That sounds great to me! We could post an issue in the new contrib queue about this possible problem, and then wait and see if anyone encounters it.

**Comment by korontari** [comment]
@Graham-72 @jenlampton Thank you for checking out the module repository. I have added a description and  Readme.md file. It is loosely based on what I saw in other BD modules readme files. I marked the Maintainers section as TBD. As to the fix, I am not sure I understand what exactly I should change as I have a zero knowledge of both D7 and Backdrop API's.  I understand that if(!is_numeric($this->view->vid)) check should be replaced with some other check but I don't know what exactly should be instead of it as I don't understand the meaning behind it. Maybe the quickest way would be if @Graham-72 sends me the code fragment to replace this 'if' statement?

**Comment by Graham-72** [comment]
@korontari it seems it only needs you to replace 'vid' with 'view' and it will work. So the line should be
`if (!is_numeric($this->view->name)) {`

Perhaps later we will find out the purpose of this test and whether it is still needed.

**Comment by korontari** [comment]
@Graham-72 Thank you, fixed that!

**Comment by herbdool** [comment]
I haven't tested but I imagine the view name is never numeric so that if statement needs to be something else. The comment in the code says it is checking if the view is new or not. In D7 I imagine it wouldn't have a vid if it was new. We need to find the equivalent here. Perhaps there's a isNew flag?

**Comment by jenlampton** [comment]
> Perhaps there's a isNew flag?

There is in a `$config` object. Not sure about the view itself.

**Comment by herbdool** [comment]
Good question, @jenlampton. I just tested it and doesn't seem like there is. The view name can't be used either since it exists even before it is saved. I'm not sure what else can be used. Regardless that if statement isn't totally necessary, though without it someone sees the validation message right away, which is a bit annoying.

**Comment by docwilmot** [comment]
What exactly happened to this port? Sounded useful.

**Comment by korontari** [comment]
On my side I couldn't make it work properly. The grid sometimes appear with images overlapping and grid layout changes considerably every time the page is reloaded. I am not sure but it seems there is a problem with jQuery plugin, not Backdrop implementation. I found it easier to switch to another plugin with similar functionality.

**Comment by klonos** [comment]
Hello @korontari 👋 ...I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
