### ISSUE TITLE
Port request: navbar

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#318]
I think the admin menu of backdrop is great, but I think there is another very great module: the drupal navbar module. I think it has a great user experience; it would be great to port it in backdrop and maybe use it as a default admin menu, or maybe use a mixture between the backdrop admin menu and the drupal navbar module;

This issue was spun off from a comment by @fivepoints79 in 
https://github.com/backdrop/backdrop-issues/issues/495#issuecomment-461456258

**Comment by VasasA** [comment]
I am working: Porting Navbar module
[https://github.com/VasasA/navbar](https://github.com/VasasA/navbar)

**Comment by VasasA** [comment]
Dear @jenlampton and @klonos ,
I think I have finished the porting. :smile:
[https://github.com/VasasA/navbar](https://github.com/VasasA/navbar)

**Comment by klonos** [comment]
Thanks @VasasA 👍 

No need to specify a version number. When you create a GitHub release, the Backdrop packaging script will add that automatically for you: https://github.com/VasasA/navbar/pull/5

**Comment by VasasA** [comment]
Thank You, I merged the PR.
Can I transfer the module to https://github.com/backdrop-contrib/?

**Comment by VasasA** [comment]
Thank You! I merged the PR, and fixed the error: https://github.com/VasasA/navbar/commit/7e407c96cfe65b2236dd567aae3cdcf170591a95
Can I transfer the module to https://github.com/backdrop-contrib/ ?

**Comment by BWPanda** [comment]
A few questions:

- There's a lot of icons included here. Can they not be removed and the icons in core used instead?
- What's the difference between/purpose of the two close icons? (Seems to me that you don't need an RTL-specific version...)
- There's quite a few JS libraries included. Are they all actually needed, or does core include some of these now?

**Comment by klonos** [comment]
@VasasA I have filed a few issues and some PRs against the project, but these do not need to be addressed before you join. All projects that are to be included in backdrop-contrib must meet these minimum requirements, and your port ticks all these:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0).

...so **the last thing that remains is to have you say that you agree with the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**.

You can then be invited and will be able to transfer the project. I would suggest to refrain from creating a release until all the major issues have been addressed. Perhaps instead of a "stable" release, you can create a 1.x-0.0.1 (as in "early alpha" 😉)

**Comment by VasasA** [comment]
Dear @BWPanda,
I think the icons and the scripts can be useful when a developer uses the module's API, or the "Administration menu" (admin/structure/menu/manage/management) is changed.

**Comment by VasasA** [comment]
@klonos Thank You the PRs and issues! I'm working on these. :smile: 
I agree with the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement).

**Comment by klonos** [comment]
Sorry @VasasA ...I forgot that you have already ported https://github.com/backdrop-contrib/menu_import and that you are already a member of the Contrib Group 😅 

What happens usually is that once you are a member of the Contrib Group, you can create repos for the ports directly under https://github.com/backdrop-contrib. You do not need to create a release if the module is not ready yet.

In other words, please feel free to move https://github.com/VasasA/navbar under https://github.com/backdrop-contrib and we can continue working on it there, until it becomes release-ready 😄 ...until then, you can create a beta, or alpha release.

**Comment by VasasA** [comment]
No problem :smile:
I transfered the repo.

**Comment by klonos** [comment]
I think we can close this one. Thanks @VasasA for all your work on porting modules to Backdrop 👍 🙂
