### ISSUE TITLE
New non-port module

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#33]
https://github.com/docwilmot/site_info_blocks

Not sure what the process is if its not a port and not the first push. Do we still require a post here? Or can I just push to contrib to my heart's content?

**Comment by quicksketch** [comment]
Hi @docwilmot! Push to contrib to your heart's content. :smile: 

Of course use judgement if it's either not finished or so specialized it doesn't have much use to others. For example I push up a port/rewrite of the Select2 module to my personal repository (https://github.com/quicksketch/backdrop-select2) because I got 1/2-way through and realized Select2 wasn't going to work for my purposes (see https://www.drupal.org/node/2346973#comment-9548453). So I put up the half finished module into my personal repo instead of the official contirb.

Thanks again!
