### ISSUE TITLE
Offer to maintain Libraries

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#330]
[Libraries](https://github.com/backdrop-contrib/libraries) doesn't list a current maintainer, so I'm offering to take over: https://github.com/backdrop-contrib/libraries/issues/10

**Comment by klonos** [comment]
Thanks @BWPanda 👍 

@jenlampton what should we be doing in such cases where there is no current maintainer? Still wait a couple of weeks as per policy re abandoned projects?

**Comment by BWPanda** [comment]
I know you didn't ask me (:stuck_out_tongue_winking_eye:), but here's my interpretation of https://github.com/backdrop-ops/contrib#adopting-abandoned-projects

- A module is abandoned if there's no current maintainer listed in the README
- If there is a maintainer listed, you should give them time to respond
  - If they don't respond within two weeks, the module's then considered abandoned
- You don't need to wait to create a request in this issue queue if the module's already abandoned
- A Backdrop Contrib admin just needs to confirm the abandoned status of the module to address this request and update the README

So as I see it, no need to wait ('cause what would we be waiting for?) But that's just my take, and if I'm mistaken maybe we need to change the wording on the instructions...

**Comment by jenlampton** [comment]
I agree with @BWPanda about abandoned projects, but...

@BWPanda what's your use case for using Libraries module?

It shouldn't be needed on Backdrop sites since libraries **should** be bundled into their parent modules. Backdrop core is our package manager, and using something like Libraries breaks that model.

**Comment by BWPanda** [comment]
Hmm, I'll have to take a look through my sites to see which use Libraries and  why...

**Comment by BWPanda** [comment]
So this was the issue I originally had with Libraries: https://github.com/backdrop-contrib/libraries/issues/7 Not sure if its still an issue in core...

But I got around it as explained, and it seems I need to update Views Slideshow Cycle 2 to use core instead of depending on Libraries. That's the only reason I've been using it.

**Comment by jenlampton** [comment]
Thanks for the link! 

Do you use cycle2 for something else on the same site(s) where you are using it in views_slideshow_cycle2? 

I'm asking because this seems to be everyone's worry: that bundling a library in too-specific a use case may cause problems. Yet, in the real world I've never had a site that used the same library twice - by two different modules.

I believe @laryn got around this for some of his projects by creating a separate module only for the library (that provided a only hook_library implementation) and then required that module from the module that needed the library.

In this case though, I'd recommend bundling cycle2 in the views_slideshow_cycle2 module first, and then wait and see if it's ever an issue before abstracting.

**Comment by BWPanda** [comment]
> In this case though, you might want to bundle cycle2 in the views_slideshow_cycle2 module first, and then wait and see if it's ever an issue before abstracting.

Wise words. I remember reading something ages ago in programming about not trying to solve problems before they happen (e.g. we can try to anticipate and account for every possible future scenario, but that'll only lead to enormous amounts of code and an unnecessarily delayed release), but I still struggle to do that sometimes :smiley: So thanks for the advice/reminder to keep it simple.

May I also still ask to be made maintainer just so I can update the README and mark Libraries as deprecated?

**Comment by jenlampton** [comment]
> May I also still ask to be made maintainer

Yes :)  Can you please file a PR on https://github.com/backdrop-contrib/libraries/issues/10 that adds your name to the README?  I'd be happy to merge it.

**Comment by BWPanda** [comment]
Done :smiley:
