### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by drupol** [backdrop-ops/contrib#333]
Hi all,

I'd like to share some stuff in the Backdrop community, would it be possible to join you ?

The project I'd like to port/maintain is: https://www.drupal.org/project/atomium
Link to the repo: https://github.com/ec-europa/atomium

Thanks.

**Comment by klonos** [comment]
Hey @drupol 👋 ...according to https://github.com/backdrop-ops/contrib#new-project-checklist, all projects must meet these minimum requirements.

- [ ] If porting a Drupal project, Maintain the Git history from Drupal 7. See
    [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [ ] Include a README.md file that includes license and maintainer information.
    You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0)

**Comment by klonos** [comment]
- All 7.x commits have been maintained, as the GitHub repo contains the 7.x version(s): https://github.com/ec-europa/atomium/commits

- README.md exists here: https://github.com/ec-europa/atomium/blob/backdrop/README.md ...but the maintainer names are not listed.

- License exists here: https://github.com/ec-europa/atomium/blob/backdrop/LICENCE.txt ...but it is European Union Public Licence, which I am not sure if it's compatible with GPL 2/3 🤔

**Comment by klonos** [comment]
https://eupl.eu

> **Is the EUPL compatible with the GPL and other F/OSS licences?**
> Yes, it is. The EUPL contains a unique compatibility clause and provides for a list of compatible copyleft licences. The GPL is one of them.

**Comment by quicksketch** [comment]
Thanks @klonos! Reading that document it's a little strange but they outline the situation here:

> For example, how would the interaction between the EUPL and the GPL play out in the case of CIRCA, an application a already distributed under the EUPL?
> 
> A developer may merge the Circabc software with a GPL component, and then could license the new derivative work (another project, with a new name) under the GPL. It is not permitted to "re-license" CIRCA under the GPL. A developer will be also able to integrate CIRCA in existing GPL work called e.g. "MY-GPL-PROGRAM" and continue to license this improved work under the GPL licence that he had chosen originally.

So bizarrely, we can re-license it as GPL and include it in the Backdrop repository but only if it had a new name?

If that is the case, it also looks like the Drupal theme is in violation of Drupal's requirement of a GPL license. https://www.drupal.org/about/licensing#project-licensing

**Comment by quicksketch** [comment]
I'm reading over the entire license file and here's the specific part of the license for "compatible licenses":

https://github.com/ec-europa/atomium/blob/7.x-3.x/LICENCE.txt

>  - Compatibility clause: If the Licensee Distributes and/or Communicates
   Derivative Works or copies thereof based upon both the Original Work and
   another work licensed under a Compatible Licence, this Distribution and/or
   Communication can be done under the terms of this Compatible Licence. For
   the sake of this clause, "Compatible Licence" refers to the licences listed
   in the appendix attached to this Licence. Should the Licensee's obligations
   under the Compatible Licence conflict with his/her obligations under this
   Licence, the obligations of the Compatible Licence shall prevail.

With the compatible licenses listed at the bottom:
>  * GNU General Public License (GNU GPL) v. 2
>  * Open Software License (OSL) v. 2.1, v. 3.0
>  * Common Public License v. 1.0
>  * Eclipse Public License v. 1.0
>  * Cecill v. 2.0

I don't see anything about renaming a project. But I think they're just saying you can't take the original source project, completely unmodified, and then distribute it with a different license.

Since this has been modified for Backdrop, I think it qualifies as a derivative work of the original Atomium theme. So in theory you could just swap out the LICENCE.txt file for the GPL v2 and you'd be all set. @drupol would that be possible?

Otherwise, our policy of only GPL v2 (and allowed exceptions for v3 with reason) will need to be adapted to suit this new license situation. The concept behind the EUPL would allow this project to keep the EUPL license, but when it's distributed (say, when packaged by the BackdropCMS.org packager), it's license would change in the process to actually be GPL. We'd need some way to indicate that, perhaps with just a note in the README.md file would suffice.

**Comment by drupol** [comment]
* Updated the LICENSE.txt (not LICENCE.txt)
* Added some paragraphs to README.md about current maintainers, credits and licencing.

**Comment by klonos** [comment]
Hello @drupol ...with the latest changes to the README, and with the change of the license to GPL-2, all checkboxes have been ticked! Invite is underway:

>You've invited Pol Dellaiera to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Officially welcome to the Backdrop Contrib group! 🎉

**Comment by drupol** [comment]
Thanks :heart: !!!

**Comment by klonos** [comment]
😉 

...closing this one then.
