### ISSUE TITLE
Notice : Array to string conversion dans _options_storage_to_form()

### ISSUE THREAD

**Issue by salahjaafar** [backdrop-ops/contrib#338]
this error appears

Notice : Array to string conversion dans _options_storage_to_form() (ligne 315 dans /opt/lampp_5.5.19-0/htdocs/core/modules/field/modules/options/options.module).

**Comment by jenlampton** [comment]
Hi @salahjaafar, can you please post this issue in the core queue? Since the error references 'core' that's likely where the problem lies. 

There are also issue templates in that queue that will help you create an issue that people can use to find and resolve your issue: https://github.com/backdrop/backdrop-issues/issues/new/choose

(We can sometimes transfer the issues for you, but sadly that won't work in this case)

**Comment by salahjaafar** [comment]
Thank you for your reply,
I put the mistake in the part you mentioned

**Comment by jenlampton** [comment]
Thank you!
