### ISSUE TITLE
Application to join: Harzah2 (bbcode module)

### ISSUE THREAD

**Issue by Harzah2** [backdrop-ops/contrib#340]
I would like to apply to join the Backdrop contrib team.

Here is a module I ported: https://github.com/Harzah2/bbcode

[LICENSE.txt](https://github.com/backdrop-ops/contrib/files/3349653/LICENSE.txt)

[README.txt](https://github.com/backdrop-ops/contrib/files/3349655/README.txt)

**Comment by klonos** [comment]
Hello @Harzah2 and thank you for porting this.

A few things:

- Out of curtesy, when porting a module from 7.x, we usually [file a ticket against the d.org issue queue of that project](https://www.drupal.org/node/add/project-issue/bbcode), to let the original project maintainer(s) know our intention to port it to Backdrop. Please allow the maintainer(s) some time to respond, in case they want to port and maintain the module themselves. If they are not interested, still let them know that they are welcomed to join as co-maintainers of the Backdrop port in the future.

According to our new project checklist, all projects must meet these minimum requirements.

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7. See
    [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [ ] Include a README.md file that includes license and maintainer information.
    You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0 -- please see below). Please use [this text for GPL-2.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
  * If your project includes a library that is licensed under GPL-3.0, LGPL-3.0,
    Apache-2.0, AGPL-3, or any other license that the Free Software Foundation
    has determined to [only be compatible with GPL-3.0](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses),
    then you must license your project as GPL-3.0. Please use [this text for GPL-3.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE-GPL-3-0.txt).
  * The GPL-3.0 license will prevent your project from one day being included in
    Backdrop core, so please only use this license when necessary.

**Comment by klonos** [comment]
...so here's a few suggestions:

- Remove the current `master` branch, or at least make 1.x-1.x the default.
- Remove the non-Backdrop releases from https://github.com/Harzah2/bbcode/releases (unless you are planning to become the maintainer of the D7 module as well)
- Remove the 1.x-1.x release. It's better to wait for the project to be approved and moved to https://github.com/backdrop-contrib and make a release then. This will make it so that when you create a release, the Backdrop packaging script will create a node for this module in backdropcms.org, so that it can become available via the core Project Installer.
- Rename the README.txt file to README.md instead.
- Include a LICENSE.txt file.

I have also done a quick code review, and noticed the below obvious things:

- `version = BACKDROP_VERSION` needs to be removed from the .info file. This is reserved for Backdrop core modules/themes only.
- The entire `; Added by Backdrop CMS packaging script on 2019-05-31` section in the .info file will also need to be removed. This will be added automatically by the Backdrop packaging script each time you make a new release (once the project has been moved to https://github.com/backdrop-contrib).

There are some other things like coding standards issues, but these can be dealt with later, once the project has officially been move to Backdrop Contrib.

Please let us know if you have any questions, or if you need help 🙂

**Comment by klonos** [comment]
@Harzah2 it's been a while since we last heard from you. I will go ahead and close this issue, but please feel free to reopen if you are still interested to join the Backdrop CMS Contrib group.
