### ISSUE TITLE
Twitter module porting

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#39]
I am starting work on the Twitter module. My repository is at  https://github.com/Graham-72/twitter. It is early days yet - plenty to do.

**Comment by Graham-72** [comment]
Guidance please - looking at the Twitter module I see that in Drupal 7 it has a data table called twitter_accounts that holds the details for each Twitter account registered with the module. My question is, in Backdrop should this data remain as a table in the database or should it become a config json file (or perhaps it would need to be one for each user)? It will surely be easier if it remains in the database but does this conflict with Backdrop policy?

**Comment by quicksketch** [comment]
Hi @Graham-72! Thanks again for working on these ports.

> My question is, in Backdrop should this data remain as a table in the database or should it become a config json file (or perhaps it would need to be one for each user)?

Anything user-generated is still stored in the database. So this includes things like users themselves, nodes, comments, and anything that attaches to those things, e.g. fields, per-node settings, user pictures, etc. If you're ever in a situation where there could be "unlimited" of something, it should probably be in the database. And one more indicator, if something uses or references an auto-increment ID, that thing should probably be in the database as well, since IDs are not consistent between different environments.

So in this case, definitely the per-user Twitter information should stay in the database, since it's all 3:

- References an auto-increment ID (the user ID)
- Is populated/generated by end-users
- Could potentially be millions of entries

It's good to check though, thanks for asking. :smile:

**Comment by Graham-72** [comment]
Thanks for your very clear answer.

**Comment by quicksketch** [comment]
No problem. :smile:
