### ISSUE TITLE
Application to join: ericfg

### ISSUE THREAD

**Issue by ericfg** [backdrop-ops/contrib#390]
Hello and welcome to the contrib application process! We're happy to have you :)

Before we begin, please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
- [x] Include a LICENSE.txt file.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

When your project meets those three criteria, please continue with the following:

**The name of your module, theme, or layout**
No Current Pass

**(Optional) Post a link here to an issue in the drupal.org queue notifying Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/nocurrent_pass/issues/3106986

**OR (option #2) If you have contributed code to Backdrop core/contrib projects please provide links to pull requests/commits**

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**
[@USERNAME]

**If you have chosen option #3 above, do you agree to undergo the same review process for coders (above) should you ever decide to contribute code?**
YES

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Post a link to your new Backdrop project under your own GitHub account**
https://github.com/ericfg/nocurrent_pass

Once we have a chance to review your project, we may provide feedback that's meant to be helpful. If everything checks out, you will be invited to the @backdrop-contrib group, and will be able to transfer the project  😉

**Comment by jenlampton** [comment]
Hi @ericfg and welcome! Thanks for applying to join the Backdrop Contrib Grouo :) 

Your project currently includes a README.txt file instead of a README.md file. We have some special integrations (and formatting) here on GitHub that makes the use of markdown files preferable.

When I am porting modules from Drupal, I usually copy the [example README.md file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) along with all it's Markdown formatting into my repo. Then I copy/paste the relevant sections from my README.txt file into the README.md file. I then `git add` the .md file and `git rm` the .txt file (I find this faster than trying to reformat the previous readme.)

**Comment by jenlampton** [comment]
It also looks like you have two LICENSE files in this repo (one named `LICENSE` and one named `LICENSE.txt`). The file named `LICENSE` states the project is GNU Version 3, and the file named `LICENSE.txt` states GNU Version 2. Our preference is for Version 2, as that way we would have the ability to merge this project into core in the future. 

Would you please remove the file named `LICENSE` from this repo?

**Comment by ericfg** [comment]
thanks for the feeback, will sort it all asap

**Comment by jenlampton** [comment]
Here are a few other recommendations for changes (these are not necessary to join the contrib group. They are intended only to be helpful.)

* the line `version = 1.x-1.0` can be removed from the `.info` file. When you create a release of this module the Backdrop packaging script will add the version info from the tag you have used for the release.
* If you are only defining a single settings file in `hook_config_info()` the group line should be `'group' => t('Configuration'),` so that these settings appear in the same section as the settings for every other module. Creating a custom group is only necessary for something like Image Styles which will have a whole set of things you want to group together.
* Inline comments should start with a Capital letter.  `// searches...` should be `// Searches...` and `// hide the...` should be `// Hide the...`

Everything else looks great!

**Comment by ericfg** [comment]
I've updated everything as suggested.

**Comment by ericfg** [comment]
I tried to follow the directions at https://backdropcms.org/contribute/join/welcome to transfer the repository and got the following error:
You don’t have the permission to create public repositories on backdrop-contrib

**Comment by jenlampton** [comment]
Hi Eric, you won't have permission to transfer the repository until we add you to the contrib group. Let me review your project again to see if we can't do that today :)

**Comment by jenlampton** [comment]
Yep, the project looks great! Nice work @ericfg. Invite is on the way!
