### ISSUE TITLE
Application to join: rositis

### ISSUE THREAD

**Issue by rositis** [backdrop-ops/contrib#407]
**The name of your module, theme, or layout**
Hook Post Action

**Post a link here to an issue in the drupal.org queue notifying Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/hook_post_action/issues/3130683

**Do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
Yes

**Post a link to your new Backdrop project under your own GitHub account**
https://github.com/rositis/hook_post_action

Once we have a chance to review your project, we may provide feedback that's meant to be helpful. If everything checks out, you will be invited to the @backdrop-contrib group, and will be able to transfer the project  😉

**Comment by jenlampton** [comment]
Hello @rositis, and welcome!

There are three requirements for new/ported projects in the Backdrop Contrib group:
[x] If porting a Drupal project, Maintain the Git history from Drupal 7. See this article.
[ ] Include a README.md file that includes license and maintainer information. You can use this example.
[ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0 -- please see below).

Unfortunately, it looks like some of these requirements have not been met yet: 
* The readme file is still in the old Drupal-style pain text. When that file is translated into Markdown syntax, it will be nicely formatted into HTML for the Backdrop CMS project listing pages.
* The LICENSE file looks like it was added by the drupal.org packaging script because it is missing it's .txt file extension. (This issue can be resolved by adding the extension, you do not need to replace it with a different file)

Quick code review (optional improvements!):
* In the info file, the line `version = VERSION` can be removed. That all-caps `VERSION` is added to core `.info` files so that the version will be replaced with the appropriate core version when packaged, but is not necessary for contrib. 
* In `hook_post_action.module` all functions have docblocks, but they are all missing the friendly human-readable description as the first line. Additionally, if the function is implementing an existing hook, the param lines are not necessary (because they are already documented on the hook). When param lines are added, they should include a data type, and a human-readable definition.

For example:
```php
/**
 * @param $entity
 * @param $type
 */
function hook_post_action_entity_insert($entity, $type) {
```

Should become:
```php
/**
 * Implements hook_entity_insert().
 */
function hook_post_action_entity_insert($entity, $type) {
```

And the docblock here:
```php
/**
 * @param $entity
 * @param $type
 * @param $op
 */
function _hook_post_action_post_save($entity_info) {
```

...should become something like:
```php
/**
 * Helper function to call the new post-hooks.
 * 
 * @param Entity $entity
 *  The fully-loaded entity object.
 * @param string $type
 *  The type of entity being saved (i.e. node, user, comment).
 * @param string $op
 *  The operating that's taking place (insert/update/delete)
 */
function _hook_post_action_post_save($entity_info) {
```

**Comment by rositis** [comment]
Thanks for the good feedback, @jenlampton!

I have made the appropriate changes and committed them to Github. Please review and let me know if there is any other changes I should make.

**Comment by jenlampton** [comment]
Thanks @rositis these changes look great!  
I'm sending you an invite to join the contrib group now.  :)

If you have time, it would also be great if you could format the README.md more [like this example file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).

In particular, we need to know who the current maintainer is (you?) so that the security team knows which GitHub user they should work with, if there should ever be an issue. 
The module author, and the name of the person who did the port can be included in the "Credits" section at the bottom.

It would also be great if the module contained an `@file` docblock. For modules that don't already have one, I often use the description from the `.info` file, like so:

```php
/**
 * @file
 * Provides additional hooks to perform actions after an entity is inserted, 
 * updated, or deleted in the database.
 */
```

**Comment by rositis** [comment]
@jenlampton I've added the `@file` statement and reworked the README formatting as you've suggested. I've also now transfered the project to backdrop-contrib!

**Comment by jenlampton** [comment]
Fantastic!  Welcome, and feel free to use this issue queue for any general questions :)
