### ISSUE TITLE
Application to join: earlyburg

### ISSUE THREAD

**Issue by earlyburg** [backdrop-ops/contrib#417]
Hello and welcome to the contrib application process! We're happy to have you :)

Before we begin, please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
- [x] Include a LICENSE.txt file.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

When your project meets those three criteria, please continue with the following:

**The name of your module, theme, or layout**
Search API Pages

**(Optional) Post a link here to an issue in the drupal.org queue notifying Drupal 7 maintainers that you are working on a Backdrop port of their project**
did not actually do that - my apologies

**OR (option #2) If you have contributed code to Backdrop core/contrib projects please provide links to pull requests/commits**
https://github.com/backdrop-contrib/entity_plus/pull/31

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**
N/A

**If you have chosen option #3 above, do you agree to undergo the same review process for coders (above) should you ever decide to contribute code?**
N/A

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Post a link to your new Backdrop project under your own GitHub account**
https://github.com/earlyburg/search_api_pages

also I have this port of my Drupal 7 module found here :
https://www.drupal.org/project/random_frontpage
https://github.com/earlyburg/RandomFrontpage

Once we have a chance to review your project, we may provide feedback that's meant to be helpful. If everything checks out, you will be invited to the @backdrop-contrib group, and will be able to transfer the project  😉

**Comment by klonos** [comment]
Sorry for the late response here @earlyburg 😓 ...I'll have a look at this issue in about 1hr, after our weekly dev meeting.

**Comment by jenlampton** [comment]
Hi @earlyburg and thank you for offering to join the contrib group. Thank you for the port of the search_api_pages module, and for all the work you've done on random_frontpage :)

I took a look at your port of search_api_pages, and it looks really good!  There's only one item that needs your attention:

> Include a `README.md` file containing license and maintainer information.

This project includes a `README.txt` file, likely from Drupal. Would you please `git mv` that file so that it's name is `README.md`?  (We're using this markdown file to pull the README from GitHub and automatically create a project node on backdropcms.org)

Additionally, you'll also need to add a `MAINTAINERS` section with your name, if you would like to be the maintainer for this project.

Please note that other than the `README.md` changes above, the rest of this code review is only intended to be helpful, and **none of this is required for joining the contrib group!** The only reason we do thorough reviews is to point out some differences between Backdrop and Drupal that you may not already be aware of :)

--- Code review (changes optional) below this line ---

For bonus points, you could adjust the whole README to match the [Backdrop standard](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) which also includes sections on how to report issues, where to find documentation, and credits for work done on the Drupal version. It also has a handy link on how to install modules, so that doesn't need to be repeated :) (I usually start from this example and then cut/paste in the relevant info form the old `README.txt` from Drupal)

Thank you for maintaining the Git history from Drupal :) It looks like all the [tags/releases from Drupal]( https://github.com/earlyburg/search_api_pages/releases) are still present.  I use this command to remove the Drupal tags from my Backdrop repos: `git tag | xargs git tag -d`

You should remove the `version = 1.x-1.x` line from the info file. That information will be added automatically by the packaging script every time you create a release on GitHub.

In Backdrop, we usually place all theme and preprocess functions in a file named `whatever.theme.inc` so that it's easier for front-end developers to find them. (It will also make everything load slightly faster if we can separate code that's needed for special purposes into files that are only loaded for those purposes.) These functions could be moved from `search_api_page.module` and `search_api_page.pages.inc` to a new `.theme.inc` file. The implementation in `hook_theme` (in `search_api_page.module`) would also need to be updated to point to this new file.

To remove the process layer in Backdrop, we have moved the conversion of classes arrays into strings using `implode()` up a layer, directly into template files, so that people using the templates will not need to use a preprocessor to manipulate the classes array. In this module, I noticed that `implode()` has been moved down a layer, into `template_preprocess_search_api_page_results()` instead of up to `search-api-page-results.tpl.php`.  

It looks like `hook_config_info()` is defined, and a there is a default `search_api_pages.settings.json` file (nice!) but the value within `search_api_page_search_api_page_disabled_` isn't used anywhere. Is that intended?

I also usually like to include a `"_module": "search_api_pages",` line in the default config, so that we know what module this config file came from (this is more important when there is more than one config file, or it is not as clearly named, but may be used in the future for better error messages with config sync issues).

If it were me, I would move `includes/searchpage_entity.inc` to `search_api_page.entity.inc` so that there was no need for the `includes` directory. The reference in `hook_autoload_info()` would also need to be updated to match. The `.entity.inc` file name pattern is how core handles it's entity definitions, and we're hoping contrib will follow :)

I noticed that this module is listed as depending on `entity_plus`. That module shouldn't be necessary as everything from `entity_api` should be possible using Backdrop core alone -- if you have found something that you can't do using Backdrop core - we'd love to hear about it (so that we can fix Backdrop core). If you haven't already, please consider chiming in on existing core issues, or create new ones as needed.

@klonos sorry if you had also started on a code review, but I really wanted to check out `search_api_pages`!

**Comment by earlyburg** [comment]
@jenlampton , @klonos 
Thank you Jen, I appreciate your taking time to go over my code, and pointing out improvements. I have gotten everything above the (optional code review changes) line done and committed. I (should ) have the rest of the suggestions done by the end of this week. Again, thanks. I appreciate it.

**Comment by earlyburg** [comment]
_In Backdrop, we usually place all theme and preprocess functions in a file named whatever.theme.inc so that it's easier for front-end developers to find them. (It will also make everything load slightly faster if we can separate code that's needed for special purposes into files that are only loaded for those purposes.) These functions could be moved from search_api_page.module and search_api_page.pages.inc to a new .theme.inc file. The implementation in hook_theme (in search_api_page.module) would also need to be updated to point to this new file._
This has been done.

_To remove the process layer in Backdrop, we have moved the conversion of classes arrays into strings using implode() up a layer, directly into template files, so that people using the templates will not need to use a preprocessor to manipulate the classes array. In this module, I noticed that implode() has been moved down a layer, into template_preprocess_search_api_page_results() instead of up to search-api-page-results.tpl.php._
This has also been done.

_If it were me, I would move includes/searchpage_entity.inc to search_api_page.entity.inc so that there was no need for the includes directory. The reference in hook_autoload_info() would also need to be updated to match. The .entity.inc file name pattern is how core handles it's entity definitions, and we're hoping contrib will follow :)_
This has been done

_I noticed that this module is listed as depending on entity_plus. That module shouldn't be necessary as everything from entity_api should be possible using Backdrop core alone -- if you have found something that you can't do using Backdrop core - we'd love to hear about it (so that we can fix Backdrop core). If you haven't already, please consider chiming in on existing core issues, or create new ones as needed._
Namely - the exportable entity class that is used in the official port of search_api found here:
https://github.com/backdrop-contrib/search_api
since my module uses a function from that module to access a search_api index object class, my module must also have the ability to handle it. There are a few other issues with the Search API Suite that I had been communicating about with docwilmot (https://github.com/backdrop-contrib/search_api/commits?author=docwilmot) that pertain to legacy code that reference constants declared in D7 Entity module that are not used in Backdrop core Entity module. Not insurmountable, we just have to figure out if they are useful.

_It looks like hook_config_info() is defined, and a there is a default search_api_pages.settings.json file (nice!) but the value within search_api_page_search_api_page_disabled_ isn't used anywhere. Is that intended?_
This config is left over from a plugin that was defined for the D7 Ctools page manager. I have determined that this functionality was focused on D7 panels, so that will require further work from me to see if it is usefull.

Thanks I appreciate it.

**Comment by jenlampton** [comment]
@earlyburg the readme looks great!  I have invited you to join the contrib group, please check your email for an invitation :) 

Thank you for also addressing some of the other issues, and thanks for helping us sort out the entity API issues!  We're lucky to have you as part of the team :)
