### ISSUE TITLE
Application to join: bugfolder

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#429]
Hello and welcome to the contrib application process! We're happy to have you :)

Before we begin, please note these 3 requirements for new contrib projects:

- [X] Include a README.md file containing license and maintainer information.
- [X] Include a LICENSE.txt file.
- [X] If porting a Drupal 7 project, Maintain the Git history from Drupal.

When your project meets those three criteria, please continue with the following:

**The name of your module, theme, or layout**
Rules Once per Day

**(Optional) Post a link here to an issue in the drupal.org queue notifying Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/rules_onceperday/issues/3169326

**OR (option #2) If you have contributed code to Backdrop core/contrib projects please provide links to pull requests/commits**

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**
[@USERNAME]

**If you have chosen option #3 above, do you agree to undergo the same review process for coders (above) should you ever decide to contribute code?**
YES/no

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Post a link to your new Backdrop project under your own GitHub account**
https://github.com/bugfolder/rules_onceperday

Once we have a chance to review your project, we may provide feedback that's meant to be helpful. If everything checks out, you will be invited to the @backdrop-contrib group, and will be able to transfer the project  😉

**Comment by jenlampton** [comment]
hi @bugfolder and thanks for applying to join the backdrop-contrib gruop, we're happy to have you :)

- [X] Include a README.md file containing license and maintainer information.
- [X] Include a LICENSE.txt file.
- [X] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Since you have met all 3 of our requirements, I have sent you an invitation to join the contrib group!  You should have an email in your inbox :) 

Feel free to transfer the repository into the backdrop-contrib group at any time (ask here if you have questions).

---

I'm also going to do a quick code review, but everything below here is a suggestion, and is only meant to be helpful.

* There is still one call to `variable_del()` in `rules_onceperday_reset()`. Since this value is relevant only for the current site, it would probably be better if `rules_onceperday_last` were stored in the state system. That would mean `variable_del()` here becomes [`state_del()`](https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_del/1) instead. 
* Similarly, all other references to `rules_onceperday_last` should also be updated using `state_set()` and `sate_get()`.
* The only value in `config/rules_onceperday.settings.json` is `last`, but I don't think this is used anywhere. (Maybe it was meant to be `rules_onceperday_last`?)
* Any settings that aren't in the state system should have their default values added to `config/rules_onceperday.settings.json` (if there aren't any, this can be removed, and so can hook_config_info()`.
* (If you are keeping this function...) In `hook_config_info()` if you are only providing a single settings file for your module, the `group` should be `t('Configuration'),` and the `label` should contain the name of the module. That way this settings file will show up with all the others at `admin/config/development/configuration/single/export` when you select `Configuration` as the option. See the [second example in the API docs](https://api.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_info/1) for reference :)
* If you want, the blank lines at the top of files can be removed. 
* `example_once_per_week.inc` is the only file in `default_rules` that's still `.inc` instead of `.json`

That's it!  Thanks for your work on this module :)

**Comment by bugfolder** [comment]
Thanks very much for the admission and for the suggestions. This is my first Backdrop port, so I'm still learning. (I have a site with 15 not-yet-ported contrib modules, so I'll likely be attempting more in the coming months.)

**Comment by jenlampton** [comment]
> Thanks very much for the admission and for the suggestions.

It's my pleasure :) 

> This is my first Backdrop port, so I'm still learning.

That's why we're here to help :)

Now that you're a member of the backdrop-contrib group, you won't need to post here for your future projects. But, if you ever think you might benefit from a code review, you are still welcome to post here to ask. :)
