### ISSUE TITLE
Application to join: djzwerg

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#438]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [ ] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
ZURB TwentyTwenty

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/zurb_twentytwenty/issues/3171892

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/djzwerg/zurb_twentytwenty

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment]
Hi @djzwerg and welcome to Backdrop contrib!  Thanks so much for applying to be part of our team :)

I'm going to do a quick review of the https://github.com/djzwerg/zurb_twentytwenty repo.

> Include a README.md file containing license and maintainer information.

The maintainer section doesn't include your name. Would you like to be a maintainer for this project? 

Maintaining a Backdrop project is less responsibility than maintaining a Drupal project since we have two teams who are also available to help with your project. The Security team will help you manage Security releases, should they ever be necessary, and the Bug Squad can help merge bug fixes that have been approved by the larger community. 

> Include a LICENSE.txt 

Would you please rename the file in this repo from `LICENSE` to `LICENSE.txt`?

> Maintain the Git history from Drupal.

I checked the [commit history](https://github.com/djzwerg/zurb_twentytwenty/commits/master) in the current repo, but it does not contain [the two commits](https://git.drupalcode.org/project/zurb_twentytwenty/-/commits/7.x-1.x) from the Drupal project. 

I've posted some notes on how to get the git history in [this comment](https://github.com/backdrop-ops/contrib/issues/412#issuecomment-657362796).  I hope you find that helpful :)

**Comment by djzwerg** [comment]
Hi @jenlampton thanks for your replay and your hints!

> Would you like to be a maintainer for this project?
No, I won't because I'm not really familiar with coding. I wish I would but I'm not for now.

> Would you please rename the file in this repo from LICENSE to LICENSE.txt?
I've done at https://github.com/djzwerg/zurb_twentytwenty/commit/971e9ed3429b4aaaf498a4d235d40102c313f0d7.

> I checked the commit history in the current repo, but it does not contain the two commits from the Drupal project.
I don't understand why that has happen. I'm going to reproduce your steps but that won't happen until next week.

**Comment by jenlampton** [comment]
> No, I won't because I'm not really familiar with coding. I wish I would but I'm not for now.

Okay, well if you change your mind there is a whole community of coders here who would be happy to help you through it :) 

> I've done at djzwerg/zurb_twentytwenty@971e9ed.

Thanks!

> I'm going to reproduce your steps but that won't happen until next week.

No problem, just post here when you're ready or if you need more help :)

**Comment by jenlampton** [comment]
@djzwerg I thought there must be an easier way to get back the Git history, so I ran an experiment using djzwerg/zurb_twentytwenty, and it worked! 

I filed a Pull request against your project, so all you should need to do to get the history back is [merge it](https://github.com/djzwerg/zurb_twentytwenty/pull/1) :)

[I wrote a blog post](https://www.jenlampton.com/blog/how-add-back-git-history-when-you-forgot-clone) on how I did it, since it is pretty common that the Git history is not included, and I want to have a good resource for the next time :)

**Comment by oadaeh** [comment]
Hi there. Is there still interest in moving forward with this, and if so, what are the next steps?

**Comment by djzwerg** [comment]
Hi @oadaeh. Because of the duplicate I think this won't make sense. What do you think?

**Comment by oadaeh** [comment]
Are you still interested in joining the Backdrop contrib team? If so, then let's pick a different project with which to move forward.

**Comment by djzwerg** [comment]
Yes, I'm interested in but because of Covid-19 it takes a bit of time. I'm looking for simple modules to learn converting (I'm not a programmer).Am 08.11.2020 15:42 schrieb Jason Flatt <notifications@github.com>:
Are you still interested in joining the Backdrop contrib team? If so, then let's pick a different project with which to move forward.

**Comment by oadaeh** [comment]
Okay, then we'll just leave this as is for now, and you can update it when you have time (unless @jenlampton wants to do something different).

**Comment by jenlampton** [comment]
> Are you still interested in joining the Backdrop contrib team? If so, then let's pick a different project with which to move forward.

What about becoming a co-maintainer for zurb_twentytwenty?

**Comment by djzwerg** [comment]
> What about becoming a co-maintainer for zurb_twentytwenty?

Well I'll have to learn coding to do so. Maybe later...?

**Comment by jenlampton** [comment]
Whenever you're ready :)
