### ISSUE TITLE
Contrib projects are packaged with their version number appended

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#44]
When one downloads and then extracts modules from d,org, the .zip or .tar.gz files contain a directory with the name of the project and that's it. Backdrop contrib projects are currently packaged with a version number appended to them (```email-1.x-1.x``` for example).

So, extracting subsequent versions in the modules directory could in theory end up with multiple versions of the same module(s). Alternatively, we add an additional step compared to the Drupal workflow (having to rename the resulting folder in order to remove the version number at the end).

**Comment by jenlampton** [comment]
I noticed that too, and it's certainly not ideal.  I'm not sure how much control we have over GitHub's packaging, but we could try to remove the version from the additional package we attach.

**Comment by quicksketch** [comment]
There isn't anything we can do about the "latest dev release" zip files that GitHub provides. That's what you get when you hit this button:

![screenshot25](https://cloud.githubusercontent.com/assets/100206/9895909/7f06908c-5bf2-11e5-98d2-065af3ca29ac.png)

However, if you download a release, either from GitHub's release pages or from BackdropCMS.org, then the name of the zip file is indeed just the module name:

![screenshot26](https://cloud.githubusercontent.com/assets/100206/9895930/aa6d6714-5bf2-11e5-8296-00be10f98cf6.png)

Our packager names the zip files so that they come out this way, matching the expected name. This also applies to all the archives recommended by Update module (as they come from the same place). But there really isn't anything we can do about the automatic archives made by GitHub.

**Comment by quicksketch** [comment]
Oh, this was filed all the way back in January, before we had the packager. I suppose we can consider this fixed. :smile:
