### ISSUE TITLE
Klonos: permission to contribute.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#45]
As per the discussion over at https://github.com/backdrop-ops/backdropcms.org/issues/44, can I please have access rights?

For more info about me, please see my [d.org profile](https://www.drupal.org/user/567014/)

Thanx in advance.

**Comment by quicksketch** [comment]
Thanks @klonos! LOL. Man, sorry this has taken a while. @jenlampton has recommended you, per https://github.com/backdrop-ops/backdropcms.org/issues/44#issuecomment-72330432.

We haven't 100% figured out the wording for non-developer contributors, since a lot of this agreement doesn't apply, but we'll have you read it anyway. As Jen noted in the above issue, if you'd like to add modules to the repository, we'd like to go through a similar spot-check that we've been doing with other applicants. Thanks!

So for the record, would you agree to the following?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by klonos** [comment]
Thanx Nate. Yes, I agree to all the above.

**Comment by quicksketch** [comment]
Excellent. Thanks and sorry for the delay. Invite on its way.

**Comment by klonos** [comment]
No worries (that's me being Down-Under for too long). Thank you guys.

**Comment by klonos** [comment]
...by the way, I cannot edit issue summaries in https://github.com/backdrop-ops/contrib/issues. Is it possible to grant me that permission too or am I asking too much?

**Comment by quicksketch** [comment]
Hi @klonos, let's reopen this issue.

So permissions to `backdrop-contrib` aren't the same as the `backdrop-ops` organization. Right now I don't think we'd want to attempt to maintain permissions to both organizations separately.

*However*, what we really could use is another person reviewing and accepting new applications. I think you'd be a great candidate and it would help alleviate a contribution bottleneck. Would you be interested in joining as a Owner of the contrib group? Then we can just add you as an author here, since you'd obviously need the permissions to modify the application issues.

**Comment by klonos** [comment]
Well, yes Nate. I'd be honored!

...a couple of things though:

1. I'm afraid that my time is limited at the moment. I work 12:00 to 12:00 pm and in the mornings I do computer repairs. My weekends are sort of free till March when college starts again. So, my point is that so long as I'm not the only person doing the reviewing/applications it'd be ok.

2. I can only do reviews based for example on d.org profiles, contributed modules etc - I can't help with actual code reviews. So I guess I'm suitable for approving non-coding contributors like myself.

3. I'd need guidance on the approval workflow. I guess I can use the Backdrop Contributed Project Agreement as a template prompting applicants to agree and more or less that'd be it. Right?

If the above are acceptable, than I'd be glad to join and help as much as I can. Let me know and once again, *really honored*!!

**Comment by quicksketch** [comment]
Excellent! Don't worry about the time management. The only way this is going to work long-term is if there are enough people in all areas to share the responsibility.

Our reviews at this point are not technical at all. We only "spot-check" for 3 things (2 of which are actually part of the agreement):

- Include a README.md that includes the list of maintainers and license info.
- Include a LICENSE.txt for GPL v2.
- Maintain the project history from Drupal 7 if it is a port.

After those 3 are met, copy/paste the agreement for the record. And that's it. :)

These two applications were pretty quick and the sort of thing we hope to see:

https://github.com/backdrop-ops/contrib/issues/23
https://github.com/backdrop-ops/contrib/issues/28

We've also actually rejected one application, but it was not based on code quality. It was based on cooperation and communication breakdowns. See:

https://github.com/backdrop-ops/contrib/issues/12

Generally we want to welcome anyone we can to the project, but we just have to establish a basic understanding of the agreement and get people started in the right direction.

I've updated the list of Owners for the contrib group and updated the list of maintainers in this repo as well, so after an applicant has met those 3 requirements you can send them an invite.

https://github.com/orgs/backdrop-contrib/invitations/new
