### ISSUE TITLE
Contrib Group Membership

### ISSUE THREAD

**Issue by mkalkbrenner** [backdrop-ops/contrib#47]
I'll move the xmlrpc contrib module to the new group.

**Comment by quicksketch** [comment]
Hi @mkalkbrenner! Great to see you again.

We have a few stipulations for contrib modules, including:

- [x] Include a LICENSE.txt file.
- [ ] Include a README.md file that includes a list of maintainers and license info (see this [example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)).
- [x] Maintain the history from Drupal 7 (if possible).

I don't think it's practical to maintain the history of the xmlrpc.php file from Drupal 7, so we don't need to worry about that. Could you update the README.md to match the example? Since permissions are so lax on GitHub, we need a way to keep track of which people are "officially" maintaining a module and can push to the repository. We've also been naming our LICENSE files as LICENSE.txt. It'd be great if that could be renamed for consistency with other projects. Thanks!

**Comment by klonos** [comment]
@mkalkbrenner ping? I see you have not updated the [README.md](https://github.com/mkalkbrenner/xmlrpc/blob/master/README.md). Are you still interested in doing this?

**Comment by klonos** [comment]
Hello @mkalkbrenner 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
