### ISSUE TITLE
Porting Custom Search

### ISSUE THREAD

**Issue by jdanthinne** [backdrop-ops/contrib#48]
Hi, I'm currently porting my Custom Search module… https://github.com/jdanthinne/custom_search

**Comment by quicksketch** [comment]
Hi @jdanthinne, that's excellent!

We need to ensure a few small things before moving this project into the Backdrop contrib group.

- [ ] Include a LICENSE.txt file indicating it is GPL v2 (you can [copy this file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes a list of maintainers and license info (see this [example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)).
- [x] Maintain the history from Drupal 7 (if possible).

Normally we ask that you clone from the D7 repository, then rename the branch 7.x-1.x branch to 1.x-1.x so that all history is maintained. However, if you're the original author of this module, it's up to you if you'd like to keep this history or not. 

We don't require a full port for the module to be included, but it'd be a good idea to indicate if your module is still under development in the README.md file. If you're interested in completing the port by switching the use of `variable_get()` to the config system, I'd suggest reading the upgrading documentation at https://api.backdropcms.org/node/28621.

But a full port is *not* necessary at this point. If you can add a LICENSE.txt file and complete the README.md, that is suitable for moving the module into the group. Thanks!

**Comment by jdanthinne** [comment]
I've just included the required LICENSE.txt and README.md files.
Config system conversion is on the way (so much easier than the full D8 conversion that still makes my brain hurts btw.).
Let me know if you need something else to include the module in the contrib repository.

**Comment by quicksketch** [comment]
Perfecto! Thanks @jdanthinne. We're really excited to have your help, thanks for porting your module to Backdrop! The invite is on its way. Add at will. :smile:

**Comment by jdanthinne** [comment]
Thanks. What's the best way to move the repository to the contrib modules one?

**Comment by quicksketch** [comment]
Hi @jdanthinne! The easiest way is probably to visit your project repository, click the "Settings" tab on the right side, then transfer the repository (in the "Danger Zone"). That will allow you to move the repository to a different organization.

You could also add a new repository to the Backdrop Contrib group and then add it as a remote and push into it, but transferring is probably the easiest.

**Comment by jdanthinne** [comment]
Hi @quicksketch, I've just transferred my repository to https://github.com/backdrop-contrib/custom_search, but since then, I'm not able to push changes to it… Have I done something wrong?
Tower (the Mac app I use) says : "remote: Permission to backdrop-contrib/custom_search.git denied to jdanthinne."

**Comment by quicksketch** [comment]
Hm, @jdanthinne I checked the permissions and you should be able to push to it (and all other repos in the group actually). I'm not familiar with Tower, but I'd suggest doing a new clone of the repository and then see if you can push up to the new copy. You might also try switching between the `https://` clone URL and the `git://` URL. The https one uses a username and password, while the git one uses your SSH private key.

**Comment by jdanthinne** [comment]
Not working with git:// in Tower as well.
I've just tried with the official GitHub app, re-cloned the repository, but when I want to sync changes, I've got the same result "You may not have permission to access custom_search.".

**Comment by quicksketch** [comment]
I'm not sure this will help, but I don't have many other ideas. I'll remove you from the group and send you a new invite.

**Comment by jdanthinne** [comment]
No, it still doesn't work BUT now that you've sent me a new invite and I see that I'm joining the "Authors" group, I remember when I made the transfer from my repository to contrib-group, I was asked to transfer admin rights the the "Authors" group as well, but at the time I did not check that, in doubt… perhaps the repository itself must be updated by an admin to give rights to the Authors group? Or you can retransfer it back to me, and I retransfer it back to the group with the correct rights?
Sorry for the trouble :-(

**Comment by quicksketch** [comment]
Ah! That's the problem!! I didn't realize you could transfer the repository but not give your own group access! That's stupid.

Anyway, I re-added authors to the group. You should *finally* be able to push. Thank YOU for helping me understand this potential caveat.

**Comment by jdanthinne** [comment]
Yeah! Working fine now. All my changes pushed.
Thanks again Nathan.
