### ISSUE TITLE
Application to join: Pack & Upload

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#480]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
Pack & Upload

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/pack_upload/issues/3189907

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/djzwerg/pack_upload

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by klonos** [comment]
Thanks for porting this module over @djzwerg 🙏 

Here are a couple of suggestions:

1. Update the "Installation" section in your README.md, to say the following:
   > Install this module using the official Backdrop CMS instructions at
  https://backdropcms.org/guide/modules.
   The instructions on that page in b.org include the manual process, but also the process to install via the Project Browser (once an official release of the module becomes available). Pointing to the online resource will also make it so that if anything changes in the way modules are installed in Backdrop, you will not need to update your README; we'll update that documentation page instead, so that it applies to all modules 😉 
2. Please consider reopening https://www.drupal.org/project/pack_upload/issues/3189907 and offer the current D7 module maintainers if they would like to co-maintain the Backdrop version. We do that out fo courtesy - most of them usually say that they are not interested, but we need to do the right thing and ask 🙂 
3. You need to remove the version number from the .info file of the module: https://github.com/djzwerg/pack_upload/blob/1.x-1.x/pack_upload.info#L5 ...when you create a new release on GitHub, our automated packaging script will take care of adding the version number (based on the release/tag). I also recommend using [semantic versioning](https://semver.org/) for your releases, like 1.x-1.2.0, 1.x-1.2.1, 1.x-1.2.2 etc. See other contrib projects for example:

   - https://github.com/backdrop-contrib/metatag/releases
   - https://github.com/backdrop-contrib/matomo/releases

   For more information re versioning, please refer to https://github.com/backdrop-ops/contrib#releases

Other than those things, the project meets the 3 requirements ✔️ ✔️ ✔️, and you've agreed to the Backdrop Contributed Project Agreement ✔️, so welcome to the Backdrop Contrib group 🎉 

I've sent an invite to add you to the GitHub Contrib group:

>You've invited djzwerg to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Once you are comfortable, please feel free to move your project from your GitHub repo over to the Backdrop Contrib repo. See the "Transfer the project" section in https://backdropcms.org/contribute/join/welcome for more 🙂 ...once your project is in the Backdrop Contrib repo, creating a release on GitHub will automatically create a project node in https://backdropcms.org/modules and also a release which will be available to install from the Project Installer in every Backdrop site.

Glad to have you join the gang! ❤️

**Comment by djzwerg** [comment]
@klonos thanks a lot! Sorry I've read you answer after transferring the module to backdrop-contrib. But I think I can make the changes anyway.

**Comment by jenlampton** [comment]
Thanks for making those changes @djzwerg! Since you are part of the contrib group now, I'm going to close this issue, but feel free to continue to comment here with @klonos about the latest changes if you like.
