### ISSUE TITLE
Maintainer change request

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#481]
Thank you for adopting an abandoned Backdrop project. 

Please note the procedure to add new maintainers:

1. If you haven't already, please join the Backdrop Contrib group by submitting an application.~
2. File an issue in the current project's issue queue requesting to help maintain the project.
3. If written permission is granted by a current maintainer, create a PR that adds your name to the README.md file in the list of maintainers. Either you, or the current maintainer may merge the PR.
4. If the project does not have a listed maintainer, or if a current maintainer does not respond within 2 weeks, create *this issue* to take over the project. 

If you have reached step 4, above, you are in the correct place.

**Please include a link to the issue you filed for the abandoned project.**
https://github.com/backdrop-contrib/reference/issues/52

After confirming the project has been abandoned, a Backdrop Contrib administrator will add your name to the list of maintainers in that project's README.md file.  Once your name is listed in the README.md, you may act as the current maintainer.

**Comment by jenlampton** [comment]
Here's a PR to add my name to README.md: https://github.com/backdrop-contrib/reference/pull/53

**Comment by klonos** [comment]
Thanks for applying to take over @jenlampton 🙏 

Since there is no current maintainer listed in the README of that project, plus also given that you have opened https://github.com/backdrop-contrib/reference/issues/52 a couple of weeks ago, and also the fact that you are keeping the last known person to have worked on that module as a co-maintainer, I'm confident to merge that PR 👍

**Comment by klonos** [comment]
All done 😉
