### ISSUE TITLE
Application to join: [Retsell]

### ISSUE THREAD

**Issue by Retsell** [backdrop-ops/contrib#488]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
     https://github.com/Retsell/grid_field_formatter/blob/1.x-1.1/README.md
- [x] Include a LICENSE.txt file. 
      https://github.com/Retsell/grid_field_formatter/blob/1.x-1.1/LICENSE.txt
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
Grid Field Formatter

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/grid_field_formatter/issues/3092046 

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/Retsell/grid_field_formatter

**OR (option #2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**If you have chosen option #3 above, do you agree to undergo this same maintainer application process again, should you decide to contribute code in the future?**
YES/no

**Comment by jenlampton** [comment]
Hello @Retsell and welcome!

Thanks for your work on grid_field_formatter :)

I see that you have met the 3 basic requirements for joining the contrib group, so an email from GitHub is on the way!

- [x] Include a README.md file containing license and maintainer information. 
     https://github.com/Retsell/grid_field_formatter/blob/1.x-1.1/README.md
- [x] Include a LICENSE.txt file. 
      https://github.com/Retsell/grid_field_formatter/blob/1.x-1.1/LICENSE.txt
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Feel free to [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) into the backdrop-contrib group at any time (ask here if you have questions).

---

I'm also going to do a quick code review, but everything below here is a suggestion, and is only meant to be helpful.


* **Versioning**: the line `version = "1.x-1.1"` should be removed from the project's info file. The version number for your project will be added automatically by the Backdrop packaging script as you make releses, so that you won't need to remember to update this line.
* **File structure**: In Backdrop we encourage all `.tpl.php` files to be placed in a `templates` directory in the module. (The same goes for `.css` files in a `/css` directory, `.js` files in a `/js` directory, tests in a `/tests` directory, etc). This project only has one, so it's not crucial, but front-end developers will look for a `templates` directory first. 
	* The location of the template file can be defined in `hook_theme()` using the `template` property, here is an [an exmple](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_common_theme/1) of how it's done in core.
* **Adding classes and attributes**: In Drupal classes were converted from an array into a string via the process layer, which has been removed from Backdrop. In Backdrop, we make that conversion directly in the template file, so that front-end developers can have an easier time changing them. You may need to update the `.tpl.php` file so that `<div class="<?php print $classes; ?>"...` becomes `<div class="<?php print implode(' ', $classes); ?>"...` and `<?php print $attributes; ?>` becomes `<?php print backdrop_attributes($attributes); ?>` in order for your classes and attributes to print correctly.  If it's working as expected now, these may have been flattened to strings too early, and you might want to rework that code to leave them as arrays until the template file.
* **hook_config_info()**: Since this module is adding its own configuration file `grid_field_formatter.settings,json` it would be good to let Backddrop know about the file via `hook_cofig_info()`. This will install the file automatically when the module is enabled, which sets default values. 
	* A default copy of the config file should be included at `/config/grid_field_formatter.settings.json` for the system to copy on install.
* **hook_uninstall()** -- You do not need to explicitly delete your module's config file when the module is uninstalled. If the file has been identified in `hook_config_info()` it should be deleted for you automatically.
* Missing space: in `.admin.inc` there is a space missing after the comma between the two parameters in `config_get('grid_field_formatter.settings','grid_field_formatter_field_types'),`. 
* the function `grid_field_formatter_field_types_options_list()` could be moved into the `admin.inc` file for a micro-performance optimization (fhat code is only needed on the admin form).
* **README.md formatting**. The README file has some [Markdown formatting issues](https://github.com/Retsell/grid_field_formatter/blob/1.x-1.1/README.md). Since this file is automatically pulled into backdropcms.org for the project node, it would be great if this could be cleaned up.
	* We have a [standard template](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) many contrib projects use to reformat the README.txt file from the Drupal project. This might help with some of the Markdown syntax or indentation issues?
* **Blank lines after `<?php`**: You can remove the extra linebreak after `<?php` if you want -- these were required in Drupal because of the previous CVS version control system, but are not needed anymore.

**Comment by jenlampton** [comment]
@Retsell I'm going to close this issue because you should have received your invite already, but feel free to re-open it if you have any questions :)
