### ISSUE TITLE
Application to join: JSitter

### ISSUE THREAD

**Issue by JSitter** [backdrop-ops/contrib#499]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] N/A If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
JWT

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/jsitter/jwt

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment]
Hello @JSitter and thank you for your application, we're happy to have you :)

If you can add a "Maintainers" section to the README.md file, I would be happy to send out an invitation to have you join the Backdrop Contrib group! 

If it's helpful, you can use [the example file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md)

**Comment by JSitter** [comment]
Thanks, I've updated README.md with the requested section.

**Comment by jenlampton** [comment]
Fantastic, thank you! An invite is on the way :)

I have done a quick code review, and the following recommendations are suggestions only. These are intended to help make maintaining your Backdrop site easier but feel free to ignore them if you prefer.

In the `.info` file:
* The line `version = 1.0-beta` should be removed. Version information will be added by the Backdrop packaging script (based on the Git tag) every time a release of the project is created. -- this should make it easier to maintain because then you don't need to remember to update list line with every release!

In the `.install` file
* Looks like there's still a `dpm()` debug message in here :)
* Backdrop coding standards call for indentation being 2 spaces instead of 4. This makes room for mode code on each line :) Plus, if all contributors use the same coding standards then our git diff's will be easier to read and review since they won't include whitespace differences.
* the `@file` docblock is missing (no biggie, just noticed it)

In the `.module` file
* Missing docblocks on `encode_jwt()`, `_jwt_encode_signature()`, `validate_jwt()`, and `jwt_decode()`.
* All Sentences in docblocks should end in a period. All hook names should be followed by parens. so, `Implements hook_permissions` should be `Implements hook_permission().` Permission singular, parens, and period.
* Indentation should be 2 spaces instead of 4. 
* the `@file` docblock is missing here too.

I'm going to close this issue since you are now a maintainer, but feel free to continue to comment here if you have questions about moving your project to the contrib group, or anything else!

**Comment by JSitter** [comment]
Thanks for the suggestions! I've updated the project with everything from your code review.

**Comment by jenlampton** [comment]
Wow, that was fast!
