### ISSUE TITLE
Twitter and OAuth ports

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#52]
These are, I believe, largely complete and functional.

The OAuth repo is now backdrop-contrib/oauth.

The Twitter repo is Graham-72/twitter. There are at least four problems still needing attention
1) The admin page for twitter-signin is not showing the images for the four button options. The Drupal module has line 73 in twitter-signin.module "return l(theme('image', array('path' => $img, 'alt' => t('Sign in with Twitter'))), 'twitter/redirect', array('html' => TRUE));" and this call to theme() doesn't seem to work in Backdrop
2) There is something wrong on the admin page of twitter-post where I get the warning "Invalid argument supplied for foreach() in form_type_checkboxes_value() (line 2348 ..../backdrop/core/includes/form.inc). It does the same thing in Drupal so it is not a backdrop related problem
3) The text filter for Twitter names is not working, though the hashtag one is.
4) I need to be able to set a system advanced action 'Post a message to Twitter' but I think this must need additions to the Backdrop actions module in core.

I shall carry on trying to get these problems resolved but comments and suggestions are most welcome. I am going to have a look at porting the Rules module, which I have found to be more useful than Actions.

**Comment by quicksketch** [comment]
Yay, that sounds great @Graham-72!

The only one I know an immediate solution to is 1), where the parameters to theme_image changed. Instead of `path`, you now have to use `uri`. We're considering putting back in a backwards-compatibility fix there, since it's not actually a URI that you need to use all the time.

**Comment by Graham-72** [comment]
Thanks @quicksketch, that has solved 1)

**Comment by Graham-72** [comment]
2) now seems to have been resolved
3) was caused by my typing mistake - now corrected.
I have now forked my repository to backdrop-contributions/twitter - I hope this is in order.

**Comment by quicksketch** [comment]
>  I have now forked my repository to backdrop-contrib/twitter - I hope this is in order.

Hi @Graham-72. Putting a fork into the contrib group may cause problems, because whenever someone forks a fork, GitHub files a pull request against the *original* repository. So to help facilitate cooperation within the backdrop-contrib group, it's preferable to *transfer* the original repository rather than fork it into the group. Could you remove the fork, then use the transfer option under the original repository settings to move it?

**Comment by Graham-72** [comment]
Thanks @quicksketch - so that is how it should be done! Twitter is now in backdrop-contrib.

**Comment by quicksketch** [comment]
Excellent thanks @Graham-72!
