### ISSUE TITLE
Application to join: joelsteidl (sendgrid_integration module)

### ISSUE THREAD

**Issue by joelsteidl** [backdrop-ops/contrib#540]
## Please note these 3 requirements for new contrib projects:

- [X] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [X] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [X] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:
Module: SendGrid Integration

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/sendgrid_integration/issues/3220145

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/joelsteidl/SendGrid-Integration

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

Note, there is a submodule SendGrid Integration Reports that is part of the project and it probably needs additional work.

**Comment by joelsteidl** [comment]
Also, I dropped a comment here https://github.com/backdrop-ops/contrib/issues/461

**Comment by jenlampton** [comment]
Thanks for working on the sendgrid_integration module @joelsteidl!

** I see that you have met the 3 requirements for joining the contrib group, so an email from GitHub is on the way!** 

- [X] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [X] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [X] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Feel free to [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) into the backdrop-contrib group at any time (ask here if you have questions).

---

I'm also going to do a quick code review, but items below are suggestions. Take or leave them as you see fit! We do this review specifically looking for things that may be done differently between Backdrop and Drupal. We hope that this review might help with the transition for those new to Backdrop :)

* Repository name: The name of the repository should match the machine name of the module, so `SendGrid-Integration` should be changed to `sendgrid_integration`.
* Test dependencies should be defined in the tests themselves, so the line `test_dependencies[] = maillog` can be removed from the `.info` file. Since this is a different module entirely, it might be helpful to list this as a dependency in the README.md also.
* The `hook_help` Implementation can be removed, there is no help module in Backdrop.
* Array syntax still needs to be compatible with PHP 5.4 until Backdrop 2.x, so `[]` needs to be replaced with `array()`.
* The function `config_get()` does not include a default value like `variable_get()` did, instead defaults are set in the `.json` file in `sendgrid_integration/config`. (see line 42 of `sendgrid_integration.install` for default that should be removed)
* Config keys don't need to be namespaced to begin with the module name `sendgrid_` since they will be saved in a `.json` file that contains the module name. (Many people like to leave the namespaced versions in anyway)
* In `hook_uninstall()` it's not necessary to delete the module's own config files. As long as a module properly implements `hook_config_info()` that cleanup will happen automatucally.  If, however, a module writes to config files provided by other modules, it should remove its own values from those other files.
* The `sendgrid_integration.tests.info` should be moved inside the `tests` directory. (and then `tests/` should be removed from the `file` definitions, within.)
* All PHP files no longer need the line of whitespace following the opening `<?php` tag.
* Everything else looks great!

Up for consideration:

**It would be safest not to store any API keys in configuration.**  This wasn't an issue in Drupal because all these variables were stored in the database, and it is assumed that the database is a safe place to keep private values like API keys. For Backdrop, it's not safe to assume the same about config, because many people commit their configuration files to VCS. 

Alternatives include the state system via `state_get()` and `stage_set()` (which is still stored in the database) or via settings (from `settings.php`), or a mix of storage locations. I've also seen configuration used, but that value overridden if it was also provided via `settings.php`. I think this is my favorite approach because then the module will still work completely from the user interface, but also provides a more secure alternative. If you do decide to go this route, it is nice to add something in the description text alerting people to the fact that their API keys will be saved in configuration, and recommending that they use `settings.php` for a more secure alternative.

[Here's an example of using settings from the GitHubAPI module](https://github.com/backdrop-contrib/githubapi/blob/master/githubapi.admin.inc#L13)


Also, thank you sparking these idea for core improvements! 
* https://github.com/backdrop/backdrop-issues/issues/5136
* https://github.com/backdrop/backdrop-issues/issues/5135

**Comment by oadaeh** [comment]
@joelsteidl, you should change the name of the project from "SendGrid-Integration" to "sendgrid_integration", so that it matches the name of Drupal 7 project it is ported from.

**Comment by jenlampton** [comment]
That was the first bullet in the list above :)

**Comment by oadaeh** [comment]
Oops! I guess I shouldn't comment when I'm in a hurry.

**Comment by joelsteidl** [comment]
Getting back to our big D7 to Backdrop port! Thanks for the feedback. I addressed much of the feedback. Tests will need to be adjusted.
