### ISSUE TITLE
Application to join: jayelless (membership_entity module)

### ISSUE THREAD

**Issue by jayelless** [backdrop-ops/contrib#545]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
Membership Entity

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/membership_entity/issues/3223098

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/jayelless/membership_entity

**OR (option #2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment]
Hello @jayelless and welcome! Thank you so much for working on the membership_entity module :) 

Since the three requirements for a contrib project have been met...

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

...and you have agreed to the Backdrop Contributed Project Agreement:

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

An invitation to join the Backdrop Contrib group is on the way!

**Comment by jenlampton** [comment]
I'm also going to do a quick code review, but items in this comment are only suggestions, take or leave them as you see fit. :) We do this review specifically looking for things that may be done differently between Backdrop and Drupal in the hopes that this information might help with the transition for those new to Backdrop :)

* README.md description - The contents of the README.md file is parsed, and used to create the project node on backdropcms.org when the project gets it's first stable release. Because the text from this file is used as the node body and summary, it should begin with the name of the project followed by a description (which will appear in the teaser) and not a table of contents. An [example README file](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) is provided in this repo, for reference. 
* README.md maintainers - A Backdrop project's maintainers are determined by those listed in the readme file. There are no maintainers in this readme file yet. (If you are not interested in maintaining this project, you should include "Seeking maintainers" to indicate that this project is available for adoption. It will then be "maintained" by anyone submitting PRs, and the Backdrop bug squad, who can commit them once they are marked RTBC.)
* Theme files - In Backdrop we encourage maintainers to place `.tpl.php` files into a directory named `templates` to make it easier for front-end developers (in the hopes that they will be located in the same place for every project). If the location of this file is changed, the `template` line in `hook_theme()` would also need to be updated to include `templates\` at the beginning.
* Similarly, test files like `membership_entity.test` are usually tucked into a `tests/` directory to keep them out of the way, along with the `.tests.info` file. 
* Tests info file missing - the contents of the `getInfo()` methods on the tests should be copied into a `membership_entity.tests.info` file, along with the location of the test. See the [link module example](https://docs.backdropcms.org/api/backdrop/core%21modules%21link%21tests%21link.tests.info/1). By moving this information out of the classes themselves, it allows us to build the test page without loading all the test classes, most of which may not be used in a given test run. (it also allows us to use a static class map instead of a class registry that could be corrupted -- much like our shiny new `hook_autoload_info()`).
* Include files containing PHP classes like `membership_entity.info.inc`, `membership_entity.controller.inc`, and `membership_entity.inc` are usually moved into an `includes/` directory in the module, leaving all procedural PHP files containing hooks or helper functions directly in the module root. 
* All PHP files no longer need the line of whitespace following the opening <?php tag :)
* In hook_uninstall() it's not necessary to delete the module's own config files, or specific values from those files. As long as a module properly implements `hook_config_info()` that cleanup will happen automatically. If, however, a module writes to config files provided by other modules, it should remove its own values from those other files.
* Config keys don't need to be namespaced to begin with the module name `membership_entity_` since they will be saved in a `.json` file that contains the module name. (But many people like to leave the namespaced versions in anyway)
* The `hook_help()` Implementation can be removed, there is no help module in Backdrop.

This module is looking great, nice job with the port!

**Comment by klonos** [comment]
https://github.com/backdrop-contrib/membership_entity is now in Contrib and has a release.

@jayelless closing this issue here, but please feel free to reopen if you happen to need any help.
