### ISSUE TITLE
Application to join: Allsite (new projects: content_limiter, dark_seven)

### ISSUE THREAD

**Issue by allsite** [backdrop-ops/contrib#547]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] ~If porting a Drupal 7 project, Maintain the Git history from Drupal.~

## Please provide the following information:

**The name of your module, theme, or layout**

content_limiter
dark_seven

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/allsite/content_limiter

**Comment by jenlampton** [comment]
Hello @allsite and thank you for these contributions!  If I understand correctly, these are both projects that are new for Backdrop? (I initially thought content_limiter was a Drupal project -- but believe I am mistaken.)

Below are the 3 requirements for new contrib projects:

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [ ] Include a LICENSE.txt file. 
      Please use [this text for GPL-2.0](https://raw.githubusercontent.com/backdrop ops/contrib/master/examples/LICENSE.txt).

Because your content_limiter project does include a license file, I have gone ahead and sent you an invite to join Backdrop Contrib! Welcome! 

I do have some recommendations about the license file, however. First, the license file is currently named only `LICENSE` instead of `LICENSE.txt` and our standard is to include the file extension. 

Second, I'd also like to recommend that you switch the license to GPL-2.0, since this module does not include a 3rd party library that is licensed under GPL-3.0. Using The GPL-3.0 license will prevent your project from one day being included in Backdrop core, so we only recommend using this license when absolutely necessary.

**Comment by allsite** [comment]
Yes they are both new projects. Nothing being ported. Thanks for the invite I look forward to contributing!

**Comment by jenlampton** [comment]
I also have some feedback on your new module :)  It looks really great for your first one!! 

Items below are suggestions. Take or leave them as you see fit. We do this review specifically looking for things that may be done differently between Backdrop and Drupal, or for things that might be helpful for people new to contributing. We hope that this review might help with the transition for those new to Backdrop :)

* In the `.info` file you have defined a `package` but this is usually only used if your module comes as part of a suite of modules, and if you would like the suite all grouped together on the modules page. Since this is a stand-alone module, that line can be left off if you like. (But if you do want it grouped with the Backdrop internal System modules, you are also welcome to leave it as-is.)
* in the `.info` file, the `project` line should be removed. This line will be added by the backdrop packager once your module gets it's first official release. Though it's not problematic to have it, it's not necessary since what you put on that line will be overridden with what is automatically added.
* In the `.install` file you have two update functions numbered `1200` and `1000`. These two functions should be ordered sequentially, with the lowest number coming first.
* Additionally, the numbers for the updates should ideally be something like `1001` and `1002`, indicating that they are both for Backdrop 1.x (in the range 1000-1999) and that they are both for the same version of your module (in the range of 1000 - 1099). Jumping 100 numbers or more in the update function name usually indicates a jump from one branch of the module to another branch (allowing room for more updates on the 1.x branch, added after those added on the 2.x branch, but to be executed before).
* The update functions in the `.install` file look like they are setting or changing config values. For new people who install this module for the first time, the'll have the initial values set when the config file is copied from the `config` directory into their sites active directory, but the updates won't be run. It's safe to leave these functions in here, but it's not necessary to include them (since they won't do anything). It's likely they were necessary on your own site, but since no one else is using this module yet (assumption!) it might be cleaner to remove them entirely.
* In the `.module` file much of the code was written using spaces for indentation, but some of it was indented using tabs. All indents should be switched to spaces. (It will make pull-requests from others in the community much easier to read and understand if we are all using the same coding standards).
* For an `if` statement, our standard is to put a space after the `if` and before the following opening parenthasis. So, `if($disable_limiting` would become `if ($disable_limiting`. This also makes the code easier for other people to read.
* When we concatenate strings with the `.` operator, we also surround the dot with spaces on both sides to make the code easier for people to read. 
* Building strings that can be translated into any language is done using the `t()` function. The first parameter is the message containing markers for variable replacements, and the second is an array of the variables to insert. Something like
```
t('Content limiting detected ('.$delete_quantity.' deleted)')
```
should be replaced with 
```
t('Content limiting detected (:quantity deleted)', array(':quantity' => $delete_quantity))
```
* For watchdog messages, the use of the `t()` function is assumed, so what you pass in is the message containing markers for variable replacements, and also the array of the variables.  Something like 
```
watchdog('content', $delete_quantity.' '.$type.' nodes deleted by content limiter.');
```
should probably be replaced with 
```
$message = ':quantity :type nodes deleted by content limiter.';
$replacements = array(':quantity' => $delete_quantity, ':type' => $type);
watchdog('content_limiter', $message, $replacements);
```
* The first parameter sent to `watchdog()` is most often the name of the module, so in my example above I switched `content` to `content_limiter`. This will allow developers to filter specifically for messages coming from Content Limiter module when they are on the database log messages page.
* An implementation of `hook_form_alter()` will be executed on every form in Backdrop. Since it looks like this change should only affect node forms, this function could be replaced with an implementation of `hook_form_BASE_FORM_alter()` for better performance. I would rename the function to `content_limiter_form_node_form_alter()`.
* In the implementation of `content_limiter_form_node_type_form_alter()` it looks like we are missing some indentation. Indentation will not change how your code works, but it will make it easier for other people to contribute to your project if we can read it more easily :)
* There is a missing docblock for `content_limiter_node_type_form_submit()`. Sometimes for submit handlers all I put in the docblock is "Submit handler for X" where X is the name of the form hook. 
* There is a missing docblock for `content_limiter_node_presave()`. I would simply put "Implements hook_node_preseave()."
* in the `.admin.inc` file I noticed that the variable `$attributes` was defined but not used anywhere. This is probably best as we don't usually like to add inline styles like this to an admin form. People often use specific admin themes, and their theme would not be able to override this style if it was added inline. If you need to add styles, we recommend using the `#attached` property, and adding a stylesheet containing the CSS you need.

**Comment by allsite** [comment]
Fantastic. I was really hoping for this type of review and look forward to going over each item. Thanks for taking the time and have a great weekend!
