### ISSUE TITLE
Application to join: alvinjohnsonso

### ISSUE THREAD

**Issue by alvinjohnsonso** [backdrop-ops/contrib#555]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [X] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [X] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [X] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
tawk.to

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
No need for posting. I'm one of the maintainers of tawk.to's Drupal plugin.

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
The repo isn't under my account but under tawk.to's organization. https://github.com/tawk/tawk-backdrop

**OR (option #2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**If you have chosen option #3 above, do you agree to undergo this same maintainer application process again, should you decide to contribute code in the future?**
YES/no

**Comment by jenlampton** [comment]
Hello and thank you for your application to join Backdrop contrib!

Since you have met all 3 of the requirements for a contributed project, an invitation to join the contrib group should be landing in your inbox shortly :)

Once it arrives, feel free to [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) into the backdrop-contrib group at any time (ask here if you have questions).

I also have some feedback on code.

Items below are suggestions. Take or leave them as you see fit. We do this review specifically looking for things that may be done differently between Backdrop and Drupal, or for things that might be helpful for people new to contributing. We hope that this review might help with the transition for those new to Backdrop :)

* The `admin.inc` file is problematic. Because there is a HTML FORM tag that was not generated via the Backdrop Form API, this page will expose a security risk to any site running this module. You might have a look at [another Backdrop or Drupal 7 module](https://github.com/backdrop-contrib/project/blob/1.x-2.x/project.admin.inc) to see how admin forms can be built and processed securely. Generally speaking, if you find yourself needing to use `ob_get_contents()` in Drupal or Backdrop, you're probably missing an easier way.
* Wherever possible, strings should be wrapped in single quotes `'` instead of double quotes `"` so they will be evaluated faster (PHP will not search the string for variable replacements if it uses single quotes)
* Blank lines after the opening `<?php` tag can be removed if you want. The extra line breaks were required in Drupal because of the previous CVS version control system, but are not needed anymore.
* According to [Backdrops Coding Standards](https://docs.backdropcms.org/php-standards) indentation should be 2 spaces, instead of 4. (this increases the number of characters before the 80 character wrap)
* According to [Backdrops Coding Standards](https://docs.backdropcms.org/php-standards) the opening tag for a function should remain on the same line as the function definition. (this reduces line count)
* According to [Backdrops Coding Standards](https://docs.backdropcms.org/php-standards) the else statement should appear on the line following the closing tag for the if statement that proceeds it, not the same line. (this makes adding or removing else statements a cleaner operation because no changes will be necessary to the if statement above)

The reason we like to stick to the same coding standards across all of contrib is so that when people submit pull requests against other projects, it will be easier to review. If everyone uses the same standards, the only changes in a PR will be to the functionality, the diff will not include syntax cleanup or code adjustments for personal preferences.

**Comment by alvinjohnsonso** [comment]
Hi @jenlampton! Thanks for having the time to review the code! I'll probably address them before I proceed on transferring the repo to the backdrop-contrib group. 😁

**Comment by alvinjohnsonso** [comment]
Hi @jenlampton, tagged you in https://github.com/tawk/tawk-backdrop/pull/4. Was wondering if you could take a look at how I refactored the .admin.inc file. Checking if I utilized the theme hook correctly and how I implemented the form with the use of the Form API. 😁

**Comment by alvinjohnsonso** [comment]
Hi @jenlampton, I've transferred the repository to backdrop-contrib. Here's the URL to it 😁

https://github.com/backdrop-contrib/tawk-backdrop

**Comment by alvinjohnsonso** [comment]
Hi @jenlampton, was wondering maybe you could help me out. So I published a release and was able to see our plugin on the module listings but the README.md file isn't properly reflected there. Would you know why this is happening?

Here's the listing URL - https://backdropcms.org/project/tawk-backdrop
Here's the README file - https://github.com/backdrop-contrib/tawk-backdrop/blob/1.x-1.x/README.md

**Comment by jenlampton** [comment]
It looks like you figured it out?
https://backdropcms.org/project/tawk_to

**Comment by alvinjohnsonso** [comment]
Yup! I got help from some of the community members in Zulip. I'll probably close this issue since everything's good now 😁

Thank you so much for all the help! 😄
