### ISSUE TITLE
Examples for developers

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#58]
Porting Examples. So far done and tests passing:
- batch
- contextual_links
- cron
- dbtng
- email
- menu
- page

cache_example is done except for waiting decision on https://github.com/backdrop/backdrop-issues/issues/674 for tests to pass as is, otherwise may need to alter tests. 

Question though, on best way to upload this: should I only push the submodules I've completed, or push the whole lot (so they can still be used as examples, albeit not certain if working) and maybe disable those that aren't working (backdrop=x.x works well for that)?
What say you all?

**Comment by docwilmot** [comment]
Two other things:
I've "finished" porting block_example, but need to decide if we should be combining examples for 
- block + custom_block; or 
- block + layout; or 
- have all three separate.

And I would appreciate ideas on examples for layout please.

**Comment by quicksketch** [comment]
> cache_example is done except for waiting decision on backdrop/backdrop-issues#674 for tests to pass as is, otherwise may need to alter tests. 

Let's fix that issue. I think we've made a decision on that, we just haven't implemented it yet.

> should I only push the submodules I've completed, or push the whole lot (so they can still be used as examples, albeit not certain if working) and maybe disable those that aren't working (backdrop=x.x works well for that)?

I'd push the whole lot but leave the .info files so that the module can't be turned on. I know @cellear was working on porting some examples as well. He may be able to combine his work with yours once it's in the contrib repo.

>  I've "finished" porting block_example, but need to decide if we should be combining examples for 

I'm not sure if you mean "custom block" as in a block.module custom block (`admin/structure/block`) or an implementation of `hook_block_info/view()`. Because blocks stand pretty well on their own, I think we should have an example module for blocks that includes:

- Example of hook_block_info(), that defines multiple types of blocks:
  - Basic block.
  - Blocks with settings.
  - Blocks with contexts.
  - Block using the `class` property to define a block using a class instead of `hook_block_view()`.
- The `hook_block_view() implementation for the above.
- A class that extends the Block class for the last example.

Although it's hidden from the developer, if you don't specify a class, then `LegacyBlock` is used as the class, which in turn just calls `hook_block_view()` to act just like before. Layout itself actually only uses the class methods and doesn't know about the hooks for block view or settings.

Separately, we should have an example for the Layout API, that provides:

- Example context plugins.
- Example access plugins.

We could also get into `hook_layout_info()`, `hook_layout_style_info()`, and `hook_layout_renderer_info()`, but each of those is going to be quite uncommon. I think example contexts and (especially) access plugins are going to be the most necessary examples.

**Comment by docwilmot** [comment]
Thanks
Actually forked @cellear's work to get this done (he was informed).
Yes, was talking about custom blocks, but that's silly of course, those are just done via the UI, no need for examples. Got you.
Will push up progress so far later.

**Comment by cellear** [comment]
@docwilmot, beyond happy to have you on this. I started it a while back, but obviously haven't found time to work on it anytime recently, and I don't have your mad porting skills, either.  I think I'm probably missing messages in the (what seems to me as a ) blizzard of Backdrop-related communications.  I didn't know you forked it.  Do I get a message when that happens?

Feel free to send me a note off-channel (cellear at kiza dot com) and we can coordinate things. Happy to divide work, or to just get out of the way if you prefer.

**Comment by docwilmot** [comment]
> mad porting skills

You flatter sir. Rank amateur here; doing these ports helps me figure out how things work. I cant write docs if I dont have a clue.
When I forked, I just left a note on your backdrop_examples repo issue queue, thats all; assumed you'd get that.
I think it would be simplest, before anyone starts porting any of the submodules, just leave a note on the new https://github.com/backdrop-contrib/examples issue queue, so we dont duplicate. 
Thanks

**Comment by cellear** [comment]
Ah yes, now that I know where to look for it, I see the "i've started working on this" message in that aforementioned blizzard.  Once upon a time I had filters in Eudora that would have helped me spot that, but now, somehow, 20 years later the interfaces have actually gotten worse.  Sigh.

I'll try to get back to getting these ported. I started on it for the same reasons you mentioned: I thought it would be a good way to be really in touch with the code.  If I manage to do find the time, I'll follow your advice and open an issue in the Example Module's issue queue when I do.

**Comment by docwilmot** [comment]
Porting done.
tablesort_example tests wont pass as an assertRaw refuses to recognize what its supposed to. And actions_example is mostly new. 
Would appreciate some eyes on especially those two, but also these were mostly straight ports and may not consider Backdrop-specific additions that may be required. Consider if anything else could be added?
And finally, I'm thinking examples for config, layout, responsive_tables and views? Anything else?

**Comment by jenlampton** [comment]
Now that we have an examples module for backdrop (thanks @docwilmot !) I'm going to close this issue.
