### ISSUE TITLE
Use different repositories for themes and layouts?

### ISSUE THREAD

**Issue by arshad** [backdrop-ops/contrib#59]
It's not easy, right now, to differentiate between modules, themes and layouts in backdrop-contrib (unless you check the source or read the repo description).

Would it make sense to have http://github.com/backdrop-themes and http://github.com/backdrop-layouts for themes and layouts respectively?

What are the pros and cons?

**Comment by quicksketch** [comment]
Hi @arshad! Thanks for opening this issue. The "backdrop-contrib" listing group isn't really effective for doing any kind of searching or browsing. The 20-items per page plus the bizarre "most recent commit first" sort order makes GitHub's repository listing pretty useless.

In order to effectively search and browse our projects, we're working on building out a project browser on backdropcms.org that will automatically pull from GitHub, similar to what jQuery did with their plugins site: http://plugins.jquery.com/tag/ui/

Once that is in place, we'll be able to split themes/layouts/modules into separate categories. As for GitHub, I think keeping our repositories all in one group makes things easier from a management perspective. It's less management of permissions and more sharing of responsibility.
