### ISSUE TITLE
Request to join contrib

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-ops/contrib#594]
Hi. I would like to join the Backdrop Contrib group.

I have started a module that was based on views B grid

Here is my repo... https://github.com/albanycomputers/views_grid_repeat

I agree to the T&C's at https://github.com/backdrop-ops/contrib

Many thanks for your consideration

Steve Moorhouse

**Comment by klonos** [comment]
Thank you for putting this module together and wanting to contribute @albanycomputers and also for taking the time to apply to join the Backdrop Contrib group.

Initial feedback from a quick look I've had at the module repo:
- there's a lot of commented-out code - this better be removed if not needed, or `@todo` comments added in its place.
- there are also some coding standard violations, like extraneous spaces/lines, comments and docblocks exceeding the 80 character limit, comments on the same line as the code, comments that aren't starting with a capital letter and have no period at the end.  You may wanna have a look at https://docs.backdropcms.org/documentation/coding-and-documentation-standards for details.
- you may want to rename the `main` branch to `1.x-1.x`

I'd like to give it a spin at some point to provide further feedback.

**Comment by albanycomputers** [comment]
I've done (fingers crossed) most of the above :)

**Comment by klonos** [comment]
Still a few places that need some love:
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views-view-views-grid-repeat.tpl.php#L5 needs a dot at the end.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views-view-views-grid-repeat.tpl.php#L25 remove the space before the `;` at the end.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views-view-views-grid-repeat.tpl.php#L30 same as above.
- the whole `switch` section in https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views-view-views-grid-repeat.tpl.php#L35 has 4-space indentation instead of 2-space.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_grid_repeat.module#L4 missing period at the end.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_grid_repeat.module#L17 same as above.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_grid_repeat.module#L31 same.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_grid_repeat.module#L33 same + also that comment should have a blank line above it, and the line following it removed (as it seems to apply to the code that follows).
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L10 missing period at the end.
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L12 the code in those two docblock lines needs to either be uncommented if it serves a purpose, otherwise removed altogether.
- There's a double space instead of single space between sentences within the `t()` functions in the following lines:
  - https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L30
  - https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L37
  - https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L47
  - https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L57
- https://github.com/albanycomputers/views_grid_repeat/blob/1.x-1.x/views_plugin_style_views_grid_repeat.inc#L65 should use commas between the various units, and lose the 3 trailing dots.

**Comment by albanycomputers** [comment]
Many thanks...  Possibly all done :)

**Comment by klonos** [comment]
Even if not all done, I don't want to delay this any longer. These issues can be addressed once the module has been moved to the Backdrop Contrib space, and others can file pull requests to fix issues 😉 

Welcome to the Backdrop Contrib group @albanycomputers 🎉 

Next steps are outlined here: https://github.com/backdrop-ops/contrib#what-to-do-after-your-application-is-accepted

Please let us know if you have any issues or you need help with anything.

**Comment by albanycomputers** [comment]
Thanks @klonos

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have any questions @albanycomputers feel free to keep asking here.
