### ISSUE TITLE
Join the contributed project developer team

### ISSUE THREAD

**Issue by juanolalla** [backdrop-ops/contrib#6]
I've ported the Drupal Email Field module in https://github.com/juanolalla/email and I wish join the contributed project developer team.

**Comment by quicksketch** [comment]
Hi @juanolalla! That's amazing! We'd like to include that module in core for the 1.2.x release (see https://backdropcms.org/roadmap).

Because permissions are pretty loose on Github, we need a way to keep track of who's the maintainer(s) for which modules, so could you please add a Maintainers section to the README? The LICENSE file is great. Could you add a line about license in the README as well? You can just copy the example from https://github.com/backdrop-ops/contrib/blob/master/examples/README.md.

Other than that, it looks like a fine start! Would you officially state that you agree to the contributed author agreement?

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by juanolalla** [comment]
I've updated the README.md, and yes, I agree to the contributed author agreement.

Thanks!

**Comment by quicksketch** [comment]
Super, invite has been sent!
