### ISSUE TITLE
Creating new projects after being accepted

### ISSUE THREAD

**Issue by sillygwailo** [backdrop-ops/contrib#61]
Once a person is accepted to add projects to the contributions repository, should that person ask for a review if they wish to submit another one? Or "just do it"?

**Comment by quicksketch** [comment]
![doit](https://cloud.githubusercontent.com/assets/100206/6244376/aacf537e-b707-11e4-8f83-78cc956e832a.png)

**Comment by quicksketch** [comment]
The first review is done just to check for the basics and vet the contributor. Afterwards, add modules as you see fit. The primary purpose of the group is to aid in collaboration, so any module for which you'd like to share the responsibility, put it in the contrib group. We're working on GitHub integration as well that will will register contrib modules automatically, so that is another benefit that you'd want if you are going to be making releases.
