### ISSUE TITLE
Contrib Group Application: Michael Bagnall (ElusiveMind)

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-ops/contrib#637]
**Please indicate how you intend to help the Backdrop community by joining this group**
* Option #1: I would like to contribute a project
* Option #2: I would like to maintain a project, but have nothing to contribute at this time
* Option #3: I would like to update documentation and/or triage issue queues

Option: 1

## Based on your selection above, please provide the following information:

** Tweet Feed Module - My Contrib Module from Drupal 7 **

## (option #1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

GitHub Link To Backdrop Port: https://github.com/ElusiveMind/tweet_feed/tree/1.x-1.x

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement]
YES

**Comment by jenlampton** [comment]
Hi Micheal, thanks for the application!

I've reviewed this module and since it meets all 3 requirements:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

 **An invitation to join the Backdrop Contrib group is on the way!** Feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

I'm also going to do a quick code review with some suggestions, but that will come in a later comment.

**Comment by ElusiveMind** [comment]
A quick question on my GitHub repo for the repository. 

Should I remove all of the Drupal branches? In addition to my 1.x-1.x branch I have branches for two versions of Drupal 7 module and the Drupal 8, 9, 10 module. Plus one that is unmaintained for Drupal 6? Happy to do so but not sure of the protocol.

**Comment by jenlampton** [comment]
It's up to you!

Most projects don't have the Drupal branches but that's because they aren't
maintained by the same people for Drupal and Backdrop. Some of those that
are also have them :)

**Comment by quicksketch** [comment]
I think this can be closed then! Welcome @ElusiveMind!
