### ISSUE TITLE
Remove example code

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#657]
Suggest removing the example code (https://github.com/backdrop-ops/contrib/tree/main/examples) in favour of the new template repos (e.g. https://github.com/backdrop-contrib/module_template). They have more up-to-date code, READMEs, etc., so this saves duplicating work.

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop-ops/contrib/pull/658

**Comment by jenlampton** [comment]
These files were linked from lots of various places, and all these links have been broken since July. This hurts new contributors who are following our instructions, and need these examples. I'm reverting this commit. Please don't remove important documentation without at the very least, consulting others.
