### ISSUE TITLE
Basic Cart being ported to Backdrop.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#66]
I was pleasantly surprised today to find out that @biolithic started porting the [Basic Cart](https://www.drupal.org/project/basic_cart) module to Backdrop: https://github.com/biolithic/backdrop_basic_cart

He even has a demo site up with his progress: http://www.andymartha.com/backdrop

The reason why I am so excited about this and why I'm posting this issue here to let everyone know about it is that Ubercart and Drupal Commerce are very big projects that will take a long time before they get ported (if they ever will) to Backdrop. Since Backdrop is targeting small and mid-size sites, Basic Cart seems like a perfect match for a decent e-shop solution:

> It's ideal for small websites with only a few products or other content types being sold, for example touristic offers.

How cool will it be if we have a couple of eshop sites built on Backdrop to showcase?!!!

**Comment by biolithic** [comment]
@klonos  You're reading my mind, man!
I'm not as dumb as I look!

**Comment by klonos** [comment]
> I'm not as dumb as I look!

I wouldn't know man. I've never seen you in real life :stuck_out_tongue:

**Comment by biolithic** [comment]
It is rather odd to think on what to port for an e-shop.  Features, strongarm, custom written database reports from a module?  Not really with CMI and Views in core.  Accepting all forms of payment possible?  I'm not sure that orgs are that modern.  Give to the pet shelter in Bitcoin!  You can buy a township/county holiday ticket package in 20 currencies not your own.  Calculating shipping on that yearly group membership package?  People set up Commerce Kickstart with Context and Panels and Display Suite with CivicCRM and every conflicting payment module out there at the same time on GoDaddy and contract me out to fix it because "there's an error...somewhere".    It's cool to build your own Ebay, people can make all the modules but I don't want to be so cool sometimes trying to dig out of abstracted trouble.
I really respect Ryan S and the gang but how people use it in the real world is to install Kickstart + every module on d.o with the word commerce in it, get an error message somewhere from some dev version conflict, and say, "Drupal doesn't work."

**Comment by jenlampton** [comment]
I'm closing this issue since https://github.com/backdrop-contrib/basic_cart exists now.  Please continue all discussion about basic cart in the issue queue for that module.
