### ISSUE TITLE
Contrib application: kiamlaluno (graphicsmagick module)

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop-ops/contrib#695]
I would like to contribute a project.

**(option 1) The name of your module, theme, or layout**
GraphisMagick module

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**Post a link to your new Backdrop project under your own GitHub account (option 1)**
https://github.com/kiamlaluno/graphicsmagick

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)?**
Yes, I agree.

## Further information
I am the maintainer of the Drupal 7 module.

**Comment by klonos** [comment]
Hey @kiamlaluno 👋🏼 ...thanks for applying to join the Backdrop contrib group 🙏🏼 ❤️ 

A quick check shows that the project meets the requirements, however, I would like to point out that the namespace has changed between D7 (`gmagick`) and Backdrop (`graphicsmagick`), which may not be such a good idea. Having said this, not sure if that was intentional or not 🤔 ...the d.org project seems to have no release other than 7.x-1.x-dev, and even that's been hidden away - also, there are no issues in its queue other than the one to maintain the 8.x version. So not sure if anyone's using the Drupal module currently.

Anyway, this is something to (re)consider before transferring the project to https://github.com/backdrop-contrib and totally up to you. If you decide to keep the new namespace, perhaps add a note about it in the README.md file(?). In the meantime, I've sent an invite your way. Please let me know if it works for you (good idea to ping me about it in Zulip as well, as I'm more responsive there).

**Comment by klonos** [comment]
...sorry @kiamlaluno - I jumped the gun here, so I retracted the invite. I will need to to agree to https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement before I send a new one your way. Can I please have you do that here for the record? Thanks.

**Comment by kiamlaluno** [comment]
@klonos Do you mean reporting in the IS that I agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)?

**Comment by kiamlaluno** [comment]
The change in the module name is intentional, as having a module and a PHP extension with the same name is probably confusing for users. If it's necessary, I will change back the module name, though.

**Comment by klonos** [comment]
Fair enough re the namespace choice @kiamlaluno ...thanks for accepting the agreement. Fresh invite sent your way 🙂 

Let me know if you have any trouble transferring the project over to contrib.

Cheers.

**Comment by klonos** [comment]
I'll go ahead and close this now 🙂
