### ISSUE TITLE
Contrib Group Application: pgrayove-mcpl

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-ops/contrib#700]
Hi,

I've started working on converting a site from Drupal 7 to Backdrop and want to help the community by maintaining modules that I port over.  I've been working with [laryn](https://github.com/laryn) to get started. Just started porting and testing [views_rss](https://github.com/Monroe-County-Public-Library/views_rss).  

Thanks,
Paula

**Comment by klonos** [comment]
Hello @pgrayove-mcpl and welcome to the Backdrop Contrib group! 👋🏼 

Sorry it has taken us so long to reply here. I'll try to review as many of these modules as soon as possible.

Cheers

**Comment by jenlampton** [comment]
@klonos  we only need to review one project to get the maintainer application approved, so let's start here: 

New Project Checklist
---------------------

All projects must meet these minimum requirements.

- [x] Maintain the Git history from Drupal 7. [Confirmed](https://github.com/Monroe-County-Public-Library/views_rss/commits)
- [x] Include a README.md file that includes license and maintainer information. [Confirmed](https://github.com/Monroe-County-Public-Library/views_rss/blob/1.x-2.x/README.md)
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 [Confirmed.](https://github.com/Monroe-County-Public-Library/views_rss/blob/1.x-2.x/LICENSE.txt)

That's it! We'll send over an invitation shortly, and once you accept it, you'll be able to transfer in each project.

**Comment by klonos** [comment]
...started a quick review of https://github.com/Monroe-County-Public-Library/views_rss:
- commit history from 7.x has been retained 👍🏼 
- LICENCE.txt and README.md added and due credits for old maintainers exist 👍🏼 

The only thing I picked up from my quick review of the commit history, is that coder_upgrade automatically used `system.performance` (which doesn't really exist) instead of `system.core` for the conversion of `site_name` and `site_slogan` from variables to config in a few of places(*):
- https://github.com/Monroe-County-Public-Library/views_rss/commit/502bf66abc7f178a7e2cb4bc8bf936a18e840242#diff-bb98c08154ee479b141407987e8d8bfb28f9c537f2d871e9636c60babe11ec23R13
- https://github.com/Monroe-County-Public-Library/views_rss/commit/502bf66abc7f178a7e2cb4bc8bf936a18e840242#diff-bb98c08154ee479b141407987e8d8bfb28f9c537f2d871e9636c60babe11ec23R21
- https://github.com/Monroe-County-Public-Library/views_rss/commit/502bf66abc7f178a7e2cb4bc8bf936a18e840242#diff-bb98c08154ee479b141407987e8d8bfb28f9c537f2d871e9636c60babe11ec23R99
- https://github.com/Monroe-County-Public-Library/views_rss/commit/502bf66abc7f178a7e2cb4bc8bf936a18e840242#diff-bb98c08154ee479b141407987e8d8bfb28f9c537f2d871e9636c60babe11ec23R205

But that shouldn't hold this back.

*Pinging @docwilmot and @bugfolder about that 😉

**Comment by klonos** [comment]
@jenlampton jinx 🙂

**Comment by klonos** [comment]
...quickly reviewed the commit history of the other 3 modules, and only have some nitpicks re formatting and coding standards that are not even worth mentioning. The point is that LICENSE/README files are present in all of them  with proper credits + 7.x commit history has been retained 👍🏼 

Great job @pgrayove-mcpl 🙏🏼 ...as @jenlampton said, all we need from you now is to state with a comment here that you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement), and we'll take it from there.

**Comment by pgrayove-mcpl** [comment]
Thank you all! No worries on the delay as it gave me more time to work on getting projects ready. 

I agree to the Backdrop Contributed Project Agreement.

**Comment by klonos** [comment]
Thank you @pgrayove-mcpl 👍🏼 ...invite should be underway:

> You've invited Paula G.O. to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

You can now follow the instructions in https://github.com/backdrop-ops/contrib#what-to-do-after-your-application-is-accepted to transfer the projects over to the Backdrop contrib group, and create releases for them when ready.

Please let us know if you happen to need any help.

**Comment by argiepiano** [comment]
I believe there is already a Backdrop port of `views_natural_sort` (https://github.com/backdrop-contrib/views_natural_sort), but it has no release. I think @keiserjb was working on it. Perhaps you can collaborate on it, @pgrayove-mcpl?

**Comment by keiserjb** [comment]
One of these days I'll get back to Bloomington.  It's been a long time.

**Comment by jenlampton** [comment]
@pgrayove-mcpl  we are going to close this issue as complete, but if you have any questions or need any assistance feel free to open a new issue.
