### ISSUE TITLE
Port of Rules

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#71]
@quicksketch What would be the best approach to porting of the Drupal Entity API module? I need a lot of its functionality if I am going to port the Rules module. Because of the name clash with the Entity module in core in Backdrop, should I rename everything in the Entity API module to be entityapi e.g. entityapi.module and produce an EntityAPI module for Backdrop, or should I extract the functions and classes I need and add them as an extension to a Backdrop version of Rules?

**Comment by quicksketch** [comment]
Hi @Graham-72! I'd probably try renaming it to something like "Extended Entities" or something like that, maybe `xentity.module`? A lot of what Entity API provided was properly classed entities, which are now in core of course. I think the part that Entity API provides that we don't handle is it's "Entity Wrapper" objects, which allow chaining of data accessing.

If it's at all possible, what I'd encourage you to try is to try and consolidate Rules' usage of Entity API directly into the module. If the data chaining is what Rules needs, consider making that class directly part of Rules module instead of a separate module. Or if there are other small portions of Entity API that are needed, we can evaluate them for including in core's entity.module. In many ways, Backdrop is trying to remove abstraction where possible, which makes code generally easier to understand and manage. This could be an area that would benefit from abstraction reduction.

**Comment by Graham-72** [comment]
Hi @quicksketch thanks for guidance. I will try the consolidation approach, perhaps to a new file within rules e.g. rules.exentity.inc ? I have made a list of the functions and classes needed by rules and put it at https://github.com/Graham-72/rules/blob/1.x-2.x/use_of_entities.md but these in turn will need others so it could get complicated.

**Comment by quicksketch** [comment]
> entity_delete
> entity_save

These two could be put in core. We already have methods for these on all entities. e.g. $node->save() or $node->delete().

> entity_access

I'm not sure how comprehensive this function is. Access checking seems like a good addition to our API as well, but I don't think we have this integrated in core yet. Another good core candidate though.

> entity_var_export
> entity_var_json_export

We can use `backdrop_json()` and `backdrop_var_export()` here, although I think that we'll probably use config instead of whatever variable exporting Rules used previously.

On the first glance, the other functions/objects are unlikely to be available in 1.x. We may be able to find compatible ways of including additional APIs, but I don't think we'll ever implement the data-chaining API that was the centerpiece of Entity API and the D8 entity system.

**Comment by Graham-72** [comment]
I have now copied various required items from the Drupal Entity API module into rules/includes in my Backdrop port of Rules ( https://github.com/Graham-72/rules ), renaming the files extentity .... There is a large quantity of code involved and maybe this can be simplified later, but at the moment I am focussing on getting a working Rules module running on Backdrop. Current status is that is partly working but I have quite a bit more checking to do.

**Comment by Graham-72** [comment]
Nearly done! But this repository is not yet up to date with several fixes. Advice please @quicksketch - I can only set up a rule if I disable Javascript, but not if Ajax is working. Looking at my server logs I see that with Javascript enabled the form is sending "POST /system/ajax HTTP/1.1" - is this correct? What controls the target for posts to Ajax?

**Comment by quicksketch** [comment]
Most Backdrop/Drupal AJAX requests are indeed POST requests to /system/ajax. That's the generic callback that is used by FormAPI when attaching a `#ajax` property onto a form element (usually a submit button). I would suggest using the Network inspector in your browser to see what the response is that is coming back from the server, it will probably contain error messages that you can use to debug.

**Comment by Graham-72** [comment]
Thanks @quicksketch , most helpful as always.

**Comment by Graham-72** [comment]
The repository is now at backdrop-contrib/rules. I look forward to hearing from anyone who tries it.

**Comment by jenlampton** [comment]
Closing this issue because https://github.com/backdrop-contrib/rules exists now.  Please continue all discussion about rules module in the queue for that module.
