### ISSUE TITLE
Contrib Group Application: Alex Höbart

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop-ops/contrib#759]
Dear Backdrop team,

I would like to contribute one or several modules ported from Drupal. I was also invited by laryn to become co-maintainer of ip_geoloc
module (see https://github.com/backdrop-contrib/ip_geoloc/issues/12).

I ported filehash to start with something rather simple, see related Drupal issue at https://www.drupal.org/project/filehash/issues/3425368 and ported module at https://github.com/AlexHoebart-ICPDR/filehash. I think it could already meet your requirements and I would be happy to get your review. 

I have already tested porting cas_server and views_database_connector and can make them available after some clean up. There are some more Drupal modules which I will need but they don't have a Backdrop version, so probably I can't avoid porting them myself.

I agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement).

Thanks for your time and looking forward to your response.

Greetings from Vienna, Austria
Alex

**Comment by laryn** [comment]
@herbdool It looks like the Backdrop changes are not in the 1.x-1.x branch.

**Comment by AlexHoebart-ICPDR** [comment]
Yes, the changes for B are in the backdrop-compatibility branch - I was thinking that this is the way to do it....

**Comment by AlexHoebart-ICPDR** [comment]
I was following this tutorial, maybe it is outdated: https://www.tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2

**Comment by herbdool** [comment]
Okay, that branch looks ok. It seems to meet the requirements IMO. As a final step you should merge it into 1.x-1.x since that's the branch that will get the releases.

Not a biggie, but you don't need the config_clear in the uninstall hook. It'll uninstall automatically if someone has hook_config_info set up

**Comment by jenlampton** [comment]
Hi @AlexHoebart-ICPDR and welcome to Backdrop contrib! 

We have 3 requirements for contrib projects, once these three are met (regardless of the state of any code) we'll be able to send you an invite to join the group.

- [x] Maintain the Git history from Drupal 7 : https://github.com/giant-rabbit/views_block_area/commits/main (although I'd rename the branch to 1.x, but that can be done after the project is transferred to the Backdrop contrib repo too)
- [x] Include a README.md file that includes license and maintainer information 
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

You've met them all!

> I agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement).

Fantastic! In that case, an invite is on the way. 

I would also recommend merging your changes into the `1.x -1.x` branch, and deleting the `backdrop-compatibility` branch since that's likely to confuse people.  

I haven't read through the Tag1 article in a while, but I think the point was simply to have one local copy of the project with lots of local branches, and two different upstreams. Some branches (like `1.x -1.x`) you push to github/backdrop and others (like `7.x-1.x`) goes up to gitlab/drupal. I hope that helps?

**Comment by AlexHoebart-ICPDR** [comment]
> Not a biggie, but you don't need the config_clear in the uninstall hook. It'll uninstall automatically if someone has hook_config_info set up

That was done be Coder Upgrade. I removed it.

> I would also recommend merging your changes into the `1.x -1.x` branch, and deleting the `backdrop-compatibility` branch since that's likely to confuse people.

OK, makes sense. Done.

Thanks for your hints.

**Comment by jenlampton** [comment]
I saw the repo got transferred, thank you so much!  Closing this issue.
