### ISSUE TITLE
Contrib Group Application: hoorack / field-collection-views

### ISSUE THREAD

**Issue by hoorack** [backdrop-ops/contrib#762]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues
Option 1

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**
Field Collection Views

## (option 1) Please note these 3 requirements for new contrib projects:

https://github.com/hoorack/field-collection-views/blob/main/readme.md Include a README.md file containing license and maintainer information.
https://github.com/hoorack/field-collection-views/blob/main/license.txt Include a LICENSE.txt file.
https://git.drupalcode.org/project/field_collection_views/-/commits/7.x-1.x?ref_type=heads If porting a Drupal 7 project, Maintain the Git history from Drupal. (I don't know an easy way to maintain the history in the new repository.)

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

https://www.drupal.org/project/field_collection_views/issues/3433168

**Post a link to your new Backdrop project under your own GitHub account (option 1)**
https://github.com/hoorack/field-collection-views

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by laryn** [comment]
@hoorack Welcome!

I haven't done a thorough review, but I can see that one thing you'll need to do is make sure the commit history from the Drupal module is included. Can you add that to your repo?

**Comment by laryn** [comment]
Oh, I just saw your question:

> (I don't know an easy way to maintain the history in the new repository.)

You should be able to get that history locally using:
`git clone --branch '7.x-1.x' https://git.drupalcode.org/project/field_collection_views.git`

Then add your changes and commits, rename the branch, etc. and change the remote to your repo.

**Comment by argiepiano** [comment]
I find the directions here very helpful:
https://docs.backdropcms.org/converting-modules-from-drupal#creating-the-repository

**Comment by hoorack** [comment]
Thanks @argiepiano & @laryn. Original repo commit history added. Is there anything more to be done?

**Comment by argiepiano** [comment]
@hoorack, thanks! I took a quick look. Here are some suggestions:

- Remove the `files[]` from the info file. In Backdrop, these should be added by implementing `hook_autoload_info()` in the main modujle
- Remove the file `views/field_collection_views.views_default.inc`. In Backdrop, this default View will be created if you put it in `config/VIEW_NAME.json`, which is moved to the config folder when you install the module. To generate the View json file, you can use the module [Default Views Convert to Config](https://backdropcms.org/project/default_views_config), which allows you to import the exported View in Drupal 7, and convert it to json configuration
- There are two License files in your repo.  

I haven't tested the module, but those are the things that "jumped". Also notice there is no official release for Field Collections, so people who try to install your module from within the site UI will not be able to do so, since Field Collection doesn't appear. You may want to lobby the maintainer for Field Collection for a release?

**Comment by argiepiano** [comment]
Also, in the info file, timestamp and version should not be provided if you intend to do an official Backdrop release. The Backdrop module packager will add the needed version and timestamp information.

**Comment by hoorack** [comment]
Thanks, I will have a look at it in the future. But before the "Field collection" module has an official Backdrop release, there is no reason to hurry. 
I just bumped into this when migrating one D7 site and found that D7 "Field Collection Views" module works almost without changes. I will add your comments to issues queue, that's a good start. Thank you again for directions!

**Comment by argiepiano** [comment]
One more thing - your repo is called `field-collection-views` instead of `field_collection_views`. This will create issues for the Backdrop module packager.

**Comment by argiepiano** [comment]
> But before the "Field collection" module has an official Backdrop release, there is no reason to hurry.

Don't hold your breath :) But, even if Field Collection doesn't have a release, having this module in the backdrop-contrib github will still be SUPER helpful, as it will allow people to still install both manually.

**Comment by jenlampton** [comment]
@hoorack welcome, we are happy to have you!!!

Please note that all the suggestions above ARE NOT REQUIRED for you to join the Backdrop contrib group - we just have lots of friendly people who are ready to help you (but only if you want!) 

Below is all that's required :)

> If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

YES (thank you!)

## The 3 requirements for new contrib projects:

- [?] Include a `README.md` file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a `LICENSE.txt` file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

I've left a ? next to the readme, because the file is named `readme.md` instead of `README.md`. though this is a very minor difference, I'm not sure I've ever seen a readme file with the name uncapitalized, and it might(?) cause an issue because the b.org project page is created by scraping this file.

Could you rename that file also, when you remove the duplicate `LICENSE` file (the one without the `.txt`)

**Comment by hoorack** [comment]
Thanks, @jenlampton. Filename adjusted and duplicate license file deleted. Code changes maybe in future...

**Comment by jenlampton** [comment]
## The 3 requirements for new contrib projects:

- [x] Include a `README.md` file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a `LICENSE.txt` file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Thanks @hoorack ! :)  **an invitation to join the Backdrop Contrib group is on the way!** Once you have accepted the invitation, feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

Welcome to contrib!

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have any issues feel free to open a new one :)
