### ISSUE TITLE
Contrib Group Application: AleMadLei + salesforce

### ISSUE THREAD

**Issue by AleMadLei** [backdrop-ops/contrib#783]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
I would like to contribute a project port

## Based on your selection above, please provide the following information:
[Salesforce Suite](https://www.drupal.org/project/salesforce)

Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/salesforce/issues/3445606

**Post a link to your new Backdrop project under your own GitHub account (option 1)**
https://github.com/AleMadLei/salesforce

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment]
Hello @AleMadLei  and welcome!

In order to send you an invite to join the contrib group, your project needs to only meet these 3 requirements for new contrib projects:

- [ ] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal

Could you please rename the `README.txt` file to `README.md` and ajust the contents to use markdown formatting? (This is particularly important because the contents of this file are used to create the project page on backdropcms.org.)

We provide [an example file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) that many people find helpful since some sections that were not in the Drupal READMEs are required for Backdrop. 

Once that change is made we can send you an invitation to join the contrib group!

**Comment by AleMadLei** [comment]
Hello @jenlampton , thank you for the review!

I've updated the README file as requested.

Let me know if there's anything else that is expected.

**Comment by jenlampton** [comment]
Beautiful, all three requirements are met, so an invitation to join the contrib group is on the way! 🎉 

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal

Once you have accepted the invitation, feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (you can ask here if you have questions).

**Comment by jenlampton** [comment]
We're going to close this issue as complete, but feel free to open new issues if you have any questions or need anything else.
