### ISSUE TITLE
How to get forum.module history in Git?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#8]
I decided to try and get forum module working, which I did so far. Everything works well (CMI, upgrade path, API changes and all) except I havent  ported tests. But I cant figure how to keep the Git history from D7 forum module alone.
Also quite frankly I did this just to see if I could, but I dont think I'd have the know-how to maintain it. So can I hand over the current state to someone who would know?

**Comment by quicksketch** [comment]
Hi docwilmot! Boy, this could be a challenge. We did some pretty crazy tricks to get the Views history maintained when we merged it into core, based on this [stack exchange post](http://stackoverflow.com/questions/1759587/un-submodule-a-git-submodule). But this is the opposite, where you're taking a module *out* of core instead of putting one in.

I think the easiest way to do this would be to start with a full D7 checkout, then git remote *everything* except for Forum module. Then move forum module to the root of the repository with git move. Then garbage collect the history of everything that has been removed from the repository (not sure how to do this last one).

Then, once the Git history is trimmed down to just forum, replace the entire forum module with your ported one, and do one additional commit for the entire port to Backdrop.

**Comment by docwilmot** [comment]
Ok, the fact that this all read like ancient Greek confirms that it's beyond me. Above my pay grade sir.

**Comment by quicksketch** [comment]
@docwilmot lol, no problem. I'll work on getting a clean D7 copy of forum as a stand-alone and then you can copy your port over the top. :smile:

**Comment by ultimateboy** [comment]
This is pretty easy with filter-branch. https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ has more info.

**Comment by quicksketch** [comment]
Thanks @ultimateboy! That definitely makes it an easier task. I think I've got it cleaned up now. The whole repo history is now 25MB (previously it was 500MB with a full D7 checkout).

```
git filter-branch --prune-empty --subdirectory-filter modules/forum 7.x
git branch -D 8.x
git tag | xargs git tag -d 
git gc --prune=now --aggressive
```

There were other commands in the middle that I don't think had any effect, so I think that's all the relevant commands. I'll put this up into the Backdrop contrib group and then let @docwilmot go to town on it.

**Comment by quicksketch** [comment]
@docwilmot I pushed up the raw D7 copy of the module into https://github.com/backdrop-contrib/forum. Could you take over with your port, adding a README.md, and LICENSE.txt file? Thanks!

**Comment by docwilmot** [comment]
Thanks. I am getting a 403 error on push. Are the permissions the issue?

**Comment by quicksketch** [comment]
Doh! Sorry, I didn't add the "Authors" group to the repository. You should be able to push now. Thanks!

**Comment by docwilmot** [comment]
All done

**Comment by quicksketch** [comment]
woot woot! :tada:
