### ISSUE TITLE
Contrib Group Application: @Rudy880719

### ISSUE THREAD

**Issue by rudy880719** [backdrop-ops/contrib#813]
I would like to be a member of the Backdrop contribution community, I have migrated the views_timelinejs module with the following github URL [Views-TimelineJS-Backdrop-Port](https://github.com/rudy880719/views_timelinejs), requested by the  following issue https://github.com/backdrop-ops/contrib/issues/779 .
I also created a new [Tiny Slider](https://github.com/rudy880719/tiny_slider) module, it currently does not have a version in Drupal 7, so it had to be created again, following the issue https://github.com/backdrop-ops/contrib/issues/450
I will continue porting others modules, thank you.

**Comment by stpaultim** [comment]
@rudy880719 Here are some questions for you to answer. 

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

**`**You already indicated that you would like to contribute a project.**`** 

Include a link to your project:

`https://github.com/rudy880719/tiny_slider`

## Please note these 3 requirements for new contrib projects:

- [ ] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [ ] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [ ] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**Please, verify that you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
yes/no





---------
Attention: @jenlampton or @klonos 

I've already tested the proposed project and it seems to be working good. 

@argiepiano has already given some feedback on the code. https://github.com/backdrop-ops/contrib/issues/450

I think we just need @rudy880719 to agree to the Backdrop Contributed Project Agreement and add some files to their project.

**Comment by rudy880719** [comment]
Yes, I 'm agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

**Comment by jenlampton** [comment]
Thanks for the confirmation @rudy880719 !

I'm reviewing https://github.com/rudy880719/tiny_slider for the requirements: 

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [ ] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] N/A: If porting a Drupal 7 project, Maintain the Git history from Drupal.

I can see that the README is present and nicely formatted. thank you for that! **Unfortunately, I don't see the the license file. (It is okay to copy the example and commit that to the project). **

I'm checking https://github.com/rudy880719/views_timelinejs also: 

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Since you have met all 3 requirements for contrib on the second project, I'm going to send you an invitation to join contrib, but please do add that missing License file for tiny_slider!

**Comment by rudy880719** [comment]
@jenlampton @stpaultim  Thank you for the opportunity to be part of this community. I appreciate all the suggestions and support I have gotten.

**Comment by jenlampton** [comment]
@rudy880719 I'm going to close this issue as complete, but feel free to open a new issue if you have any questions or other concerns.
