### ISSUE TITLE
Porting APC module

### ISSUE THREAD

**Issue by pablo-romero** [backdrop-ops/contrib#87]
I've made an attempt to port Drupal's APC module to Backdrop: https://github.com/pablo-romero/apc.

Although I finally got it working locally, this is my first port to Backdrop. So there are probably a lot of things to improve.

If any of you are interested in contributing or just testing/reviewing it, you are more than welcome. Any tips or help are really appreciated.

**Comment by quicksketch** [comment]
Hi @pablo-romero! That's great! We're thrilled to see this module ported to Backdrop. I did a spot-check and you've included everything we need to move this into the contrib repository:


New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

You also did a great job porting the tests and swapping out drupal/backdrop functions and variables. I did run across one call to `variable_get()`:

> variable_get('apc_show_debug', FALSE)

Which you can convert either to Config or settings. In this case since it's an internal, developer-only tool I'd recommend you just change that to `settings_get('apc_show_debug', FALSE)`. Settings are options that may be set in `settings.php`, as opposed to configuration, which generally has a UI and is managed via the config files.

If you're up for moving it, we can grant you access to the group if you accept the terms of outlined below.

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by pablo-romero** [comment]
@quicksketch: Thanks a lot for the heads up, I have already converted that one to `settings_get`.

I've also converted:

* All `'cron_key'` references to `state_get`, since it's no longer a config value.
* All `variable_get('cache_lifetime', 0)` to `config_get('system.core','page_cache_maximum_age', 0)`

However, I didn't find any reference to `'cache_prefix'` in config files or states, so I have also set this one as a `settings_get` (to preserve consistency with the rest of configuration values for this module in *settings.php*).

I have locally re-tested the module with logged-in users and different versions of **PHP + APC/APCu** and it works fine (caches items, clears caches, etc.) 

I accept those terms, so if the above is all correct: should I transfer the full repository to **backdrop-contrib**?

**Comment by quicksketch** [comment]
> I accept those terms, so if the above is all correct: should I transfer the full repository to backdrop-contrib?

Excellent! An invite to the group should be in your e-mail. Transferring the repo is the easiest approach, though there are a few gotchas. See http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2.

Great work on porting this module. I'm looking forward to making software together!
