### ISSUE TITLE
Can I get a quick guide for creating releases please?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#88]
Was about to, and realised I am clueless. How do I get the module version number correct in the release? Do I create a branch first, or edit 1.x-1.x branch to 1.x-1.1, commit, release, edit back to 1.x-1.x?
Some quick advice please.

**Comment by quicksketch** [comment]
> How do I get the module version number correct in the release? 

Releases are simply tags, and they're not bound to the branch name at all. So to make a new release, you can start on whatever branch you want (we generally name these 1.x-1.x, but you could do this directly from `master` or any other branch).

So just make a tag and push it:

```
git tag 1.x-1.0.0
git push origin 1.x-1.0.0
```

Then visit your project on GitHub, click on "Releases" at the top of the page. All tags are automatically shown in the list of releases, but they're not "Official" until you edit the tag and put in release notes and give the release a title. I usually name the release the same as the tag.

Optionally, instead of tagging and pushing a tag locally, you create a release tag directly on GitHub from the current tip of any branch. Just be sure to give it a name that matches our convention of `1.x-a.b.c`. If the tag doesn't match the expected format, BackdropCMS.org will attach a `PACKAGING_ERROR_LOG.txt` file to your release on GitHub. Packages (and an error log if any) should be created within a few seconds of creating an official release.

**Comment by docwilmot** [comment]
thanks
