### ISSUE TITLE
Apply to commit to contrib

### ISSUE THREAD

**Issue by quackers8me** [backdrop-ops/contrib#9]
I would like to commit to contrib projects and agree to the author agreement.

I have so far simply added the 'backdrop = 1.x' to about 30 drupal module info files, tested and worked through the cache->get issue that has been mentioned has been rolled back. Is this the type of contrib work you are looking for? What else might be involved?

Jason

**Comment by docwilmot** [comment]
Hi there @quackers8me and welcome. See brief  info on module conversions here:
https://api.backdropcms.org/node/28621.
Since we're using GitHub, you'd need to use Git as well and also have a GitHub account.
Then the ideal process would be to clone the Drupal module you want to convert into a local GitHub repo, apply all the changes recommended in the article I linked to above, including changing the .info file, switching from variables to config etc, then test on a local site to make sure it all works. When its well ported, push it to your own GitHub acct, then announce it here on this contrib issue queue so everyone can see it. 
Then someone will grant you push privileges to push it up to the Backdrop contrib.

Not to self: this should all be in the conversion instructions article on the API site!

**Comment by quackers8me** [comment]
Thank-you I watched the module porting video last week which I would also recommend. I'll begin porting now.

**Comment by quicksketch** [comment]
Thanks @quackers8me! If you complete any full ports, we'd love to include them in the contrib repository. Just give us a link to the module (here on Github) so we can give it an initial review. And then we can add you into the contrib developers group. Thanks for trying out Backdrop! It's pretty exciting to hear that the backwards compatibility layer is working so well.
