### ISSUE TITLE
Request to contribute

### ISSUE THREAD

**Issue by hellomrcat** [backdrop-ops/contrib#95]
Hi, I would like to help port modules to Backdrop. I've been working on porting the [Youtube Field module](https://github.com/hellomrcat/Youtube) (although it's not yet functional), and I agree to the Backdrop Contributed Project Agreement. Thanks :)

-Paul

**Comment by quicksketch** [comment]
Hi Paul! That's excellent!

I checked out https://github.com/hellomrcat/Youtube and it's a good start, nice!

We check all projects for these basic requirements:

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

It looks like this last one isn't done. We like to be able to get the complete history along with all the commit messages for all changes on the original projects. Although most Open Source developers are generous with their work, we need to keep the history intact to maintain the original copyright history.

Let's get the history fixed (you may need to delete the repository and create it again with a fresh checkout) and then we can get this tranfered over. Thanks!

**Comment by hellomrcat** [comment]
@quicksketch I remade the repo and it should be fixed now.

**Comment by quicksketch** [comment]
Yay, excellent! To keep things consistent, could you rename the repository to be "youtube" all lower-case when you transfer it to the https://github.com/backdrop-contrib group? The transferring process is included in this article: http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2

Otherwise, great job! I haven't given it a spin yet but I'm looking forward to it. Invitation sent. After accepting, you should now be able to commit to projects in the backdrop-contrib group.

> and I agree to the Backdrop Contributed Project Agreement

For posterity, here's the current agreementL

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.
