### ISSUE TITLE
Porting Date module : testing 'delete'

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#99]
In the Drupal module 'Date' the tests, such as in date_field.test, check that fields can be created and deleted. 
To delete a field $this->clickLink('delete') is used, which is fine where 'delete' is a simple link on the page.
But how is this done in Backdrop where 'delete' is one option in a select menu? I have been searching for an example. Any advice would be much appreciated.

**Comment by quicksketch** [comment]
> But how is this done in Backdrop where 'delete' is one option in a select menu?

Usually this requires submitting the form of which the element is a part. It usually looks something like this:

```php
$edit = array(
  'action' => 'delete',
);
$button_label = t('Submit');
$this->backdropPost($edit, $button_label);
```

The $edit array should use the "name" attributes from the front-end form, and the label should be the button that needs to be pressed to submit the form. Because SimpleTest can't execute JavaScript, it's often helpful to try performing the steps in a browser with JS disabled. That way all non-AJAX behaviors will be used and will make performing the steps the same as what SimpleTest would execute.

**Comment by Graham-72** [comment]
Thanks @quicksketch . The crucial thing you have pointed out that helps me solve my particular problem is that SimpleTest is executing without JS, and so in this particular case is not seeing 'Delete' as an option in a dropdown.
And so my port of this particular test will now work. Several more to do though.

**Comment by Graham-72** [comment]
Issue resolved with commit
https://github.com/backdrop-contrib/date/commit/c7d8e37
